### ISSUE TITLE
Keepass2Android 1.07b-r0 can't sync with WebDav

### ISSUE THREAD

**Issue by Gladuin** [PhilippC/keepass2android#1014]
Hello,

For a while now, every time I try to sync my db with my WebDav server (not mine actually, it's [STACK](https://stackstorage.com)), it times out / fails with some vague broken pipe error. This has worked before but decided to stop working all of a sudden. If you need any more info, please tell me

**Comment by PhilippC** [comment]
can you please try again with 1.08-pre1 (https://play.google.com/apps/testing/keepass2android.keepass2android). I updated OkHttp - that doesn't mean I'm sure it will work, but at least it might...

**Comment by Gladuin** [comment]
I've just tried it and it still doesnt work sadly..., thanks for your effort anyways though!

I've attatched my log (without passwords) [30-10-2019 07:12:35:717.txt](https://github.com/PhilippC/keepass2android/files/3787234/30-10-2019.07.12.35.717.txt)

**Comment by PhilippC** [comment]
according to https://stackoverflow.com/questions/38016109/javax-net-ssl-sslexception-write-error-ssl-0x7f70604080-i-o-error-during-syst, this might result from a file size limit in the Apache configuration. Do you have access to the server config?

**Comment by Gladuin** [comment]
I do not, since this isn't my server but a companies' that sells online storage. I happened to get 1TB for free and they provide access to it through their webinterface and webdav. Size shouldn't be the problem since I've uploaded bigger files through webdav to their service (5 gigs).

**Comment by Gladuin** [comment]
I have just tried to push a 22MB file to the same URL I use with my KeePass db using curl and it worked fine.

**Comment by beatstream69** [comment]
Hi. My android client can't sync too since okhttp3 update, but for another reason, according to my logs.
`11/8/2019 7:52:40 PM:498 -- Java.Lang.LinkageError: The method 'java.lang.String okhttp3.internal.http.RequestLine.requestPath(okhttp3.HttpUrl)' was expected to be of type static but instead was found to be of type virtual (declaration of 'com.burgstaller.okhttp.digest.DigestAuthenticator' appears in base.apk)
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <d791b02b7879422ba29126cf38d80c64>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <d791b02b7879422ba29126cf38d80c64>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <9f11d06d828c4bc3836dd6ab0672af64>:0 
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.GetRemoteDataAndHash (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& hash) [0x00006] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.CalculateHash (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00000] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00045] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  --- End of managed Java.Lang.LinkageError stack trace ---
java.lang.IncompatibleClassChangeError: The method 'java.lang.String okhttp3.internal.http.RequestLine.requestPath(okhttp3.HttpUrl)' was expected to be of type static but instead was found to be of type virtual (declaration of 'com.burgstaller.okhttp.digest.DigestAuthenticator' appears in base.apk)
	at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticateWithState(DigestAuthenticator.java:233)
	at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticate(DigestAuthenticator.java:176)
	at com.burgstaller.okhttp.DispatchingAuthenticator.authenticate(DispatchingAuthenticator.java:45)
	at com.burgstaller.okhttp.CachingAuthenticatorDecorator.authenticate(CachingAuthenticatorDecorator.java:30)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.kt:213)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:102)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
	at okhttp3.RealCall.execute(RealCall.kt:66)
	at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:120)`

**Comment by PhilippC** [comment]
@beatstream69 which Android version is this?

**Comment by beatstream69** [comment]
Android 9, LineageOS 16, Xiaomi mi5s, Keepass from Google play 1.08-pre3.

**Comment by PhilippC** [comment]
@beatstream69  moved this to https://github.com/PhilippC/keepass2android/issues/1032

**Comment by PhilippC** [comment]
@beatstream69 trying to test #1032, I need a server with Digest Auth. Can you provide testing credentials. (if possible please reply on the #1032 issue, I just cannot @ you there)

**Comment by Gladuin** [comment]
I don't know what caused this, but for some reason it works again...
