### ISSUE TITLE
Java.Lang.LinkageError with 1.08

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#1032]
Hi. My android client can't sync too since okhttp3 update, but for another reason, according to my logs.
`11/8/2019 7:52:40 PM:498 -- Java.Lang.LinkageError: The method 'java.lang.String okhttp3.internal.http.RequestLine.requestPath(okhttp3.HttpUrl)' was expected to be of type static but instead was found to be of type virtual (declaration of 'com.burgstaller.okhttp.digest.DigestAuthenticator' appears in base.apk)
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <d791b02b7879422ba29126cf38d80c64>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <d791b02b7879422ba29126cf38d80c64>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <9f11d06d828c4bc3836dd6ab0672af64>:0 
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.GetRemoteDataAndHash (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& hash) [0x00006] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.CalculateHash (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00000] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00045] in <0e5af143c4a34a5ab0fb6ac3dd129fdc>:0 
  --- End of managed Java.Lang.LinkageError stack trace ---
java.lang.IncompatibleClassChangeError: The method 'java.lang.String okhttp3.internal.http.RequestLine.requestPath(okhttp3.HttpUrl)' was expected to be of type static but instead was found to be of type virtual (declaration of 'com.burgstaller.okhttp.digest.DigestAuthenticator' appears in base.apk)
	at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticateWithState(DigestAuthenticator.java:233)
	at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticate(DigestAuthenticator.java:176)
	at com.burgstaller.okhttp.DispatchingAuthenticator.authenticate(DispatchingAuthenticator.java:45)
	at com.burgstaller.okhttp.CachingAuthenticatorDecorator.authenticate(CachingAuthenticatorDecorator.java:30)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.kt:213)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:102)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
	at okhttp3.RealCall.execute(RealCall.kt:66)
	at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:120)`

_Originally posted by @beatstream69 in https://github.com/PhilippC/keepass2android/issues/1014#issuecomment-551977574_

**Comment by beatstream69** [comment]
@PhilippC 
https://cloud.beatstream.ru/kp_test
user
w7oharLG==
