### ISSUE TITLE
auto-opening a child database (nextcloud) fails

### ISSUE THREAD

**Issue by leo-b** [PhilippC/keepass2android#1051]
I am trying to configure a child database that gets opened automatically with the parent database. Both databases are located on Nextcloud and are using keyfiles that are stored locally on the android device.
The _AutoOpen_ folder contains an entry specific for that android device which has been configured by the "configure child databases" menu in keepass2android.
Unfortunately the child database silently doesn't get opened on unlocking the parent.
When trying to manually open it using
_Database settings_ -> _configure child databases_ -> _DB_NAME_ -> Open
... keepass2android crashes. The stack trace shows a `java.io.FileNotFoundException`.

The _AutoOpen_ entry looks like that:
```
Username: content://com.android.externalstorage.documents/document/80AB-20C9%3ALeo%2Fkeyfilename.key
Password: _db_passwd_
URL: https://leo:NEXTCLOUD_PASSWD@cloud.kloburg.at/remote.php/webdav/DB/child.kdbx
Enabled: True
IfDevice: samsung SM-G930F (_device_id_)
Visible: True
```

Edit:
Due to a missing newline after the markdown code element start, the Username field wasn't shown in the issue report originally. And that seems to be the cause of the problem. (See below.)

**Comment by PhilippC** [comment]
could you please enable debug logging and send me the log after retrying to open the parent database and then manually opening the child? (Make sure the webdav password is not in the log)

**Comment by leo-b** [comment]
It looks like it cannot  handle the `content://` URI to the keyfile:
```content://com.android.externalstorage.documents/document/80AB-20C9%3ALeo%2Fkeyfilename.key```

```
20.11.2019 07:39:03:691 -- error opening file: System.Net.WebException: An exception occurred during a WebClient request. ---> System.NotSupportedException: The URI prefix is not recognized.
  at System.Net.WebRequest.Create (System.Uri requestUri, System.Boolean useUriBase) [0x000ae] in <6bb71ad2e32c42539fc39e7f56312c8d>:0 
  at System.Net.WebRequest.Create (System.Uri requestUri) [0x00014] in <6bb71ad2e32c42539fc39e7f56312c8d>:0 
  at System.Net.WebClient.GetWebRequest (System.Uri address) [0x00000] in <6bb71ad2e32c42539fc39e7f56312c8d>:0 
  at KeePassLib.Serialization.IOWebClient.GetWebRequest (System.Uri address) [0x00000] in <36ac55d2100e4f75b9dd964f8c43c19a>:0 
  at System.Net.WebClient.OpenRead (System.Uri address) [0x0001c] in <6bb71ad2e32c42539fc39e7f56312c8d>:0 
   --- End of inner exception stack trace ---
  at System.Net.WebClient.OpenRead (System.Uri address) [0x00089] in <6bb71ad2e32c42539fc39e7f56312c8d>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient.OpenRead(System.Uri)
  at KeePassLib.Serialization.IOConnection.OpenRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00094] in <36ac55d2100e4f75b9dd964f8c43c19a>:0 
  at KeePassLib.Serialization.IOConnection.ReadFile (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00004] in <36ac55d2100e4f75b9dd964f8c43c19a>:0 
20.11.2019 07:39:03:693 -- Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
  at KeePassLib.Keys.KcpKeyFile.Construct (System.Byte[] pbFileData, KeePassLib.Serialization.IOConnectionInfo iocKeyFile, System.Boolean bThrowIfDbFile) [0x00008] in <36ac55d2100e4f75b9dd964f8c43c19a>:0 
  at KeePassLib.Keys.KcpKeyFile.Construct (KeePassLib.Serialization.IOConnectionInfo iocFile, System.Boolean bThrowIfDbFile) [0x00007] in <36ac55d2100e4f75b9dd964f8c43c19a>:0 
  at KeePassLib.Keys.KcpKeyFile..ctor (System.String strKeyFile) [0x0000d] in <36ac55d2100e4f75b9dd964f8c43c19a>:0 
  at keepass2android.KeeAutoExecExt.AutoOpenEntry (Android.App.Activity activity, keepass2android.AutoExecItem item, System.Boolean bManual) [0x00115] in <a2f69a5acb404d1db04af2e61e5e6fd3>:0 
  at keepass2android.SelectCurrentDbActivity.OpenAutoExecEntries (keepass2android.Database db) [0x00058] in <a2f69a5acb404d1db04af2e61e5e6fd3>:0 
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
	at md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity.n_onActivityResult(Native Method)
	at md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity.onActivityResult(SelectCurrentDbActivity.java:65)
	at android.app.Activity.dispatchActivityResult(Activity.java:7556)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by leo-b** [comment]
This seems to be the same as #984.

**Comment by PhilippC** [comment]
you are right, it's the same cause. Thanks for investigating!
