### ISSUE TITLE
Change Database button closes activity

### ISSUE THREAD

**Issue by MalcolmEvershed** [PhilippC/keepass2android#1111]
In the "Unlock database" screen, when I tap the "Change Database" button, the activity just closes, making it impossible to change database. The process doesn't seem to actually exit. The issue did not exist with version 1.05d.

Android 4.2.x
KeePass2Android Offline 1.07b-r0

1. Run app
2. Tap Create new database
3. Enter password
4. Tap Create Database
5. Tap Lock Database
6. Tap Change Database button. App closes.
7. Run app again.
8. Tap Change Database button. App closes.

Here's the logcat output after tapping Change Database.

```
D/KP2A: PasswordActivity.OnPause
D/KP2A: StackBaseActivity.OnActivityResult Canceled/1
D/KP2A: TryGetFromActivityResult: no data
W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
E/ActivityThread: Activity md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity has leaked IntentReceiver md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity_MyBroadcastReceiver@<address> that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity has leaked IntentReceiver md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity_MyBroadcastReceiver@<address> that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:795)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:596)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1316)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1296)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1290)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:423)
        at md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity.n_onCreate(Native Method)
        at md5b85ab5ea2545156b0f09600c184a5178.SelectCurrentDbActivity.onCreate(SelectCurrentDbActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:5104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
D/KP2A: PasswordActivity.OnStop
D/KP2A: PasswordActivity.OnDestroyTrue
```

Here's the logcat output with version 1.05d which works fine:

```
D/KP2A: PasswordActivity.OnPause
D/KP2A: FileSelect.OnCreate
D/KP2A: FileSelect:apptask=NullTask
D/KP2A: Loaded task keepass2android.NullTask
D/KP2A: OnCreateView
D/KP2A: Recent files visible
D/KP2A: SetAdapter
D/KP2A: OnActCreated
D/KP2A: RefreshList
D/KP2A: FileSelect.OnStart
D/KP2A: FileSelect.OnResume
D/KP2A: PasswordActivity.OnStop
D/KP2A: PasswordActivity.OnDestroyTrue
```

Thank you

**Comment by MalcolmEvershed** [comment]
Thanks for the fast fix!
