### ISSUE TITLE
Synchronisation failure, android denial

### ISSUE THREAD

**Issue by Superkikim** [PhilippC/keepass2android#1211]
Hi, 
I have random sync issues with a file sync from a webdav source (nextcloud based).

I tried to disable local cache. The issue stands. After phone reboot, it opened the right file. Is there anyway I can sort this out ?

```08.04.2020 10:42:44:543 -- DatabaseSettingsActivity.OnPause
08.04.2020 10:42:44:548 -- Timeout start
08.04.2020 10:42:44:579 -- GroupActivity.OnStart
08.04.2020 10:42:44:581 -- GroupActivity.OnResume
08.04.2020 10:42:44:582 --  DatabaseIsUnlocked=True
08.04.2020 10:42:44:582 -- Timeout cancel
08.04.2020 10:42:44:623 -- Java.Lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{28e0539 27492:keepass2android.keepass2android/u0a212} (pid=27492, uid=10212) that is not exported from UID 10008 ---> Android.Util.AndroidException: Remote stack trace:
at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:12704)
at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:13110)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:358)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3551)
at android.os.Binder.execTransact(Binder.java:735)

   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <c8df2d9fc23e4c3e930589657120c656>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <c8df2d9fc23e4c3e930589657120c656>:0
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <9c008a85bab5447b94102e9b8fd19994>:0
  at keepass2android.Io.AndroidContentStorage.IsReadOnly (KeePassLib.Serialization.IOConnectionInfo ioc, keepass2android.Io.OptionalOut`1[T] reason) [0x0003c] in <3169fd143f40409586dc88385b819b66>:0
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{28e0539 27492:keepass2android.keepass2android/u0a212} (pid=27492, uid=10212) that is not exported from UID 10008
at android.os.Parcel.createException(Parcel.java:1950)
at android.os.Parcel.readException(Parcel.java:1918)
at android.os.Parcel.readException(Parcel.java:1868)
at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4118)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:6217)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2607)
at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1828)
at android.content.ContentResolver.query(ContentResolver.java:786)
at android.content.ContentResolver.query(ContentResolver.java:752)
at md5b85ab5ea2545156b0f09600c184a5178.GroupBaseActivity.n_onResume(Native Method)
at md5b85ab5ea2545156b0f09600c184a5178.GroupBaseActivity.onResume(GroupBaseActivity.java:54)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1434)
at android.app.Activity.performResume(Activity.java:7304)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3993)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4033)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6923)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:12704)
at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:13110)
at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:358)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3551)
at android.os.Binder.execTransact(Binder.java:735)


08.04.2020 10:42:45:151 -- DatabaseSettingsActivity.OnStop
08.04.2020 10:42:45:154 -- DatabaseSettingsActivity.OnDestroyTrue
08.04.2020 10:42:47:450 -- status message: Initializing...
08.04.2020 10:42:47:451 -- status submessage:
08.04.2020 10:42:47:476 -- status message: Vérification des changements dans la base de données…
08.04.2020 10:42:47:477 -- status submessage: Chargement du fichier source…
08.04.2020 10:42:52:41 -- GroupActivity.OnPause
08.04.2020 10:42:52:42 -- Timeout start
08.04.2020 10:42:52:61 -- DatabaseSettingsActivity.OnCreate
08.04.2020 10:42:52:61 -- DatabaseSettingsActivity:apptask=
08.04.2020 10:42:52:137 -- DatabaseSettingsActivity.OnStart
08.04.2020 10:42:52:138 -- DatabaseSettingsActivity.OnResume
08.04.2020 10:42:52:139 --  DatabaseIsUnlocked=True
08.04.2020 10:42:52:139 -- Timeout cancel
08.04.2020 10:42:52:795 -- GroupActivity.OnStop```

**Comment by PhilippC** [comment]
Please select Change database - Open Database - Nextcloud to open the file using the built-in nextcloud support (through webdav).
