### ISSUE TITLE
Database open reports "file not found"

### ISSUE THREAD

**Issue by GitHubror** [PhilippC/keepass2android#1463]
I try to use my main database on my android phone. I have transfered the database file to my webspace provided from 1und1.
The file will be recognized and the password entry is shown. After typing the password the message comes up: "Ein Fehler ist aufgetreten: Datei nicht gefunden." The original version for windows opens this file witout any problems. During this test no oher app has this file open.
Log-datei:
05.11.2020 14:51:42:602 -- AppSettingsActivity.OnPause
05.11.2020 14:51:43:214 -- AppSettingsActivity.OnStop
05.11.2020 14:51:45:659 -- AppSettingsActivity.OnStart
05.11.2020 14:51:45:662 -- AppSettingsActivity.OnResume
05.11.2020 14:51:45:663 -- DB null
05.11.2020 14:51:48:923 -- AppSettingsActivity.OnPause
05.11.2020 14:51:49:534 -- AppSettingsActivity.OnStop
05.11.2020 14:51:49:539 -- AppSettingsActivity.OnDestroyTrue
05.11.2020 14:51:51:310 -- AppSettingsActivity.OnCreate
05.11.2020 14:51:51:311 -- AppSettingsActivity:apptask=
05.11.2020 14:51:51:419 -- AppSettingsActivity.OnStart
05.11.2020 14:51:51:420 -- AppSettingsActivity.OnResume
05.11.2020 14:51:51:421 -- DB null
05.11.2020 14:52:04:636 -- AppSettingsActivity.OnPause
05.11.2020 14:52:05:236 -- AppSettingsActivity.OnStop
05.11.2020 14:52:05:239 -- AppSettingsActivity.OnDestroyTrue
05.11.2020 14:52:16:959 -- AppSettingsActivity.OnCreate
05.11.2020 14:52:16:961 -- AppSettingsActivity:apptask=
05.11.2020 14:52:17:103 -- AppSettingsActivity.OnStart
05.11.2020 14:52:17:107 -- AppSettingsActivity.OnResume
05.11.2020 14:52:17:107 -- DB null
05.11.2020 14:52:23:605 -- AppSettingsActivity.OnPause
05.11.2020 14:52:24:235 -- AppSettingsActivity.OnStop
05.11.2020 14:53:28:159 -- AppSettingsActivity.OnStart
05.11.2020 14:53:28:160 -- AppSettingsActivity.OnResume
05.11.2020 14:53:28:160 -- DB null
05.11.2020 14:53:29:231 -- AppSettingsActivity.OnPause
05.11.2020 14:53:29:855 -- AppSettingsActivity.OnStop
05.11.2020 14:53:29:858 -- AppSettingsActivity.OnDestroyTrue
05.11.2020 14:53:46:427 -- Creating application keepass2android.keepass2android. Version=160
05.11.2020 14:53:46:548 -- KeePass.OnCreate
05.11.2020 14:53:46:551 -- KeePass:apptask=
05.11.2020 14:53:46:555 -- Loaded task keepass2android.NullTask
05.11.2020 14:53:46:556 -- KeePass.OnCreate
05.11.2020 14:53:46:571 -- KeePass.OnStart
05.11.2020 14:53:46:572 -- KeePass.OnStart
05.11.2020 14:53:46:686 -- Loaded task keepass2android.NullTask
05.11.2020 14:53:46:771 -- FileSelect.OnCreate
05.11.2020 14:53:46:940 -- FileSelect.OnStart
05.11.2020 14:53:47:540 -- PasswordActivity.OnCreate
05.11.2020 14:53:47:541 -- PasswordActivity:apptask=
05.11.2020 14:53:47:878 -- PasswordActivity.OnStart
05.11.2020 14:53:47:907 -- PasswordActivity.OnResume
05.11.2020 14:53:47:907 -- DB null
05.11.2020 14:53:47:909 -- starting: True, Finishing: False, _performingLoad: False
05.11.2020 14:53:47:960 -- Pre-loading database file starting
05.11.2020 14:53:47:963 -- CFS: OpenWhenNoLocalChanges
05.11.2020 14:53:48:181 -- FileSelect.OnStop
05.11.2020 14:53:48:241 -- FileSelect.OnDestroyTrue
05.11.2020 14:53:48:244 -- KeePass.OnStop
05.11.2020 14:53:48:247 -- KeePass.OnDestroyTrue
05.11.2020 14:53:48:248 -- KeePass.OnDestroyTrue
05.11.2020 14:54:12:288 -- LockingActivity: OnActivityResult 
05.11.2020 14:54:12:296 -- PasswordActivity.OnActivityResult 874348/1000
05.11.2020 14:54:12:469 -- status message: Initializing...
05.11.2020 14:54:12:472 -- status submessage: 
05.11.2020 14:54:12:567 -- status message: Lade Datenbank…
05.11.2020 14:54:12:628 -- System.IO.FileNotFoundException: ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <71fa3b3620f54526b858e23f7088d717>:0 
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <71fa3b3620f54526b858e23f7088d717>:0 
at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <e3e9d5a585d043aaafed2fdc8e851883>:0 
at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
--- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:370)
at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:124)

at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.PasswordActivity.PreloadDbFile () [0x0004c] in <d88b9a7d74f7461c9e9cc57e36dbc807>:0 
at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <b466c5258e1e47298aefb496b82ddec4>:0 
at System.Threading.Tasks.Task.Execute () [0x00000] in <b466c5258e1e47298aefb496b82ddec4>:0 
05.11.2020 14:54:12:641 -- OnFinish message: Ein Fehler ist aufgetreten: 
05.11.2020 14:54:15:709 -- LockingActivity: OnActivityResult 
05.11.2020 14:54:15:711 -- PasswordActivity.OnActivityResult 874348/1000
05.11.2020 14:54:15:732 -- status message: Initializing...
05.11.2020 14:54:15:733 -- status submessage: 
05.11.2020 14:54:15:774 -- status message: Lade Datenbank…
05.11.2020 14:54:15:777 -- CFS: OpenWhenNoLocalChanges
05.11.2020 14:54:16:42 -- System.IO.FileNotFoundException: ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <71fa3b3620f54526b858e23f7088d717>:0 
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <71fa3b3620f54526b858e23f7088d717>:0 
at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <e3e9d5a585d043aaafed2fdc8e851883>:0 
at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
--- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:370)
at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:124)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
at java.lang.Thread.run(Thread.java:919)

at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.LoadDb.Run () [0x000c2] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
05.11.2020 14:54:16:46 -- OnFinish message: Ein Fehler ist aufgetreten: Datei nicht gefunden.
05.11.2020 14:54:18:415 -- LockingActivity: OnActivityResult 
05.11.2020 14:54:18:415 -- PasswordActivity.OnActivityResult 874348/1000
05.11.2020 14:54:18:426 -- status message: Initializing...
05.11.2020 14:54:18:427 -- status submessage: 
05.11.2020 14:54:18:463 -- status message: Lade Datenbank…
05.11.2020 14:54:18:466 -- CFS: OpenWhenNoLocalChanges
05.11.2020 14:54:18:817 -- System.IO.FileNotFoundException: ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <71fa3b3620f54526b858e23f7088d717>:0 
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <71fa3b3620f54526b858e23f7088d717>:0 
at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <e3e9d5a585d043aaafed2fdc8e851883>:0 
at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
--- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:370)
at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:124)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
at java.lang.Thread.run(Thread.java:919)

at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.LoadDb.Run () [0x000c2] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
05.11.2020 14:54:18:819 -- OnFinish message: Ein Fehler ist aufgetreten: Datei nicht gefunden.
05.11.2020 14:54:21:305 -- PasswordActivity.OnPause
05.11.2020 14:54:21:316 -- StackBaseActivity.OnActivityResult Canceled/1
05.11.2020 14:54:21:317 -- TryGetFromActivityResult: no data
05.11.2020 14:54:21:942 -- PasswordActivity.OnStop
05.11.2020 14:54:21:949 -- PasswordActivity.OnDestroyTrue
05.11.2020 14:54:26:545 -- KeePass.OnCreate
05.11.2020 14:54:26:547 -- KeePass:apptask=
05.11.2020 14:54:26:548 -- Loaded task keepass2android.NullTask
05.11.2020 14:54:26:549 -- KeePass.OnCreate
05.11.2020 14:54:26:568 -- KeePass.OnStart
05.11.2020 14:54:26:568 -- KeePass.OnStart
05.11.2020 14:54:26:626 -- Loaded task keepass2android.NullTask
05.11.2020 14:54:26:665 -- FileSelect.OnCreate
05.11.2020 14:54:26:728 -- FileSelect.OnStart
05.11.2020 14:54:26:752 -- KeePass.OnStop
05.11.2020 14:54:26:754 -- KeePass.OnDestroyTrue
05.11.2020 14:54:26:754 -- KeePass.OnDestroyTrue
05.11.2020 14:54:26:783 -- PasswordActivity.OnCreate
05.11.2020 14:54:26:783 -- PasswordActivity:apptask=
05.11.2020 14:54:26:907 -- PasswordActivity.OnStart
05.11.2020 14:54:26:910 -- PasswordActivity.OnResume
05.11.2020 14:54:26:910 -- DB null
05.11.2020 14:54:26:911 -- starting: True, Finishing: False, _performingLoad: False
05.11.2020 14:54:26:919 -- Pre-loading database file starting
05.11.2020 14:54:26:921 -- CFS: OpenWhenNoLocalChanges
05.11.2020 14:54:27:77 -- FileSelect.OnStop
05.11.2020 14:54:27:182 -- FileSelect.OnDestroyTrue
05.11.2020 14:54:28:579 -- PasswordActivity.OnPause
05.11.2020 14:54:28:587 -- StackBaseActivity.OnActivityResult FirstUser/1
05.11.2020 14:54:28:588 -- TryGetFromActivityResult: no data
05.11.2020 14:54:28:693 -- FileSelect.OnCreate
05.11.2020 14:54:28:735 -- FileSelect.OnStart
05.11.2020 14:54:28:737 -- FileSelect.OnResume
05.11.2020 14:54:29:251 -- PasswordActivity.OnStop
05.11.2020 14:54:29:254 -- PasswordActivity.OnDestroyTrue
05.11.2020 14:54:52:286 -- FileSelect.OnPause
05.11.2020 14:54:52:760 -- FileSelect.OnStop
05.11.2020 15:18:56:26 -- Creating application keepass2android.keepass2android. Version=160
05.11.2020 15:18:57:164 -- KeePass.OnCreate
05.11.2020 15:18:57:167 -- KeePass:apptask=
05.11.2020 15:18:57:173 -- Loaded task keepass2android.NullTask
05.11.2020 15:18:57:174 -- KeePass.OnCreate
05.11.2020 15:18:57:189 -- KeePass.OnStart
05.11.2020 15:18:57:190 -- KeePass.OnStart
05.11.2020 15:18:57:306 -- Loaded task keepass2android.NullTask
05.11.2020 15:18:57:389 -- FileSelect.OnCreate
05.11.2020 15:18:57:579 -- FileSelect.OnStart
05.11.2020 15:18:58:199 -- PasswordActivity.OnCreate
05.11.2020 15:18:58:200 -- PasswordActivity:apptask=
05.11.2020 15:18:58:554 -- PasswordActivity.OnStart
05.11.2020 15:18:58:583 -- PasswordActivity.OnResume
05.11.2020 15:18:58:583 -- DB null
05.11.2020 15:18:58:586 -- starting: True, Finishing: False, _performingLoad: False
05.11.2020 15:18:58:638 -- Pre-loading database file starting
05.11.2020 15:18:58:640 -- CFS: OpenWhenNoLocalChanges
05.11.2020 15:18:58:869 -- FileSelect.OnStop
05.11.2020 15:18:58:925 -- FileSelect.OnDestroyTrue
05.11.2020 15:18:58:928 -- KeePass.OnStop
05.11.2020 15:18:58:930 -- KeePass.OnDestroyTrue
05.11.2020 15:18:58:931 -- KeePass.OnDestroyTrue
05.11.2020 15:19:27:406 -- LockingActivity: OnActivityResult 
05.11.2020 15:19:27:414 -- PasswordActivity.OnActivityResult 874348/1000
05.11.2020 15:19:27:611 -- status message: Initializing...
05.11.2020 15:19:27:614 -- status submessage: 
05.11.2020 15:19:27:710 -- status message: Lade Datenbank…
05.11.2020 15:19:27:724 -- LockingActivity: OnActivityResult 
05.11.2020 15:19:27:725 -- PasswordActivity.OnActivityResult 874348/1000
05.11.2020 15:19:27:772 -- System.IO.FileNotFoundException: ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <71fa3b3620f54526b858e23f7088d717>:0 
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <71fa3b3620f54526b858e23f7088d717>:0 
at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <e3e9d5a585d043aaafed2fdc8e851883>:0 
at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
--- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:370)
at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:124)

at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.PasswordActivity.PreloadDbFile () [0x0004c] in <d88b9a7d74f7461c9e9cc57e36dbc807>:0 
at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <b466c5258e1e47298aefb496b82ddec4>:0 
at System.Threading.Tasks.Task.Execute () [0x00000] in <b466c5258e1e47298aefb496b82ddec4>:0 
05.11.2020 15:19:27:788 -- OnFinish message: Ein Fehler ist aufgetreten: 
05.11.2020 15:19:38:38 -- LockingActivity: OnActivityResult 
05.11.2020 15:19:38:39 -- PasswordActivity.OnActivityResult 874348/1000
05.11.2020 15:19:38:56 -- status message: Initializing...
05.11.2020 15:19:38:58 -- status submessage: 
05.11.2020 15:19:38:116 -- status message: Lade Datenbank…
05.11.2020 15:19:38:119 -- CFS: OpenWhenNoLocalChanges
05.11.2020 15:19:38:379 -- System.IO.FileNotFoundException: ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <71fa3b3620f54526b858e23f7088d717>:0 
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <71fa3b3620f54526b858e23f7088d717>:0 
at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <e3e9d5a585d043aaafed2fdc8e851883>:0 
at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
--- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:370)
at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:124)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
at java.lang.Thread.run(Thread.java:919)

at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.LoadDb.Run () [0x000c2] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
05.11.2020 15:19:38:383 -- OnFinish message: Ein Fehler ist aufgetreten: Datei nicht gefunden.
05.11.2020 15:19:56:977 -- LockingActivity: OnActivityResult 
05.11.2020 15:19:56:979 -- PasswordActivity.OnActivityResult 874348/1000
05.11.2020 15:19:56:989 -- status message: Initializing...
05.11.2020 15:19:56:991 -- status submessage: 
05.11.2020 15:19:57:29 -- status message: Lade Datenbank…
05.11.2020 15:19:57:31 -- CFS: OpenWhenNoLocalChanges
05.11.2020 15:19:57:267 -- System.IO.FileNotFoundException: ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <71fa3b3620f54526b858e23f7088d717>:0 
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <71fa3b3620f54526b858e23f7088d717>:0 
at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String path) [0x00029] in <e3e9d5a585d043aaafed2fdc8e851883>:0 
at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
--- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:370)
at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:124)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
at java.lang.Thread.run(Thread.java:919)

at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
at keepass2android.LoadDb.Run () [0x000c2] in <ecd8a7bc4bb24c4d96e8d9b50a750eff>:0 
05.11.2020 15:19:57:270 -- OnFinish message: Ein Fehler ist aufgetreten: Datei nicht gefunden.
05.11.2020 15:20:18:843 -- PasswordActivity.OnPause
05.11.2020 15:20:18:868 -- AppSettingsActivity.OnCreate
05.11.2020 15:20:18:869 -- AppSettingsActivity:apptask=
05.11.2020 15:20:19:111 -- AppSettingsActivity.OnStart
05.11.2020 15:20:19:113 -- AppSettingsActivity.OnResume
05.11.2020 15:20:19:114 -- DB null
05.11.2020 15:20:19:525 -- PasswordActivity.OnStop
05.11.2020 15:20:28:135 -- AppSettingsActivity.OnPause
05.11.2020 15:20:42:897 -- AppSettingsActivity.OnResume
05.11.2020 15:20:42:898 -- DB null
05.11.2020 15:20:49:729 -- AppSettingsActivity.OnPause
05.11.2020 15:20:50:346 -- AppSettingsActivity.OnStop
05.11.2020 15:20:55:514 -- AppSettingsActivity.OnStart
05.11.2020 15:20:55:517 -- AppSettingsActivity.OnResume
05.11.2020 15:20:55:518 -- DB null

**Comment by PhilippC** [comment]
FileNotFound is thrown because the Http response code is 404 (not found). Are you sure you entered the correct URL?

**Comment by GitHubror** [comment]
Yes, this is the same URL copied from the original Keepass version for Windows. This app has no problem using the database.
The error is not reported during input the password for the database. Is the database checked for using password or keyfile?
The first time the report was "Ein Fehler ist aufgetreten:". The second try reports: "Ein Fehler ist aufgetreten: Datei nicht gefunden."
I have also tried to modify the extension of the file. Normally I use a file without extension.
