### ISSUE TITLE
[Bug] v1.08d-r3 keepass2android.SettingsFragment.OnDebugLogChanged

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [PhilippC/keepass2android#1540]
Tried disabling debug log but kp2a freeze until crash with this screen:
![IMG_20210114_043231](https://user-images.githubusercontent.com/46166740/104541859-b4600300-5622-11eb-8a81-1b105eb671c8.jpg)

Until storage went 💯% full.

![IMG_20210114_043600](https://user-images.githubusercontent.com/46166740/104541924-dbb6d000-5622-11eb-9bc9-9e396c763ef1.jpg)
![IMG_20210114_043610](https://user-images.githubusercontent.com/46166740/104541927-dce7fd00-5622-11eb-8fde-3d9793a42112.jpg)

Needed to delete app data and loose all my settings again 😓

```
android.runtime.JavaProxyThrowable: System.IO.IOException: No space left on device
  at Interop.ThrowExceptionForIoErrno (Interop+ErrorInfo errorInfo, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00014] in <df08862c0a5643a6bad3d1f1c3ed090d>:0 
  at Interop.CheckIo (System.Int64 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x0000a] in <df08862c0a5643a6bad3d1f1c3ed090d>:0 
  at Interop.CheckIo (System.Int32 result, System.String path, System.Boolean isDirectory, System.Func`2[T,TResult] errorRewriter) [0x00000] in <df08862c0a5643a6bad3d1f1c3ed090d>:0 
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x0005c] in <df08862c0a5643a6bad3d1f1c3ed090d>:0 
  at System.IO.FileSystem.LinkOrCopyFile (System.String sourceFullPath, System.String destFullPath) [0x0006f] in <df08862c0a5643a6bad3d1f1c3ed090d>:0 
  at System.IO.FileSystem.MoveFile (System.String sourceFullPath, System.String destFullPath) [0x0003a] in <df08862c0a5643a6bad3d1f1c3ed090d>:0 
  at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00083] in <df08862c0a5643a6bad3d1f1c3ed090d>:0 
  at keepass2android.Kp2aLog.FinishLogFile () [0x00057] in <6d7a8113157b45cfb19d69a006588753>:0 
  at keepass2android.SettingsFragment.OnDebugLogChanged (System.Object sender, Android.Preferences.Preference+PreferenceChangeEventArgs e) [0x00013] in <cb7468b0e62249cab241c40310eacb99>:0 
  at Android.Preferences.Preference+IOnPreferenceChangeListenerImplementor.OnPreferenceChange (Android.Preferences.Preference preference, Java.Lang.Object newValue) [0x00015] in <ea21f4e089d145a9b2755a641208df44>:0 
  at Android.Preferences.Preference+IOnPreferenceChangeListenerInvoker.n_OnPreferenceChange_Landroid_preference_Preference_Ljava_lang_Object_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_preference, System.IntPtr native_newValue) [0x00019] in <ea21f4e089d145a9b2755a641208df44>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.124(intptr,intptr,intptr,intptr)
	at mono.android.preference.Preference_OnPreferenceChangeListenerImplementor.n_onPreferenceChange(Native Method)
	at mono.android.preference.Preference_OnPreferenceChangeListenerImplementor.onPreferenceChange(Preference_OnPreferenceChangeListenerImplementor.java:30)
	at android.preference.Preference.callChangeListener(Preference.java:1127)
	at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:73)
	at android.preference.Preference.performClick(Preference.java:1183)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:260)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1219)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3230)
	at android.widget.AbsListView$3.run(AbsListView.java:4186)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by PhilippC** [comment]
did you have the logging enabled for a long time or do you think the large space might result from some kind of endless loop? Is "no space left" something you expected or do you think the log actually caused this?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> did you have the logging enabled for a long time

Yes

> or do you think the large space might result from some kind of endless loop? 

Yes, I can live watch kp2a Data usage in app details grow about 1gb per minute. Without looking at code, the results is like endless loop.

> Is "no space left" something you expected or do you think the log actually caused this?

There was space left beforehand unchecking the log option. But kp2a filled all space left and finally produced above crash report.


![IMG_20210219_160201.jpg](https://user-images.githubusercontent.com/46166740/108555162-6a3f0100-72f5-11eb-8de1-8752d04ab545.jpg)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
#1799
