### ISSUE TITLE
[Bug] v1.08d-r5 opening specific entry forces db close

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [PhilippC/keepass2android#1578]
Everytime accessing a specific Database entry, forces kp2a close the database and return to start screen.

No matter how opened. From group list or search box results, both close db instantly without savings.

Path xxx-ed out. Debug log:

```
19.02.2021 20:39:18:138 -- DatabaseSettingsActivity.OnPause 4
19.02.2021 20:39:18:139 -- Timeout start
19.02.2021 20:39:18:174 -- GroupActivity.OnStart 3
19.02.2021 20:39:18:175 -- GroupActivity.OnResume 3
19.02.2021 20:39:18:176 --  DatabaseIsUnlocked=True 3
19.02.2021 20:39:18:176 -- Timeout cancel
19.02.2021 20:39:18:274 -- DatabaseSettingsActivity.OnStop 4
19.02.2021 20:39:18:277 -- DatabaseSettingsActivity.OnDestroyTrue 4
19.02.2021 20:39:19:503 -- GroupActivity.OnPause 3
19.02.2021 20:39:19:503 -- Timeout start
19.02.2021 20:39:19:536 -- GroupActivity.OnCreate 5
19.02.2021 20:39:19:537 -- GroupActivity:apptask= 5
19.02.2021 20:39:19:539 -- Loaded task keepass2android.NullTask
19.02.2021 20:39:19:539 -- Task in activity GroupActivity 5 changed to NullTask
19.02.2021 20:39:19:578 -- GroupActivity.OnStart 5
19.02.2021 20:39:19:580 -- GroupActivity.OnResume 5
19.02.2021 20:39:19:580 --  DatabaseIsUnlocked=True 5
19.02.2021 20:39:19:581 -- Timeout cancel
19.02.2021 20:39:19:842 -- GroupActivity.OnStop 3
19.02.2021 20:39:30:659 -- GroupActivity.OnPause 5
19.02.2021 20:39:30:660 -- Timeout start
19.02.2021 20:39:30:697 -- EntryActivity.OnCreate 6
19.02.2021 20:39:30:697 -- EntryActivity:apptask= 6
19.02.2021 20:39:30:761 -- Loaded task keepass2android.NullTask
19.02.2021 20:39:30:761 -- Task in activity EntryActivity 6 changed to NullTask
19.02.2021 20:39:30:873 -- EntryActivity.OnStart 6
19.02.2021 20:39:30:877 -- EntryActivity.OnResume 6
19.02.2021 20:39:30:877 --  DatabaseIsUnlocked=True 6
19.02.2021 20:39:30:877 -- Timeout cancel
19.02.2021 20:39:30:979 -- Received intent to provide access to entry
19.02.2021 20:39:31:0 -- Create Combined Notifications: True True True True
19.02.2021 20:39:31:69 -- Received intent to provide access to entry
19.02.2021 20:39:31:99 -- Received intent to provide access to entry
19.02.2021 20:39:31:111 -- GroupActivity.OnStop 5
19.02.2021 20:39:32:179 -- EntryActivity.OnPause 6
19.02.2021 20:39:32:180 -- Timeout start
19.02.2021 20:39:32:213 -- LockingActivity: OnActivityResult 
19.02.2021 20:39:32:213 -- TryGetFromActivityResult: no data
19.02.2021 20:39:32:224 -- GroupActivity.OnStart 5
19.02.2021 20:39:32:226 -- GroupActivity.OnResume 5
19.02.2021 20:39:32:226 --  DatabaseIsUnlocked=True 5
19.02.2021 20:39:32:226 -- Timeout cancel
19.02.2021 20:39:32:326 -- EntryActivity.OnStop 6
19.02.2021 20:39:32:332 -- EntryActivity.OnDestroyTrue 6
19.02.2021 20:39:41:304 -- GroupActivity.OnPause 5
19.02.2021 20:39:41:305 -- Timeout start
19.02.2021 20:39:41:339 -- EntryActivity.OnCreate 7
19.02.2021 20:39:41:340 -- EntryActivity:apptask= 7
19.02.2021 20:39:41:386 -- Loaded task keepass2android.NullTask
19.02.2021 20:39:41:386 -- Task in activity EntryActivity 7 changed to NullTask
19.02.2021 20:39:41:447 -- EntryActivity.OnStart 7
19.02.2021 20:39:41:451 -- EntryActivity.OnResume 7
19.02.2021 20:39:41:451 --  DatabaseIsUnlocked=True 7
19.02.2021 20:39:41:452 -- Timeout cancel
19.02.2021 20:39:42:401 -- Creating application keepass2android.keepass2android. Version=168
19.02.2021 20:39:42:505 -- GroupActivity.OnCreate 0
19.02.2021 20:39:42:507 -- GroupActivity:apptask= 0
19.02.2021 20:39:42:572 -- Loaded task keepass2android.NullTask
19.02.2021 20:39:42:573 -- Task in activity GroupActivity 0 changed to NullTask
19.02.2021 20:39:42:634 -- SelectCurrentDbActivity.OnCreate 1
19.02.2021 20:39:42:635 -- SelectCurrentDbActivity:apptask= 1
19.02.2021 20:39:42:659 -- Loaded task keepass2android.NullTask
19.02.2021 20:39:42:660 -- Task in activity SelectCurrentDbActivity 1 changed to NullTask
19.02.2021 20:39:42:678 -- SelectCurrentDbActivity.OnStart 1
19.02.2021 20:39:42:686 -- SelectCurrentDbActivity 1: OnActivityResult Canceled/0
19.02.2021 20:39:42:687 -- TryGetFromActivityResult: no data
19.02.2021 20:39:42:691 -- SelectCurrentDbActivity.OnResume 1
19.02.2021 20:39:42:691 --  DB null 1
19.02.2021 20:39:42:719 -- SelectCurrentDbActivity.OnPause 1
19.02.2021 20:39:42:753 -- FileSelect.OnCreate
19.02.2021 20:39:42:871 -- FileSelect.OnStart
19.02.2021 20:39:43:69 -- gdrive://XXX isCached = True
19.02.2021 20:39:43:90 -- FileSelect.OnResume
19.02.2021 20:39:43:110 -- GroupActivity.OnDestroyTrue 0
19.02.2021 20:39:43:149 -- FileSelect.OnPause
19.02.2021 20:39:43:339 -- Java.Lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AXXX from pid=4979, uid=10585 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <566a4932caf24fcda317104ab70850f8>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <566a4932caf24fcda317104ab70850f8>:0 
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <210350a8f5b24a2eb0939212781e4e72>:0 
  at keepass2android.Io.AndroidContentStorage.TryGetDisplayName (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& displayName) [0x00017] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AXXX from pid=4979, uid=10585 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	at android.content.ContentResolver.query(ContentResolver.java:946)
	at android.content.ContentResolver.query(ContentResolver.java:881)
	at crc64ae7e22645ed9821f.FileSelectActivity_MyCursorAdapter.n_bindView(Native Method)
	at crc64ae7e22645ed9821f.FileSelectActivity_MyCursorAdapter.bindView(FileSelectActivity_MyCursorAdapter.java:46)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:296)
	at android.widget.AbsListView.obtainView(AbsListView.java:2437)
	at android.widget.ListView.makeAndAddView(ListView.java:2102)
	at android.widget.ListView.fillDown(ListView.java:817)
	at android.widget.ListView.fillFromTop(ListView.java:879)
	at android.widget.ListView.originalLayoutChildren(ListView.java:1873)
	at android.widget.ListView.layoutChildren(ListView.java:1666)
	at android.widget.AbsListView.onLayout(AbsListView.java:2231)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:812)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3192)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2702)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1820)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7782)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

19.02.2021 20:39:43:383 -- FSSA.OnCreate
19.02.2021 20:39:43:513 -- FileSelect.OnStop
19.02.2021 20:39:43:522 -- SelectCurrentDbActivity.OnStop 1
19.02.2021 20:39:45:167 -- Java.Lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AXXX from pid=4979, uid=10585 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <566a4932caf24fcda317104ab70850f8>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <566a4932caf24fcda317104ab70850f8>:0 
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <210350a8f5b24a2eb0939212781e4e72>:0 
  at keepass2android.Io.AndroidContentStorage.TryGetDisplayName (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& displayName) [0x00017] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AXXX from pid=4979, uid=10585 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	at android.content.ContentResolver.query(ContentResolver.java:946)
	at android.content.ContentResolver.query(ContentResolver.java:881)
	at crc64ae7e22645ed9821f.FileSelectActivity_MyCursorAdapter.n_bindView(Native Method)
	at crc64ae7e22645ed9821f.FileSelectActivity_MyCursorAdapter.bindView(FileSelectActivity_MyCursorAdapter.java:46)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:296)
	at android.widget.AbsListView.obtainView(AbsListView.java:2437)
	at android.widget.ListView.makeAndAddView(ListView.java:2102)
	at android.widget.ListView.fillDown(ListView.java:817)
	at android.widget.ListView.fillFromTop(ListView.java:879)
	at android.widget.ListView.originalLayoutChildren(ListView.java:1873)
	at android.widget.ListView.layoutChildren(ListView.java:1666)
	at android.widget.AbsListView.onLayout(AbsListView.java:2231)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:812)
	at android.view.View.layout(View.java:22088)
	at android.view.ViewGroup.layout(ViewGroup.java:6325)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3192)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2702)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1820)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7782)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

19.02.2021 20:39:45:201 -- PasswordActivity.OnCreate 2
19.02.2021 20:39:45:202 -- PasswordActivity:apptask= 2
19.02.2021 20:39:45:420 -- PasswordActivity.OnStart 2
19.02.2021 20:39:45:432 -- PasswordActivity.OnResume 2
19.02.2021 20:39:45:432 --  DB null 2
19.02.2021 20:39:45:433 -- starting: True, Finishing: False, _performingLoad: False
19.02.2021 20:39:45:434 -- gdrive://XXX isCached = True
19.02.2021 20:39:45:455 -- Pre-loading database file starting
19.02.2021 20:39:45:457 -- gdrive://XXX isCached = True
19.02.2021 20:39:45:468 -- gdrive://XXX localVersionHash = CC58040B79AB338EDA8A64912EAAAF2E0C4D7DF61A7C2EF0E53E3FF1E6A2E664
19.02.2021 20:39:45:470 -- gdrive://XXX baseVersionHash = CC58040B79AB338EDA8A64912EAAAF2E0C4D7DF61A7C2EF0E53E3FF1E6A2E664
19.02.2021 20:39:45:471 -- CFS: OpenWhenNoLocalChanges
19.02.2021 20:39:45:471 -- CFS: hashing cached version
19.02.2021 20:39:45:981 -- found 80 in 81
19.02.2021 20:39:46:1 -- cannot autofill
19.02.2021 20:39:46:140 -- FileSelect.OnDestroyTrue
19.02.2021 20:39:57:516 -- gdrive://XXX isCached = True
19.02.2021 20:39:57:537 -- PasswordActivity.OnPause 2
19.02.2021 20:39:57:571 -- FSSA.OnCreate
19.02.2021 20:39:57:681 -- LockingActivity: OnActivityResult 
19.02.2021 20:39:57:683 -- PasswordActivity.OnActivityResult 874348/1000
19.02.2021 20:39:57:684 -- content://com.android.externalstorage.documents/document/home%3AXXX isCached = True
19.02.2021 20:39:57:685 -- LockingActivity: OnActivityResult 
19.02.2021 20:39:57:686 -- PasswordActivity.OnActivityResult 874348/1004
19.02.2021 20:39:57:714 -- PasswordActivity.OnResume 2
19.02.2021 20:39:57:714 --  DB null 2
19.02.2021 20:39:57:717 -- starting: False, Finishing: False, _performingLoad: True
19.02.2021 20:39:57:719 -- gdrive://XXX isCached = True
19.02.2021 20:39:57:774 -- content://com.android.externalstorage.documents/document/home%3AXXX isCached = True
19.02.2021 20:39:57:778 -- content://com.android.externalstorage.documents/document/home%3AXXX localVersionHash = 09AB3F70195ABC3CA2135345791FEDFDF52C1F2637B3E05529BE969D7ACA8B24
19.02.2021 20:39:57:780 -- content://com.android.externalstorage.documents/document/home%3AXXX baseVersionHash = 09AB3F70195ABC3CA2135345791FEDFDF52C1F2637B3E05529BE969D7ACA8B24
19.02.2021 20:39:57:781 -- CFS: OpenWhenNoLocalChanges
19.02.2021 20:39:57:781 -- CFS: hashing cached version
19.02.2021 20:39:57:818 -- CFS: Files in Sync
19.02.2021 20:39:58:55 -- status message: Initializing...
19.02.2021 20:39:58:56 -- status submessage: 
19.02.2021 20:39:58:147 -- status message: Lade Datenbank…
19.02.2021 20:40:05:220 -- CFS: Files in Sync
19.02.2021 20:40:05:233 -- Pre-loading database file completed
19.02.2021 20:40:05:351 -- status submessage: Führe Schlüsseltransformationen durch…
19.02.2021 20:40:44:61 -- status submessage: Lese Datenbank ein…
19.02.2021 20:40:46:854 -- ReadXmlStreamed: 2790ms
19.02.2021 20:40:46:860 -- status submessage: 
19.02.2021 20:40:46:876 -- status message: Aktualisiere lokale Sicherungskopie...
19.02.2021 20:40:46:909 -- Timeout cancel
19.02.2021 20:40:46:927 -- LoadDB OK
19.02.2021 20:40:46:931 -- Starting/Updating OngoingNotificationsService. Database Unlocked
19.02.2021 20:40:47:129 -- PasswordActivity.OnPause 2
19.02.2021 20:40:47:131 -- Timeout start
19.02.2021 20:40:47:154 -- SelectCurrentDbActivity 1: OnActivityResult Ok/1
19.02.2021 20:40:47:156 -- No AppTask in OnActivityResult
19.02.2021 20:40:47:204 -- SelectCurrentDbActivity.OnStart 1
19.02.2021 20:40:47:206 -- SelectCurrentDbActivity.OnResume 1
19.02.2021 20:40:47:207 --  DatabaseIsUnlocked=True 1
19.02.2021 20:40:47:210 -- SelectCurrentDbActivity.OnResume 1
19.02.2021 20:40:47:210 --  DatabaseIsUnlocked=True 1
19.02.2021 20:40:47:216 -- SelectCurrentDbActivity.OnPause 1
19.02.2021 20:40:47:293 -- PasswordActivity.OnCreate 3
19.02.2021 20:40:47:294 -- PasswordActivity:apptask= 3
19.02.2021 20:40:47:356 -- Java.Lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AXXX from pid=4979, uid=10585 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <566a4932caf24fcda317104ab70850f8>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <566a4932caf24fcda317104ab70850f8>:0 
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <210350a8f5b24a2eb0939212781e4e72>:0 
  at keepass2android.Io.AndroidContentStorage.TryGetDisplayName (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& displayName) [0x00017] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AXXX from pid=4979, uid=10585 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	at android.content.ContentResolver.query(ContentResolver.java:946)
	at android.content.ContentResolver.query(ContentResolver.java:881)
	at crc64ae7e22645ed9821f.PasswordActivity.n_onCreate(Native Method)
	at crc64ae7e22645ed9821f.PasswordActivity.onCreate(PasswordActivity.java:54)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

19.02.2021 20:40:47:361 -- PasswordActivity.OnStart 3
19.02.2021 20:40:47:364 -- PasswordActivity.OnResume 3
19.02.2021 20:40:47:364 --  DatabaseIsUnlocked=True 3
19.02.2021 20:40:47:365 -- Timeout cancel
19.02.2021 20:40:47:371 -- starting: True, Finishing: False, _performingLoad: False
19.02.2021 20:40:47:372 -- content://com.android.externalstorage.documents/document/primary%3AXXX isCached = False
19.02.2021 20:40:47:379 -- status message: Initializing...
19.02.2021 20:40:47:380 -- Pre-loading database file starting
19.02.2021 20:40:47:381 -- content://com.android.externalstorage.documents/document/primary%3AXXX isCached = False
19.02.2021 20:40:47:381 -- CFS: OpenWhenNoLocalChanges
19.02.2021 20:40:47:383 -- content://com.android.externalstorage.documents/document/primary%3AXXX isCached = False
19.02.2021 20:40:47:386 -- status submessage: 
19.02.2021 20:40:47:420 -- status message: Lade Datenbank…
19.02.2021 20:40:47:433 -- keepass2android.Io.DocumentAccessRevokedException: Exception of type 'keepass2android.Io.DocumentAccessRevokedException' was thrown.
  at keepass2android.Io.AndroidContentStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00034] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <4c6c2d1dbc9845a29318c8ecde17e542>:0 
  at keepass2android.PasswordActivity.PreloadDbFile () [0x0004c] in <ebaec2cf6eca4155aab0b38c84a3358b>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <8fcd4f83275646e0aa9513c1b05b7be7>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <8fcd4f83275646e0aa9513c1b05b7be7>:0 
19.02.2021 20:40:47:512 -- OnFinish message: Ein Fehler ist aufgetreten: Exception of type 'keepass2android.Io.DocumentAccessRevokedException' was thrown.
19.02.2021 20:40:47:776 -- SelectCurrentDbActivity.OnStop 1
19.02.2021 20:40:47:779 -- PasswordActivity.OnStop 2
19.02.2021 20:40:47:781 -- PasswordActivity.OnDestroyTrue 2
19.02.2021 20:40:49:638 -- PasswordActivity.OnPause 3
19.02.2021 20:40:49:639 -- Timeout start
19.02.2021 20:40:49:661 -- SelectCurrentDbActivity 1: OnActivityResult Canceled/1
19.02.2021 20:40:49:662 -- TryGetFromActivityResult: no data
19.02.2021 20:40:49:669 -- SelectCurrentDbActivity.OnStart 1
19.02.2021 20:40:49:675 -- SelectCurrentDbActivity.OnResume 1
19.02.2021 20:40:49:675 --  DatabaseIsUnlocked=True 1
19.02.2021 20:40:49:724 -- SelectCurrentDbActivity.OnPause 1
19.02.2021 20:40:49:748 -- GroupActivity.OnCreate 4
19.02.2021 20:40:49:748 -- GroupActivity:apptask= 4
19.02.2021 20:40:49:752 -- Loaded task keepass2android.NullTask
19.02.2021 20:40:49:752 -- Task in activity GroupActivity 4 changed to NullTask
19.02.2021 20:40:49:805 -- GroupActivity.OnStart 4
19.02.2021 20:40:49:807 -- GroupActivity.OnResume 4
19.02.2021 20:40:49:807 --  DatabaseIsUnlocked=True 4
19.02.2021 20:40:49:808 -- Timeout cancel
19.02.2021 20:40:50:97 -- SelectCurrentDbActivity.OnStop 1
19.02.2021 20:40:50:98 -- PasswordActivity.OnStop 3
19.02.2021 20:40:50:100 -- PasswordActivity.OnDestroyTrue 3
19.02.2021 20:40:54:307 -- GroupActivity.OnPause 4
19.02.2021 20:40:54:308 -- Timeout start
19.02.2021 20:40:54:341 -- DatabaseSettingsActivity.OnCreate 5
19.02.2021 20:40:54:342 -- DatabaseSettingsActivity:apptask= 5
19.02.2021 20:40:54:504 -- DatabaseSettingsActivity.OnStart 5
19.02.2021 20:40:54:506 -- DatabaseSettingsActivity.OnResume 5
19.02.2021 20:40:54:507 --  DatabaseIsUnlocked=True 5
19.02.2021 20:40:54:508 -- Timeout cancel
19.02.2021 20:40:54:676 -- GroupActivity.OnStop 4
19.02.2021 20:40:59:770 -- DatabaseSettingsActivity.OnPause 5
19.02.2021 20:40:59:773 -- Timeout start
19.02.2021 20:41:03:112 -- DatabaseSettingsActivity.OnResume 5
19.02.2021 20:41:03:113 --  DatabaseIsUnlocked=True 5
19.02.2021 20:41:03:113 -- Timeout cancel

```

**Comment by davidpierson** [comment]
Assuming you can open the db in Keepass2 on a PC - are there any entries in the Advanced section of the entry, under File Attachments?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, I could open the db in Keepass2 on a PC without any problems. No File Attachments existed. So I compared the entry fields and found the otp field had an newline inside its keyvalue somehow. Removed this and kp2a opens it now again and showing totp. I guess the TOTP parser got stuck at the newline.

**Comment by PhilippC** [comment]
closing due to no activity
