### ISSUE TITLE
Exception on biometric unlock setup

### ISSUE THREAD

**Issue by 3Goldjungen** [PhilippC/keepass2android#1603]
Since today (09. March 2021) I get always the following exception if I try to setup the biometric unlock.

```
09.03.2021 21:12:45:650 -- DatabaseSettingsActivity.OnPause 5
09.03.2021 21:12:45:651 -- Timeout start
09.03.2021 21:12:53:136 -- DatabaseSettingsActivity.OnStop 5
09.03.2021 21:13:03:489 -- DatabaseSettingsActivity.OnStart 5
09.03.2021 21:13:03:492 -- DatabaseSettingsActivity.OnResume 5
09.03.2021 21:13:03:492 --  DatabaseIsUnlocked=True 5
09.03.2021 21:13:03:493 -- Timeout cancel
09.03.2021 21:13:19:938 -- DatabaseSettingsActivity.OnPause 5
09.03.2021 21:13:19:940 -- Timeout start
09.03.2021 21:13:19:975 -- BiometricSetupActivity.OnCreate 7
09.03.2021 21:13:19:976 -- BiometricSetupActivity:apptask= 7
09.03.2021 21:13:20:3 -- BiometricSetupActivity.OnStart 7
09.03.2021 21:13:20:4 -- BiometricSetupActivity.OnResume 7
09.03.2021 21:13:20:5 --  DatabaseIsUnlocked=True 7
09.03.2021 21:13:20:5 -- Timeout cancel
09.03.2021 21:13:20:15 -- BiometricHardware available = 0
09.03.2021 21:13:20:290 -- DatabaseSettingsActivity.OnStop 5
09.03.2021 21:13:21:82 -- FP: Create BiometricEncryption
09.03.2021 21:13:21:86 -- FP: CreateKey
09.03.2021 21:13:21:138 -- Java.Lang.RuntimeException: Keystore operation failed ---> Java.Lang.Exception: User authentication required
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <8355ef0a333e4b2bb687dfa0d7a07a88>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <8355ef0a333e4b2bb687dfa0d7a07a88>:0
  at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in <74d23df9f55e4f1e9cce4916ae18a0b2>:0
  at keepass2android.BiometricEncryption.CreateKey () [0x0006c] in <137a58190b124d2a98d7730fbd8892f1>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.security.ProviderException: Keystore operation failed
at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:324)
at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
at android.widget.CompoundButton.toggle(CompoundButton.java:127)
at android.widget.RadioButton.toggle(RadioButton.java:76)
at android.widget.CompoundButton.performClick(CompoundButton.java:132)
at android.view.View.performClickInternal(View.java:6577)
at android.view.View.access$3100(View.java:781)
at android.view.View$PerformClick.run(View.java:25966)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:210)
at android.app.ActivityThread.main(ActivityThread.java:7124)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
Caused by: android.security.KeyStoreException: User authentication required
at android.security.KeyStore.getKeyStoreException(KeyStore.java:813)
... 18 more

09.03.2021 21:13:21:139 -- FP: Init for Enc
09.03.2021 21:13:25:930 -- BiometricSetupActivity.OnPause 7
09.03.2021 21:13:25:932 -- Timeout start
09.03.2021 21:13:25:939 -- Fingerprint: StopListening  without prompt
09.03.2021 21:13:25:980 -- DatabaseSettingsActivity.OnStart 5
09.03.2021 21:13:25:981 -- DatabaseSettingsActivity.OnResume 5
09.03.2021 21:13:25:981 --  DatabaseIsUnlocked=True 5
09.03.2021 21:13:25:982 -- Timeout cancel
09.03.2021 21:13:26:355 -- BiometricSetupActivity.OnStop 7
09.03.2021 21:13:26:358 -- BiometricSetupActivity.OnDestroyTrue 7
09.03.2021 21:13:34:920 -- DatabaseSettingsActivity.OnPause 5
09.03.2021 21:13:34:921 -- Timeout start
09.03.2021 21:13:35:302 -- DatabaseSettingsActivity.OnStop 5
09.03.2021 21:13:48:151 -- DatabaseSettingsActivity.OnStart 5
09.03.2021 21:13:48:153 -- DatabaseSettingsActivity.OnResume 5
09.03.2021 21:13:48:153 --  DatabaseIsUnlocked=True 5
09.03.2021 21:13:48:154 -- Timeout cancel
```

HTC U11 - Android 9
KeePass version 1.09a-pre1

**Comment by PhilippC** [comment]
did your phone get an OS update?

**Comment by 3Goldjungen** [comment]
Hello, 

no the last update was 2019.

But I suspect it is a problem of the device, because now it works again. And at the same time some other apps were affected. 
I don't know what fixed the problem.

So I will close this task because it works now and I can't reproduce the behavior.
