### ISSUE TITLE
Pixel 6 pro bio unlock not working

### ISSUE THREAD

**Issue by wired64** [PhilippC/keepass2android#1907]
On the pixel 6 pro, no worries the first time is setup, but then stops displaying the fingerprint UI.  This is without changes to the prints stored in the system (which the app indicated will occur).

**Comment by MichelJe** [comment]
Having the same issue with Pixel 6 Pro and Android 12
![20220117_060102](https://user-images.githubusercontent.com/48717319/149711206-571b4a31-5f4b-4a6f-8945-b13b6132da2c.jpg)

**Comment by wired64** [comment]
Actually, I'm thinking it may be related to other programs (not just adding fingerprints).  Not to say this may not be a bug, but it's possible that the bug is a side-effect of something else happening (adding a new program with new system requirements, for example).

I'm trying to keep track of what I do on my phone that may cause this to happen - today, I've been getting the fingerprint prompt all day long - yesterday and the day before - no so much.  

If I can winnow down what's related, I'll pass it along!  These issues are tough - I won't be really complaining about this unless there are just a ton of others having the same issue.

**Comment by marno-t** [comment]
Same error for the Pixel 4a and Pixel 4a 5G

**Comment by MichelJe** [comment]
After the system update yesterday it works now on my Pixel6.
Android-Version: 12
Android Secrityupde: 5.Feb 2022

**Comment by MichelJe** [comment]
> @MichelJe was it reinstalled or data cleaned after update ? installed same update but still getting same exception

Nothing. Just updated Android
![Screenshot_20220211-154945](https://user-images.githubusercontent.com/48717319/153613589-f59613a8-9719-4bdf-91bf-e4976e86b768.png)

**Comment by MichelJe** [comment]
Maybe deactivating and reactivating the biometrics for the database might do the trick. (Preferences -> Database -> ~biometrics)

**Comment by marno-t** [comment]
Ok thanks, 4a has got different build


пт, 11 февр. 2022 г., 17:52 MichelJe ***@***.***>:

**Comment by marno-t** [comment]
> Maybe deactivating and reactivating the biometrics for the database might do the trick. (Preferences -> Database -> ~biometrics)

Magic! I got it working now, thanks!

**Comment by PhilippC** [comment]
@wired64 did you try disabling and reactiving biometrics as well?

**Comment by wired64** [comment]
I will give thatva try.

The biometrics have seemed to be more reliable lately.  I know that's doesn't help to track down any issues, but I've had to enter me password less frequently...

Cheers,

SK

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gtgt** [comment]
I have a MI8 with MIUI 12.5. App version is 1.09d-r0. I have the same result using latest stable. Biometric unlock  worked with earlier version of the application or MIUI or both. I don't remember, since it was more than a year ago when I used the feature successfully. Here is the log I collected (I tried to enable biometric unlock in database settings):

```
2022. 07. 27. 18:41:58:99 -- DatabaseSettingsActivity.OnPause 19 2022. 07. 27. 18:41:58:99 -- Timeout start 2022. 07. 27. 18:41:58:143 -- BiometricSetupActivity.OnCreate 20 2022. 07. 27. 18:41:58:143 -- BiometricSetupActivity:apptask= 20 2022. 07. 27. 18:41:58:199 -- BiometricSetupActivity.OnStart 20 2022. 07. 27. 18:41:58:204 -- BiometricSetupActivity.OnResume 20 2022. 07. 27. 18:41:58:204 -- DatabaseIsUnlocked=True 20 2022. 07. 27. 18:41:58:205 -- Timeout cancel 2022. 07. 27. 18:41:58:217 -- BiometricHardware available = 0 2022. 07. 27. 18:41:58:615 -- DatabaseSettingsActivity.OnStop 19 2022. 07. 27. 18:41:59:499 -- FP: Create BiometricEncryption 2022. 07. 27. 18:41:59:501 -- FP: CreateKey 2022. 07. 27. 18:41:59:529 -- Java.Lang.RuntimeException: Keystore operation failed ---> Java.Lang.Exception: User authentication required --- End of inner exception stack trace --- at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in :0 at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in :0 at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in :0 at keepass2android.BiometricEncryption.CreateKey () [0x0006c] in :0 --- End of managed Java.Lang.RuntimeException stack trace --- java.security.ProviderException: Keystore operation failed 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(Unknown Source:220) 	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612) 	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method) 	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30) 	at android.widget.CompoundButton.setChecked(Unknown Source:29) 	at android.widget.CompoundButton.toggle(Unknown Source:4) 	at android.widget.RadioButton.toggle(Unknown Source:6) 	at android.widget.CompoundButton.performClick(Unknown Source:0) 	at android.view.View.performClickInternal(Unknown Source:3) 	at android.view.View.access$3500(Unknown Source:0) 	at android.view.View$PerformClick.run(Unknown Source:8) 	at android.os.Handler.handleCallback(Unknown Source:2) 	at android.os.Handler.dispatchMessage(Unknown Source:4) 	at android.os.Looper.loop(Unknown Source:242) 	at android.app.ActivityThread.main(Unknown Source:98) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11) 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275) Caused by: android.security.KeyStoreException: User authentication required 	at android.security.KeyStore.getKeyStoreException(Unknown Source:102) 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(Unknown Source:216) 	... 17 more 2022. 07. 27. 18:41:59:529 -- FP: Init for Enc 2022. 07. 27. 18:42:01:664 -- FP: Create BiometricEncryption 2022. 07. 27. 18:42:01:666 -- FP: CreateKey 2022. 07. 27. 18:42:01:682 -- Java.Lang.RuntimeException: Keystore operation failed ---> Java.Lang.Exception: User authentication required --- End of inner exception stack trace --- at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in :0 at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in :0 at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in :0 at keepass2android.BiometricEncryption.CreateKey () [0x0006c] in :0 --- End of managed Java.Lang.RuntimeException stack trace --- java.security.ProviderException: Keystore operation failed 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(Unknown Source:220) 	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612) 	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method) 	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30) 	at android.widget.CompoundButton.setChecked(Unknown Source:29) 	at android.widget.CompoundButton.toggle(Unknown Source:4) 	at android.widget.RadioButton.toggle(Unknown Source:6) 	at android.widget.CompoundButton.performClick(Unknown Source:0) 	at android.view.View.performClickInternal(Unknown Source:3) 	at android.view.View.access$3500(Unknown Source:0) 	at android.view.View$PerformClick.run(Unknown Source:8) 	at android.os.Handler.handleCallback(Unknown Source:2) 	at android.os.Handler.dispatchMessage(Unknown Source:4) 	at android.os.Looper.loop(Unknown Source:242) 	at android.app.ActivityThread.main(Unknown Source:98) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11) 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275) Caused by: android.security.KeyStoreException: User authentication required 	at android.security.KeyStore.getKeyStoreException(Unknown Source:102) 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(Unknown Source:216) 	... 17 more 2022. 07. 27. 18:42:01:684 -- FP: Init for Enc 2022. 07. 27. 18:42:02:827 -- FP: Create BiometricEncryption 2022. 07. 27. 18:42:02:830 -- FP: CreateKey 2022. 07. 27. 18:42:02:852 -- Java.Lang.RuntimeException: Keystore operation failed ---> Java.Lang.Exception: User authentication required --- End of inner exception stack trace --- at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in :0 at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in :0 at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in :0 at keepass2android.BiometricEncryption.CreateKey () [0x0006c] in :0 --- End of managed Java.Lang.RuntimeException stack trace --- java.security.ProviderException: Keystore operation failed 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(Unknown Source:220) 	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612) 	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method) 	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30) 	at android.widget.CompoundButton.setChecked(Unknown Source:29) 	at android.widget.CompoundButton.toggle(Unknown Source:4) 	at android.widget.RadioButton.toggle(Unknown Source:6) 	at android.widget.CompoundButton.performClick(Unknown Source:0) 	at android.view.View.performClickInternal(Unknown Source:3) 	at android.view.View.access$3500(Unknown Source:0) 	at android.view.View$PerformClick.run(Unknown Source:8) 	at android.os.Handler.handleCallback(Unknown Source:2) 	at android.os.Handler.dispatchMessage(Unknown Source:4) 	at android.os.Looper.loop(Unknown Source:242) 	at android.app.ActivityThread.main(Unknown Source:98) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11) 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275) Caused by: android.security.KeyStoreException: User authentication required 	at android.security.KeyStore.getKeyStoreException(Unknown Source:102) 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(Unknown Source:216) 	... 17 more 2022. 07. 27. 18:42:02:855 -- FP: Init for Enc 2022. 07. 27. 18:42:05:243 -- BiometricSetupActivity.OnPause 20 2022. 07. 27. 18:42:05:243 -- Timeout start 2022. 07. 27. 18:42:05:248 -- Fingerprint: StopListening without prompt 2022. 07. 27. 18:42:05:270 -- DatabaseSettingsActivity.OnStart 19 2022. 07. 27. 18:42:05:273 -- DatabaseSettingsActivity.OnResume 19 2022. 07. 27. 18:42:05:273 -- DatabaseIsUnlocked=True 19 2022. 07. 27. 18:42:05:273 -- Timeout cancel 2022. 07. 27. 18:42:05:655 -- BiometricSetupActivity.OnStop 20 2022. 07. 27. 18:42:05:658 -- BiometricSetupActivity.OnDestroyTrue 20 
```

Thanks
