### ISSUE TITLE
Samsung S21 biometrics don't work with Keepass

### ISSUE THREAD

**Issue by nanci322** [PhilippC/keepass2android#1914]
I am unable to use the fingerprint access within Keepass on my new Samsung S21 5G Ultra phone.  I get the attached error message when I try to enable biometrics.  How can I get it to work? It worked perfectly on my Samsung Note 9.
![20220119_134934](https://user-images.githubusercontent.com/98073817/150273906-6ba3291d-e4b5-40e4-8486-79ca5e0c9b2d.jpg)

**Comment by gulp79** [comment]
Same error for me, on my Poco F3.
Worked until yesterday, i was on A11 Miui12, then i've updated to A12 Miui 13 and the fingerprint show the same error.

**Comment by markfm62** [comment]
> I am unable to use the fingerprint access within Keepass on my new Samsung S21 5G Ultra phone. I get the attached error message when I try to enable biometrics. How can I get it to work? It worked perfectly on my Samsung Note 9. ![20220119_134934](https://user-images.githubusercontent.com/98073817/150273906-6ba3291d-e4b5-40e4-8486-79ca5e0c9b2d.jpg)

It had been working fine on my s20+, biometric unlock stopped working for this app in the last day or 2.  I've cleared and reset my fingerprints, which work fine for phone unlock, cleared app data, done full uninstall and reinstall of the app (with clearing data), nothing works to get biometric stop unlock functioning, either the uninitialized unlock it the quick unlock.

**Comment by gmotor82** [comment]
I have the smae issues. I can not access to the app because i can not remember the password.
Br
Gabriel

**Comment by jorgeyanesdiez** [comment]
I have an S21 Ultra and it's working fine. Let me know if I can help diagnosing this

**Comment by gmotor82** [comment]
Yes please.
I have activated the Quick Access option, but they would always a password, but i doesn't the password, i used the last 1 year always the Biometric unlock function.
Now i don't no what i can do, too fix my issues.
Br

**Comment by nanci322** [comment]
I got sick of trying to resolve the issue and returned the phone yesterday.  I went back to my Galaxy Note 9 and it works perfectly.

**Comment by markfm62** [comment]
I uninstalled and reinstalled the app on my S20+ running Android 12.  The phone has fingerprints set up, functioning fine for unlock of the phone.  Here's the portion of the k2a log relative to trying to have it use biometric unlock after reinstall.  By any chance should I have been getting prompted for authentication (e.g., PIN) at  "2/3/2022 2:51:30 PM:940 -- Java.Lang.RuntimeException: Keystore key generation failed ---> Java.Lang.Exception: User authentication required"?  (that didn't happen)

2/3/2022 2:51:29 PM:606 -- GroupActivity.OnPause 3
2/3/2022 2:51:29 PM:607 -- Timeout start
2/3/2022 2:51:29 PM:624 -- BiometricSetupActivity.OnCreate 6
2/3/2022 2:51:29 PM:624 -- BiometricSetupActivity:apptask= 6
2/3/2022 2:51:29 PM:646 -- BiometricSetupActivity.OnStart 6
2/3/2022 2:51:29 PM:646 -- BiometricSetupActivity.OnResume 6
2/3/2022 2:51:29 PM:647 --  DatabaseIsUnlocked=True 6
2/3/2022 2:51:29 PM:647 -- Timeout cancel
2/3/2022 2:51:29 PM:650 -- BiometricHardware available = 0
2/3/2022 2:51:30 PM:118 -- GroupActivity.OnStop 3
2/3/2022 2:51:30 PM:929 -- FP: Create BiometricEncryption
2/3/2022 2:51:30 PM:930 -- FP: CreateKey
2/3/2022 2:51:30 PM:940 -- Java.Lang.RuntimeException: Keystore key generation failed ---> Java.Lang.Exception: User authentication required
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <72def2bfa5d341bfbf05115bb5c7ca17>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <72def2bfa5d341bfbf05115bb5c7ca17>:0
  at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in <bf1d22f8b0534a448222ada7cd1a0bfe>:0
  at keepass2android.BiometricEncryption.CreateKey () [0x0006c] in <7165a5adb3574afbabf24b0ad4c46188>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.security.ProviderException: Keystore key generation failed
at android.security.keystore2.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:429)
at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
at android.widget.CompoundButton.setChecked(CompoundButton.java:235)
at android.widget.CompoundButton.toggle(CompoundButton.java:150)
at android.widget.RadioButton.toggle(RadioButton.java:85)
at android.widget.CompoundButton.performClick(CompoundButton.java:155)
at android.view.View.performClickInternal(View.java:7769)
at android.view.View.access$3800(View.java:910)
at android.view.View$PerformClick.run(View.java:30184)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8641)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: android.security.KeyStoreException: User authentication required
at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:382)
at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:59)
at android.security.KeyStoreSecurityLevel.generateKey(KeyStoreSecurityLevel.java:161)
at android.security.keystore2.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:414)
... 18 more

2/3/2022 2:51:30 PM:942 -- FP: Init for Enc
2/3/2022 2:51:33 PM:673 -- BiometricSetupActivity.OnPause 6
2/3/2022 2:51:33 PM:674 -- Timeout start
2/3/2022 2:51:33 PM:677 -- Fingerprint: StopListening  without prompt
2/3/2022 2:51:33 PM:694 -- GroupActivity.OnStart 3
2/3/2022 2:51:33 PM:696 -- GroupActivity.OnResume 3
2/3/2022 2:51:33 PM:696 --  DatabaseIsUnlocked=True 3
2/3/2022 2:51:33 PM:696 -- Timeout cancel
2/3/2022 2:51:34 PM:55 -- BiometricSetupActivity.OnStop 6
2/3/2022 2:51:34 PM:57 -- BiometricSetupActivity.OnDestroyTrue 6
2/3/2022 2:51:38 PM:311 -- GroupActivity.OnPause 3
2/3/2022 2:51:38 PM:312 -- Timeout start
2/3/2022 2:51:38 PM:330 -- DatabaseSettingsActivity.OnCreate 7
2/3/2022 2:51:38 PM:331 -- DatabaseSettingsActivity:apptask= 7
2/3/2022 2:51:38 PM:366 -- DatabaseSettingsActivity.OnStart 7
2/3/2022 2:51:38 PM:367 -- DatabaseSettingsActivity.OnResume 7
2/3/2022 2:51:38 PM:367 --  DatabaseIsUnlocked=True 7
2/3/2022 2:51:38 PM:367 -- Timeout cancel
2/3/2022 2:51:38 PM:817 -- GroupActivity.OnStop 3

**Comment by Nicodonald** [comment]
Same issue here one a oneplus 8T since the Android 12 update.
Tried to clear data, cache and disable fingerprint then re-enable but no luck

**Comment by sengerts** [comment]
Are there any updates on resolving the issue?

**Comment by DoubleJCream** [comment]
Just came accross this issue - I'll throw in my experience, i was just setting up a Samsung A52 5G as my Android phone and I installed Keepass2android and as soon as i try to activate biometrics it started throwing that java error. So from what AI tells me, and it seems correct from what i've tested is that;
Fingerprint biometrics work
FaceID does not because the level of security of the FaceID on this phone is considered sufficient to open the phone but not to unlock a password manager. ;
`Your phone’s front camera uses 2D facial scanning. While Android and Samsung allow this lower-security tier to unlock your lock screen, the operating system blocks it from interacting with the phone's secure hardware encryption chip (the Keystore API). When KeePass2Android requests a secure token for Face Recognition, Android rejects the call, causing the app to crash with that Java runtime error.`

So it looks like i'll be using just the fingerprint with the phone.
hope this helps someone.
