### ISSUE TITLE
Synchronizing/reloading database causes a crash

### ISSUE THREAD

**Issue by BobVul** [PhilippC/keepass2android#1936]
When I manually synchronize my database (on OneDrive), I get the "Reload file?" prompt. When I click OK, the application crashes back to the master password screen.

This seems to be new behaviour with 1.09c-r0. I was previously using 1.08 with no issues.

Exception details:

```
02-21 20:40:23.753  1860  1860 D KP2A    : SelectCurrentDbActivity.OnStart 7
02-21 20:40:23.754  1860  1860 I ViewRootImpl@f7bd763[SelectCurrentDbActivity]: stopped(false) old=false
02-21 20:40:23.755  1860  1860 D KP2A    : SelectCurrentDbActivity.OnResume 7
02-21 20:40:23.755  1860  1860 D KP2A    :  DB null 7
02-21 20:40:23.755  1860  1860 D KP2A    : SelectCurrentDbActivity.OnResume 7
02-21 20:40:23.755  1860  1860 D KP2A    :  DB null 7
02-21 20:40:23.763   513   513 I SurfaceFlinger: SFWD update time=2670996939040013
02-21 20:40:23.765  1860  1860 D KP2A    : System.Exception: Database element not found!
02-21 20:40:23.765  1860  1860 D KP2A    :   at keepass2android.Kp2aApp.FindDatabaseForElement (KeePassLib.Interfaces.IStructureItem element) [0x00015] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.765  1860  1860 D KP2A    :   at keepass2android.view.PwGroupView.PopulateView (Android.Views.View gv, KeePassLib.PwGroup pw) [0x00018] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.765  1860  1860 D KP2A    :   at keepass2android.view.PwGroupView.ConvertView (KeePassLib.PwGroup pw) [0x00000] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.765  1860  1860 D KP2A    :   at keepass2android.PwGroupListAdapter.CreateGroupView (System.Int32 position, Android.Views.View convertView) [0x0002e] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.765  1860  1860 D KP2A    :   at keepass2android.PwGroupListAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00010] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.765  1860  1860 D KP2A    :   at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x00018] in <bf1d22f8b0534a448222ada7cd1a0bfe>:0 
02-21 20:40:23.765  1860  1860 D KP2A    :   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.41(intptr,intptr,int,intptr,intptr)
02-21 20:40:23.769  1860  1860 D AndroidRuntime: Shutting down VM
02-21 20:40:23.771  1860  1860 E AndroidRuntime: FATAL EXCEPTION: main
02-21 20:40:23.771  1860  1860 E AndroidRuntime: Process: keepass2android.keepass2android, PID: 1860
02-21 20:40:23.771  1860  1860 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.Exception: Database element not found!
02-21 20:40:23.771  1860  1860 E AndroidRuntime:   at keepass2android.Kp2aApp.FindDatabaseForElement (KeePassLib.Interfaces.IStructureItem element) [0x00015] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.771  1860  1860 E AndroidRuntime:   at keepass2android.view.PwGroupView.PopulateView (Android.Views.View gv, KeePassLib.PwGroup pw) [0x00018] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.771  1860  1860 E AndroidRuntime:   at keepass2android.view.PwGroupView.ConvertView (KeePassLib.PwGroup pw) [0x00000] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.771  1860  1860 E AndroidRuntime:   at keepass2android.PwGroupListAdapter.CreateGroupView (System.Int32 position, Android.Views.View convertView) [0x0002e] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.771  1860  1860 E AndroidRuntime:   at keepass2android.PwGroupListAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00010] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.771  1860  1860 E AndroidRuntime:   at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x00018] in <bf1d22f8b0534a448222ada7cd1a0bfe>:0 
02-21 20:40:23.771  1860  1860 E AndroidRuntime:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.41(intptr,intptr,int,intptr,intptr)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at crc64dd09b2a2e58bb27d.PwGroupListAdapter.n_getView(Native Method)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at crc64dd09b2a2e58bb27d.PwGroupListAdapter.getView(PwGroupListAdapter.java:74)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:3271)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.ListView.makeAndAddView(ListView.java:2238)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.ListView.fillSpecific(ListView.java:1539)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.ListView.layoutChildren(ListView.java:1936)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.AbsListView.onLayout(AbsListView.java:3041)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:530)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3709)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3161)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:732)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
02-21 20:40:23.771  1860  1860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
02-21 20:40:23.777  1860  1860 I MonoDroid: UNHANDLED EXCEPTION:
02-21 20:40:23.781  1860  1860 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
02-21 20:40:23.781  1860  1860 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
02-21 20:40:23.781  1860  1860 I MonoDroid: android.runtime.JavaProxyThrowable: System.Exception: Database element not found!
02-21 20:40:23.781  1860  1860 I MonoDroid:   at keepass2android.Kp2aApp.FindDatabaseForElement (KeePassLib.Interfaces.IStructureItem element) [0x00015] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.781  1860  1860 I MonoDroid:   at keepass2android.view.PwGroupView.PopulateView (Android.Views.View gv, KeePassLib.PwGroup pw) [0x00018] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.781  1860  1860 I MonoDroid:   at keepass2android.view.PwGroupView.ConvertView (KeePassLib.PwGroup pw) [0x00000] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.781  1860  1860 I MonoDroid:   at keepass2android.PwGroupListAdapter.CreateGroupView (System.Int32 position, Android.Views.View convertView) [0x0002e] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.781  1860  1860 I MonoDroid:   at keepass2android.PwGroupListAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00010] in <7165a5adb3574afbabf24b0ad4c46188>:0 
02-21 20:40:23.781  1860  1860 I MonoDroid:   at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x00018] in <bf1d22f8b0534a448222ada7cd1a0bfe>:0 
02-21 20:40:23.781  1860  1860 I MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.41(intptr,intptr,int,intptr,intptr)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at crc64dd09b2a2e58bb27d.PwGroupListAdapter.n_getView(Native Method)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at crc64dd09b2a2e58bb27d.PwGroupListAdapter.getView(PwGroupListAdapter.java:74)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.AbsListView.obtainView(AbsListView.java:3271)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.ListView.makeAndAddView(ListView.java:2238)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.ListView.fillSpecific(ListView.java:1539)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.ListView.layoutChildren(ListView.java:1936)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.AbsListView.onLayout(AbsListView.java:3041)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.781  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:530)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1099)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.View.layout(View.java:23750)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewGroup.layout(ViewGroup.java:7277)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3709)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3161)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.Choreographer.doFrame(Choreographer.java:732)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.os.Handler.handleCallback(Handler.java:883)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.os.Looper.loop(Looper.java:237)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at java.lang.reflect.Method.invoke(Native Method)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
02-21 20:40:23.782  1860  1860 I MonoDroid: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
02-21 20:40:23.782  1860  1860 I MonoDroid: 
```

**Comment by BobVul** [comment]
Looks like #1909 deals with the same issue, although the commit comment for 40146a suggests this is specific to Android 12 -- I'm running Android 10 on a S9+.

**Comment by DouggieC** [comment]
I can report the same issue on Android 8.0.0, Samsung Galaxy Edge S7.

**Comment by mellonguie** [comment]
Hello,
I'm facing to the same similar issue with 1.09c-r0
I'm using Asus mobile phone with Android 7.1.1
