### ISSUE TITLE
1.04-pre3 keyboard crashes on long-press

### ISSUE THREAD

**Issue by seanrand** [PhilippC/keepass2android#212]
Also can't access the symbols page, clicking the key automatically switches back to QWERTY keyboard.

Android 7.0, device htc_pmeuhl. Issue not present on 1.04-pre2. 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void keepass2android.softkeyboard.LatinKeyboardBaseView.setOnKeyboardActionListener(keepass2android.softkeyboard.LatinKeyboardBaseView$OnKeyboardActionListener)' on a null object reference
	at keepass2android.softkeyboard.LatinKeyboardBaseView.inflateMiniKeyboardContainer(LatinKeyboardBaseView.java:1080)
	at keepass2android.softkeyboard.LatinKeyboardBaseView.onLongPress(LatinKeyboardBaseView.java:1160)
	at keepass2android.softkeyboard.LatinKeyboardView.onLongPress(LatinKeyboardView.java:108)
	at keepass2android.softkeyboard.LatinKeyboardBaseView.openPopupIfRequired(LatinKeyboardBaseView.java:1059)
	at keepass2android.softkeyboard.LatinKeyboardBaseView.access$300(LatinKeyboardBaseView.java:71)
	at keepass2android.softkeyboard.LatinKeyboardBaseView$UIHandler.handleMessage(LatinKeyboardBaseView.java:283)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by metzgore** [comment]
Same here, trying to enter my database password with long-press to access a number crashes immediately.

**Comment by levinus** [comment]
Yep, can confirm the crash and the number / symbols page being not available (switches back instantly). There is also no button to control which field should be filled or to select another entry when the keyboard is in the "insert password". Should I open a new issue with more description and images?

**Comment by auricgoldfinger** [comment]
Any long press crashes the app indeed. Problem occurs since only recently on Oreo using the beta app. Switching keyboards is now only possible using the android notification for me 😊

**Comment by mcarver2000** [comment]
Previously I was able to search/select entries from the KP2A keyboard.  Now I must switch to KP2A manually to search. These are now my only options: Actually, it seems the option is hiding somewhere behind Press the Back Key & Open the keyboard & Touch any text field.

The KP2A key is not present when cursor is placed in password field. Also missing on regular qwerty layout.

Autoswitch is now broken and can crash Chrome (it doesn't actually stop running, but the screen goes black, including the keyboard.

**Comment by lsascha** [comment]
Same issue here on OnePlus 3 with Android 8.0.0

Another issue i noticed is that on some places the Enter key does not show up. So i can only press the smiley key ":-)".

With the crashes, press&hold issue for the special characters etc. the keyboard is really unusable for me at the moment. Have to use copy+paste for passwords which i don't really like since it is easier for 3rd party apps to capture the clipboard.

**Comment by erolha** [comment]
I have the same issue as @Isacha above here. Only the smiley-key available (no Enter-key). In addition, when pressing the "?123"-key the keyboard drops one row down, hiding the row further most down below the screen.
Huawei P9 with Android 7.0.

**Comment by PhilippC** [comment]
What a weird bug. It seems like the build was somehow broken. Simply rebuilding the app seems to fix it. Uploading to the beta channel right now.
