### ISSUE TITLE
Couldn't open OneDrive files

### ISSUE THREAD

**Issue by Piroro-hs** [PhilippC/keepass2android#2192]
The app crashes everytime when I tap Open file -> OneDrive -> one of options.
Same for latest and latest beta on Play store.

```
2023/01/14 1:56:37:132 -- GroupActivity.OnStart 8
2023/01/14 1:56:37:135 -- GroupActivity.OnResume 8
2023/01/14 1:56:37:135 --  DatabaseIsUnlocked=True 8
2023/01/14 1:56:37:136 -- Timeout cancel
2023/01/14 1:56:39:751 -- GroupActivity.OnPause 8
2023/01/14 1:56:39:754 -- Timeout start
2023/01/14 1:56:39:776 -- SelectCurrentDbActivity 7: OnActivityResult FirstUser/0
2023/01/14 1:56:39:777 -- AppTask keepass2android.NullTask in OnActivityResult
2023/01/14 1:56:39:778 -- Task in activity SelectCurrentDbActivity 7 changed to NullTask
2023/01/14 1:56:39:782 -- Task in activity SelectCurrentDbActivity 7 changed to NullTask
2023/01/14 1:56:39:783 -- Finishing SelectCurrentDbActivity 7
2023/01/14 1:56:39:800 -- Finishing SelectCurrentDbActivity 7
2023/01/14 1:56:39:885 -- SelectCurrentDbActivity.OnDestroyTrue 7
2023/01/14 1:56:40:314 -- GroupActivity.OnStop 8
2023/01/14 1:56:40:320 -- GroupActivity.OnDestroyTrue 8
2023/01/14 1:56:42:613 -- KeePass.OnCreate 10
2023/01/14 1:56:42:614 -- KeePass:apptask= 10
2023/01/14 1:56:42:614 -- Loaded task keepass2android.NullTask
2023/01/14 1:56:42:614 -- Task in activity KeePass 10 changed to NullTask
2023/01/14 1:56:42:614 -- KeePass.OnCreate
2023/01/14 1:56:42:618 -- KeePass.OnStart 10
2023/01/14 1:56:42:620 -- KeePass.OnStart
2023/01/14 1:56:42:652 -- SelectCurrentDbActivity.OnCreate 11
2023/01/14 1:56:42:652 -- SelectCurrentDbActivity:apptask= 11
2023/01/14 1:56:42:658 -- Loaded task keepass2android.NullTask
2023/01/14 1:56:42:658 -- Task in activity SelectCurrentDbActivity 11 changed to NullTask
2023/01/14 1:56:42:663 -- SelectCurrentDbActivity.OnStart 11
2023/01/14 1:56:42:664 -- SelectCurrentDbActivity.OnResume 11
2023/01/14 1:56:42:665 --  DatabaseIsUnlocked=True 11
2023/01/14 1:56:42:671 -- SelectCurrentDbActivity.OnPause 11
2023/01/14 1:56:42:681 -- GroupActivity.OnCreate 12
2023/01/14 1:56:42:681 -- GroupActivity:apptask= 12
2023/01/14 1:56:42:683 -- Loaded task keepass2android.NullTask
2023/01/14 1:56:42:683 -- Task in activity GroupActivity 12 changed to NullTask
2023/01/14 1:56:42:703 -- GroupActivity.OnStart 12
2023/01/14 1:56:42:703 -- GroupActivity.OnResume 12
2023/01/14 1:56:42:704 --  DatabaseIsUnlocked=True 12
2023/01/14 1:56:42:704 -- Timeout cancel
2023/01/14 1:56:42:713 -- SelectCurrentDbActivity.OnStop 11
2023/01/14 1:56:42:714 -- KeePass.OnStop 10
2023/01/14 1:56:42:714 -- KeePass.OnDestroyTrue
2023/01/14 1:56:42:715 -- KeePass.OnDestroyTrue 10
2023/01/14 1:56:44:974 -- GroupActivity.OnPause 12
2023/01/14 1:56:44:975 -- Timeout start
2023/01/14 1:56:45:6 -- DatabaseSettingsActivity.OnCreate 13
2023/01/14 1:56:45:6 -- DatabaseSettingsActivity:apptask= 13
2023/01/14 1:56:45:66 -- DatabaseSettingsActivity.OnStart 13
2023/01/14 1:56:45:67 -- DatabaseSettingsActivity.OnResume 13
2023/01/14 1:56:45:67 --  DatabaseIsUnlocked=True 13
2023/01/14 1:56:45:68 -- Timeout cancel
2023/01/14 1:56:45:517 -- GroupActivity.OnStop 12
2023/01/14 1:56:50:588 -- DatabaseSettingsActivity.OnPause 13
2023/01/14 1:56:50:590 -- Timeout start
2023/01/14 1:56:50:610 -- GroupActivity.OnStart 12
2023/01/14 1:56:50:611 -- GroupActivity.OnResume 12
2023/01/14 1:56:50:612 --  DatabaseIsUnlocked=True 12
2023/01/14 1:56:50:613 -- Timeout cancel
2023/01/14 1:56:51:89 -- DatabaseSettingsActivity.OnStop 13
2023/01/14 1:56:51:98 -- DatabaseSettingsActivity.OnDestroyTrue 13
2023/01/14 1:56:56:264 -- GroupActivity.OnPause 12
2023/01/14 1:56:56:265 -- Timeout start
2023/01/14 1:56:56:276 -- SelectCurrentDbActivity 11: OnActivityResult 11/0
2023/01/14 1:56:56:277 -- AppTask keepass2android.NullTask in OnActivityResult
2023/01/14 1:56:56:278 -- Task in activity SelectCurrentDbActivity 11 changed to NullTask
2023/01/14 1:56:56:293 -- SelectCurrentDbActivity.OnStart 11
2023/01/14 1:56:56:295 -- SelectCurrentDbActivity.OnResume 11
2023/01/14 1:56:56:295 --  DatabaseIsUnlocked=True 11
2023/01/14 1:56:56:295 -- SelectCurrentDbActivity.OnResume 11
2023/01/14 1:56:56:296 --  DatabaseIsUnlocked=True 11
2023/01/14 1:56:56:414 -- SelectCurrentDbActivity.OnPause 11
2023/01/14 1:56:56:433 -- FileSelect.OnCreate
2023/01/14 1:56:56:458 -- FileSelect.OnStart
2023/01/14 1:56:56:459 -- FileSelect.OnResume
2023/01/14 1:56:56:523 -- SelectCurrentDbActivity.OnStop 11
2023/01/14 1:56:56:933 -- GroupActivity.OnStop 12
2023/01/14 1:56:56:936 -- GroupActivity.OnDestroyTrue 12
2023/01/14 1:56:57:483 -- FileSelect.OnPause
2023/01/14 1:56:57:508 -- SelectStorageLocationActivity.OnCreate
2023/01/14 1:56:58:61 -- FileSelect.OnStop
2023/01/14 1:57:01:854 -- onAR
2023/01/14 1:57:01:854 -- base.onAR
2023/01/14 1:57:01:862 -- FSSIA: StartSelectFileProcess 
2023/01/14 1:57:01:916 -- FSSA.OnCreate
2023/01/14 1:57:02:999 -- MSAL.Xamarin.Android.4.8.2.0.MsalClientException: 
	ErrorCode: android_activity_not_found
Microsoft.Identity.Client.MsalClientException: The Activity cannot be found to launch the given Intent. To ensure authentication, a browser with custom tab support is recommended. See https://aka.ms/msal-net-system-browsers for more details on using system browser on Android. ---> Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://login.microsoftonline.com/... }
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <72def2bfa5d341bfbf05115bb5c7ca17>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00063] in <72def2bfa5d341bfbf05115bb5c7ca17>:0 
  at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <380403efe49b41d2b4dd79140f0127b0>:0 
  at Microsoft.Identity.Client.Platforms.Android.SystemWebview.AuthenticationActivity.OnResume () [0x00067] in <e1f7bc6344d14ae4a7c4b2729af2924b>:0 
   --- End of inner exception stack trace ---
  at Microsoft.Identity.Client.Platforms.Android.SystemWebview.AuthenticationActivity.OnResume () [0x00081] in <e1f7bc6344d14ae4a7c4b2729af2924b>:0 
  at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <380403efe49b41d2b4dd79140f0127b0>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.47(intptr,intptr)
Inner Excception: Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://login.microsoftonline.com/... }
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <72def2bfa5d341bfbf05115bb5c7ca17>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00063] in <72def2bfa5d341bfbf05115bb5c7ca17>:0 
  at Android.Content.ContextWrapper.StartActivity (Android.Content.Intent intent) [0x00031] in <380403efe49b41d2b4dd79140f0127b0>:0 
  at Microsoft.Identity.Client.Platforms.Android.SystemWebview.AuthenticationActivity.OnResume () [0x00067] in <e1f7bc6344d14ae4a7c4b2729af2924b>:0 
  --- End of managed Android.Content.ActivityNotFoundException stack trace ---
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://login.microsoftonline.com/... }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
	at android.app.Activity.startActivityForResult(Activity.java:5211)
	at android.app.Activity.startActivityForResult(Activity.java:5169)
	at android.app.Activity.startActivity(Activity.java:5540)
	at android.app.Activity.startActivity(Activity.java:5508)
	at microsoft.identity.client.AuthenticationActivity.n_onResume(Native Method)
	at microsoft.identity.client.AuthenticationActivity.onResume(AuthenticationActivity.java:48)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
	at android.app.Activity.performResume(Activity.java:7962)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4231)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4273)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2052)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7452)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

2023/01/14 1:57:03:566 -- Creating application keepass2android.keepass2android. Version=186
2023/01/14 1:57:03:625 -- SelectStorageLocationActivity.OnCreate
2023/01/14 1:57:03:634 -- onAR
2023/01/14 1:57:03:635 -- base.onAR
2023/01/14 1:57:03:693 -- FileSelect.OnCreate
2023/01/14 1:57:03:774 -- FileSelect.OnStart
2023/01/14 1:57:03:777 -- FileSelect.OnResume
2023/01/14 1:57:13:335 -- content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2Fseki63hi%2540hotmail.co.jp%2FItem%2FRID%2F37BBEABED20BBCC0%2521978%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1 isCached = True
2023/01/14 1:57:13:507 -- FileSelect.OnPause
2023/01/14 1:57:13:550 -- PasswordActivity.OnCreate 0
2023/01/14 1:57:13:551 -- PasswordActivity:apptask= 0
2023/01/14 1:57:13:786 -- GetIocFromLaunchIntent()
2023/01/14 1:57:13:786 -- no keyprovider specified
2023/01/14 1:57:13:790 -- Reset keyfile
2023/01/14 1:57:13:819 -- PasswordActivity.OnStart 0
2023/01/14 1:57:13:826 -- PasswordActivity.OnResume 0
2023/01/14 1:57:13:826 --  DB null 0
2023/01/14 1:57:13:827 -- starting: True, Finishing: False, _performingLoad: False
2023/01/14 1:57:13:829 -- content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2Fseki63hi%2540hotmail.co.jp%2FItem%2FRID%2F37BBEABED20BBCC0%2521978%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1 isCached = True
2023/01/14 1:57:13:853 -- Pre-loading database file starting
2023/01/14 1:57:13:854 -- content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2Fseki63hi%2540hotmail.co.jp%2FItem%2FRID%2F37BBEABED20BBCC0%2521978%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1 isCached = True
2023/01/14 1:57:13:860 -- content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2Fseki63hi%2540hotmail.co.jp%2FItem%2FRID%2F37BBEABED20BBCC0%2521978%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1 localVersionHash = E0BCB4E3623A233DCB5A9538FA39E0B8DCE503CBDD69604FA9280219EE2FFE14
2023/01/14 1:57:13:861 -- content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2Fseki63hi%2540hotmail.co.jp%2FItem%2FRID%2F37BBEABED20BBCC0%2521978%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1 baseVersionHash = E0BCB4E3623A233DCB5A9538FA39E0B8DCE503CBDD69604FA9280219EE2FFE14
2023/01/14 1:57:13:861 -- CFS: OpenWhenNoLocalChanges
2023/01/14 1:57:13:862 -- CFS: hashing cached version
2023/01/14 1:57:13:902 -- CFS: Files in Sync
2023/01/14 1:57:13:905 -- Pre-loading database file completed
2023/01/14 1:57:13:912 -- PasswordModeSpinner item selected: 0
2023/01/14 1:57:14:43 -- found 80 in 81
2023/01/14 1:57:14:57 -- cannot autofill
2023/01/14 1:57:14:335 -- FileSelect.OnStop
2023/01/14 1:57:14:379 -- FileSelect.OnDestroyTrue
2023/01/14 1:57:20:192 -- content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2Fseki63hi%2540hotmail.co.jp%2FItem%2FRID%2F37BBEABED20BBCC0%2521978%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1 isCached = True
2023/01/14 1:57:20:208 -- LockingActivity: OnActivityResult 
2023/01/14 1:57:20:226 -- PasswordActivity.OnActivityResult 874348/1000
2023/01/14 1:57:20:306 -- status message: Initializing...
2023/01/14 1:57:20:307 -- status submessage: 
2023/01/14 1:57:20:342 -- status message: データベース読込中…
2023/01/14 1:57:20:376 -- status submessage: マスターキーを変換しています…
2023/01/14 1:57:21:599 -- status submessage: データベースを解析しています…
2023/01/14 1:57:21:705 -- ReadXmlStreamed: 104ms
2023/01/14 1:57:21:718 -- status submessage: 
2023/01/14 1:57:21:722 -- status message: ローカルバックアップを更新しています...
2023/01/14 1:57:21:800 -- Timeout cancel
2023/01/14 1:57:21:814 -- LoadDB OK
2023/01/14 1:57:21:820 -- Starting/Updating OngoingNotificationsService. Database Unlocked
2023/01/14 1:57:21:996 -- PasswordActivity.OnPause 0
2023/01/14 1:57:21:999 -- Timeout start
2023/01/14 1:57:22:22 -- SelectCurrentDbActivity.OnCreate 1
2023/01/14 1:57:22:22 -- SelectCurrentDbActivity:apptask= 1
2023/01/14 1:57:22:31 -- Loaded task keepass2android.NullTask
2023/01/14 1:57:22:32 -- Task in activity SelectCurrentDbActivity 1 changed to NullTask
2023/01/14 1:57:22:45 -- SelectCurrentDbActivity.OnStart 1
2023/01/14 1:57:22:49 -- SelectCurrentDbActivity 1: OnActivityResult Ok/1
2023/01/14 1:57:22:50 -- No AppTask in OnActivityResult
2023/01/14 1:57:22:69 -- SelectCurrentDbActivity.OnResume 1
2023/01/14 1:57:22:69 --  DatabaseIsUnlocked=True 1
2023/01/14 1:57:22:70 -- SelectCurrentDbActivity.OnResume 1
2023/01/14 1:57:22:70 --  DatabaseIsUnlocked=True 1
2023/01/14 1:57:22:73 -- SelectCurrentDbActivity.OnPause 1
2023/01/14 1:57:22:93 -- GroupActivity.OnCreate 2
2023/01/14 1:57:22:93 -- GroupActivity:apptask= 2
2023/01/14 1:57:22:102 -- Loaded task keepass2android.NullTask
2023/01/14 1:57:22:102 -- Task in activity GroupActivity 2 changed to NullTask
2023/01/14 1:57:22:156 -- GroupActivity.OnStart 2
2023/01/14 1:57:22:158 -- GroupActivity.OnResume 2
2023/01/14 1:57:22:158 --  DatabaseIsUnlocked=True 2
2023/01/14 1:57:22:159 -- Timeout cancel
2023/01/14 1:57:22:349 -- SelectCurrentDbActivity.OnStop 1
2023/01/14 1:57:22:711 -- PasswordActivity.OnStop 0
2023/01/14 1:57:22:720 -- PasswordActivity.OnDestroyTrue 0
2023/01/14 1:57:24:580 -- GroupActivity.OnPause 2
2023/01/14 1:57:24:581 -- Timeout start
2023/01/14 1:57:24:641 -- DatabaseSettingsActivity.OnCreate 3
2023/01/14 1:57:24:642 -- DatabaseSettingsActivity:apptask= 3
2023/01/14 1:57:24:799 -- DatabaseSettingsActivity.OnStart 3
2023/01/14 1:57:24:799 -- DatabaseSettingsActivity.OnResume 3
2023/01/14 1:57:24:800 --  DatabaseIsUnlocked=True 3
2023/01/14 1:57:24:800 -- Timeout cancel
2023/01/14 1:57:25:256 -- GroupActivity.OnStop 2
```

**Comment by Piroro-hs** [comment]
Ok, my phone apparently doesn't have any valid web browser app at that time. Solved.
