### ISSUE TITLE
Fingerprint error on Xiaomi 4 Prime

### ISSUE THREAD

**Issue by odooleg** [PhilippC/keepass2android#220]
This is observed in all devices of this model. Here is the error code: 

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
... 1 more
Caused by: javax.crypto.AEADBadTagException
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:484)
at javax.crypto.Cipher.doFinal(Cipher.java:1502)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
at android.os.Handler.handleCallback(Handler.java:742)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5555)
... 3 more
Caused by: android.security.KeyStoreException: Signature/MAC verification failed
at android.security.KeyStore.getKeyStoreException(KeyStore.java:632)
at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:473)
... 10 more

**Comment by PhilippC** [comment]
if your password has any non-ASCII character, please create a test database with a simple password (e.g. "test") and try to enable fingerprint unlock for that database. Can you please report if that works?

**Comment by odooleg** [comment]
Does not work. All Xiaomi 4 Prime users do not have fingerprints. The problem has always been.

**Comment by vitaliypo** [comment]
Constantly meet this problem too on Redmi 4 Prime

**Comment by PhilippC** [comment]
Sorry but this seems to be an incorrect implementation of the Fingerprint API, so there is nothing I can do about that. Other apps have the same problem with this device (see for example http://en.miui.com/thread-489493-1-1.html or https://discussions.agilebits.com/discussion/comment/366528)
