### ISSUE TITLE
1.09e-r1 crash after import database by SFTP

### ISSUE THREAD

**Issue by playersct** [PhilippC/keepass2android#2223]
Hello :)

Galaxy S23+
After import database by SFTP app immediately crash.
In 1.09d-r0 work without problem

**Comment by hyproman** [comment]
I was able to reproduce this one. It's an Android API compatibility issue regarding the way the "New Identity" and "Add To Authorized Hosts" dialog boxes are created. This is an issue

```
E AndroidRuntime: java.lang.IllegalArgumentException: keepass2android.keepass2android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E AndroidRuntime:        at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
E AndroidRuntime:        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:487)
E AndroidRuntime:        at android.app.PendingIntent.getActivity(PendingIntent.java:473)
E AndroidRuntime:        at android.app.PendingIntent.getActivity(PendingIntent.java:437)
E AndroidRuntime:        at keepass2android.javafilestorage.SftpUserInfo$1.run(SftpUserInfo.java:54)
```

I will submit a PR for review that should fix this.
