### ISSUE TITLE
nonet version chrashes on start

### ISSUE THREAD

**Issue by Boebbele** [PhilippC/keepass2android#2273]
App (nonet version) chrash on start since update from r3 to r4. Testet on /e/os android 11 and iodeos android 13.

**Comment by hyproman** [comment]
I was able to reproduce this. This is the error:

```
D KP2A    : System.NullReferenceException: Object reference not set to an instance of an object
D KP2A    :   at keepass2android.SelectCurrentDbActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00036] in <9677545fef204e6b85d438458b767b5f>:0
D KP2A    :   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <e74dcf35373743e2bbf871ba34f3d1e2>:0
D KP2A    :   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in <e74dcf35373743e2bbf871ba34f3d1e2>:0

E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: keepass2android.keepass2android_nonet, PID: 32343
E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
E AndroidRuntime:   at keepass2android.SelectCurrentDbActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00036] in <9677545fef204e6b85d438458b767b5f>:0
E AndroidRuntime:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <e74dcf35373743e2bbf871ba34f3d1e2>:0
E AndroidRuntime:   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in <e74dcf35373743e2bbf871ba34f3d1e2>:0
E AndroidRuntime:        at crc64dd09b2a2e58bb27d.SelectCurrentDbActivity.n_onCreate(Native Method)
E AndroidRuntime:        at crc64dd09b2a2e58bb27d.SelectCurrentDbActivity.onCreate(SelectCurrentDbActivity.java:64)
E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8290)
E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8269)
E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1390)
E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7945)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```
Not sure yet why this happens.

**Comment by hyproman** [comment]
Unfortunately I can't reproduce this issue if I build my own version of the app (NoNet, Debug, Signed) via tag v1.09e-r4.
The hope was that the debug version of the app would contain line numbers to track down the source of the NullReferenceException.

@PhilippC this would appear to be another piece of evidence pointing to something very wrong with the release building process.

**Comment by FanXiangTM** [comment]
I also encountered the same problem on my phone

**Comment by FranLa** [comment]
I have the same problem. After upgrading of nonet from r3 to r4 Keepass2Android kept crashing, so I had to uninstall / install it again (fortunately I had a backup of the database).
My phone: Oneplus 5 (android 10)

**Comment by PhilippC** [comment]
please verify that this is no longer present in https://github.com/PhilippC/keepass2android/releases/tag/v1.09e-r5

**Comment by FranLa** [comment]
Nonet version r5 does no longer crash on startup. Tested on Android 10 and 12, both ok.  Thanks !
