### ISSUE TITLE
[BUG] Unable to Sync Database stored on Google Drive

### ISSUE THREAD

**Issue by Ray-B** [PhilippC/keepass2android#2467]
### Checks

- [X] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Whenever you make a change to the local copy of the DB (e.g. add an entry) and save, **the sync to the remote file on google drive fails**, and only the local copy is updated with the change. 

I've seen this bug crop up across multiple android devices (tablet and phone) **when a KBDX file is stored/referenced on google drive.**

**Other Considerations of Note:**

- This behaviour appears to present itself on as many versions of the app that have bee released in the last year and on both android 12 and 13. 
- When tested, both devices that experience this problem had the Google Drive app installed. 
- Both devices reference the same KDBX file
- Referencing a KBDX on google drive from a fresh app install, and then syncing appears to succeed, but subsequent  closing and re-opening of the app results in sync failure. 

Inspection of the log shows an exception on manual sync with a stack trace:

_Important Note_: I've obfuscated things, but its worth pointing out that this log entry did "leak" out my email address, google drive KBDX file name, and some other information. On a quick look, I am not sure if any of these are tokens or other important encoded values, so we should double check that too.

```
11/22/2023 11:12:08 PM:641 -- status message: Initializing...
11/22/2023 11:12:08 PM:642 -- status submessage: 
11/22/2023 11:12:08 PM:660 -- status message: Synchronizing cached database…
11/22/2023 11:12:08 PM:661 -- status submessage: Loading source file…
11/22/2023 11:12:08 PM:889 -- status submessage: Restoring source file…
11/22/2023 11:12:08 PM:890 -- gdrive://.U8-john.doe%[40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F](http://40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F) localVersionHash = 831C1552BD14FC35D1BDD57BDC37022B2E4FF0B070E593B7A61FEBA4F7F0D32611/22/2023 
11:12:09 PM:93 -- error getting file with for gdrive://.U8-john.doe%[40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F](http://40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F)
11/22/2023 11:12:09 PM:96 -- System.Exception: error getting file with for gdrive://.U8-john.doe%[40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F](http://40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F) ---> Java.IO.FileNotFoundException: error getting file with for gdrive://.U8-john.doe%[40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F](http://40gmail.com/.U8-kp-KP2A-1l0c8cfKdodmcmmdbSQellSAX-eIUuSu5/.U8-EXAMPLE-KEYPASS-DATABASE.kdbx-KP2A-10rny2SEiMSbLFMUpBQs9DTT6Iy0jwX5F)  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <6fb1725a77344b3e81b15cb69a959b5c>:0   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00036] in <6fb1725a77344b3e81b15cb69a959b5c>:0   at Keepass2android.Javafilestorage.GoogleDriveBaseFileStorage.UploadFile (System.String path, System.Byte[] data, System.Boolean writeTransactional) [0x00059] in <ef4fc53bed604ca380e5f749cd276ee6>:0   at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x0001c] in <483bd1ecfe364ef6a0dfb2f58ee9f0f5>:0    --- End of inner exception stack trace ---  at keepass2android.Io.JavaFileStorage+JavaFileStorageWriteTransaction.CommitWrite () [0x00036] in <483bd1ecfe364ef6a0dfb2f58ee9f0f5>:0   at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (System.IO.Stream cachedData, KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction, System.String hash) [0x00022] in <483bd1ecfe364ef6a0dfb2f58ee9f0f5>:0   at keepass2android.Io.CachingFileStorage.UpdateRemoteFile (KeePassLib.Serialization.IOConnectionInfo ioc, System.Boolean useFileTransaction) [0x00018] in <483bd1ecfe364ef6a0dfb2f58ee9f0f5>:0   at keepass2android.SynchronizeCachedDatabase.Run () [0x0009e] in <483bd1ecfe364ef6a0dfb2f58ee9f0f5>:0
```

**Rampant Speculation:**

- The URI path is URL encoded. Probably nothing, but I have see bugs before where an encoded URL gets saved/passed and causes unexpected behaviour
- "Error getting file with for gdrive" -> The path it logs looks funny. What is all the extra stuff appended? Is that a token-ized temporary path that is maybe no longer valid? 

Not sure how busy contributors are - I don't have a dev env for this project set up - but if maintainers want help debugging or a PR, I am happy to do so, but it may take me some time as we have a new baby. 

Thanks!

### Describe what you expected to happen:

When attempting to reconcile/synchronise a remotely stored google drive KBDX file, it should succeed.

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

13

**Comment by abend0c1** [comment]
I'm getting this issue too (just today). Same 1.09e-r7 version of the Android app. Also getting similar error using Keypass Password Safe Version 2.47 (64-bit) on Linux (Ubuntu 22-04.3LTS). On Linux I can list my gdrive keypass folder (and my other folders)  but I notice that it does not contain a *.kdbx file (I can't remember if it ever did, but it seems reasonable that it should). Instead it contains two files called <33 gibberish characters>.tmp and one called <33 gibberish characters>. My guess is that something has accidentally deleted the *.kdbx file and that these *.tmp files are the most recent backups (one is from today Jan 6, the other is a little older Jan 2). The one without the tmp extension is empty (0 bytes).

**Comment by Ray-B** [comment]
> I'm getting this issue too (just today). Same 1.09e-r7 version of the Android app. Also getting similar error using Keypass Password Safe Version 2.47 (64-bit) on Linux (Ubuntu 22-04.3LTS). On Linux I can list my gdrive keypass folder (and my other folders) but I notice that it does not contain a *.kdbx file. Instead it contains two files called <33 gibberish characters>.tmp and one called <33 gibberish characters>. My guess is that something has accidentally deleted the *.kdbx file and that these *.tmp files are the most recent backups (one is from today Jan 6, the other is a little older Jan 2). The one without the tmp extension is empty (0 bytes). Edit: If I rename one of the tmp files to my original kdbx file name then keypass can open the file OK, but when I save it the result is that the kdbx file disappears and a new tmp file contains the latest update. Seems to be some kind of GDrive API malfunction.


@abend0c1 

Might not be the same issue, however reading in the issues list, gdrive sync has been a pain for a while. 

Can you turn on logging in keypass2android,  then try to replicate the issue you're having and paste the logs here. 

This will make it easier to tell if your issue is related, or completely different and requires a separate issue to be created.

**Comment by PhilippC** [comment]
@Ray-B if you can collect a logcat, there might be a bit more information right before the logged error due to the `e.printStackTrace();`

    try {
				fl = getDriveService(getAccount()).files().get(getGDriveId()).execute();
			} catch (Exception e) {
				e.printStackTrace();
				throw new FileNotFoundException("error getting file with for "+ this.getFullPath());
			}

> The path it logs looks funny. What is all the extra stuff appended? Is that a token-ized temporary path that is maybe no longer valid?

Yes, I'm encoding GDrive-IDs in the path. The problem is that GDrive "looks like" a drive with a folder structure, but underneath, each file is referenced by an ID and the path is not even unique. I don't know a good way of dealing with this (considering cases like renamed files etc.)

Did you try to re-open the file?

**Comment by abend0c1** [comment]
I did the same today on two different Android devices and now it all works perfectly. Adding, deleting and syncing work as expected. App version is 1.09e-r7. Android version 11 on phone, and 13 on tablet. Sorry for hijacking this issue :/

**Comment by grzesuav** [comment]
hi, I have  same issue, my copy of db is not saved on the drive, with the same error (`error getting file with for gdrive://xxxx`)

**Comment by nascentt** [comment]
Same issue here.  I tried closing the database and opening it through Google drive again but now get earning Google are disabling it and to use system file picker. But that's local files. So if grove no longer an option?

**Comment by granite** [comment]
I also noticed I started to get this (error getting file with for gdrive://xxxx) error message and keepass2android  (version 1.14-r4) is not able to synchronize the `gdrive://email@gmail.com/filename.kdbx` file.  I confirmed the file is there on google drive, and I can update it using KeePassXC (version 2.7.10) on my macbook just fine.  Not sure what is going on.  It has worked fine for years.

**Comment by zediiiii** [comment]
UPDATE -- this method doesn't work so feel free to skip reading it. K2A notes that files are in sync, but it really doesn't do anything. I'm leaving this hot garbage idea here for context.

Related issue -- when sharing a keepass database through a shared file in Google drive, this is how I fix it for both accounts. Fixes your issue too. The ai I used did an okay job at outlining it, sorry if it's a little unclear

Solving KeePass2Android "Corrupted Headers" & Sync Overwrites on Shared Google Drive

1. The Problem: Why "Corrupted Header" happens
When you share a .kdbx file from one Google account to another account, you usually create a Shortcut in the personal "My Drive." Access and permissions and expiring oath logins make synchronizing unreliable.

In the case of KeePass2Android (KP2A) uses the Google Drive API to fetch files. This API sees the shortcut as a 0-byte metadata link, not the actual database. This results in KP2A trying to parse 0 bytes of data, fails to find the KeePass header, and throws the "Corrupted Header" or "Generic Error."

2. The Danger: Why standard Cloud Sync causes Data Loss

Most Android file pickers (including the "Open with" method) provide the app with a temporary stream. In this mode, KP2A acts like a simple text editor: it reads the file, you edit it, and it overwrites the whole file on save.

Conflict Scenario: If User A adds a password and User B adds a password before syncing, the person who saves last permanently erases the other person’s work.

3. The Solution: Separating "Transport" from "Merging"
To get 100% reliable multi-user merging without API errors, you must use a Two-File Sync Strategy. This involves using a dedicated sync app (like DriveSync/Autosync) to handle the cloud and KP2A to handle the database merge.

The Workflow:
Sync App (e.g., DriveSync): Handles the "Transport." It mirrors the shared .kdbx from Google Drive to a local folder on the phone. These apps are better than KP2A at following Google shortcuts and bypassing account API restrictions.
KeePass2Android: Handles the "Merge." You open the local file provided by the sync app.

The Merge Logic: KP2A maintains an internal Local Cache. When you save, it compares your "In-Memory" changes against the "Local File" (which DriveSync might have updated with your wife's changes).  

The Result: KP2A detects the external change and triggers its Merge Engine. It combines the entries based on their internal UUIDs and timestamps, then saves a unified version. DriveSync then pushes that unified version back to the cloud.

How to Set It Up (The TL;DR)

On the secondary phone: Use DriveSync (or Syncthing/Nextcloud) to create a "Two-Way" sync pair between the Shared Google Drive file and a local folder (e.g., /Documents/KeePass/).

In KeePass2Android: Open the file from the Local Folder (System File Picker > Documents).

Enable Change Detection: In KP2A, go to Settings > Database > File Handling and ensure "Check for changes" is enabled.  

Usage: When the app says "File modified externally. Synchronize?"—always click Synchronize. This is your data loss protection.

**Comment by ViperCode7** [comment]
I have (I think) a similar problem. K2A doesn't know how to retrieve the updated database from Google Drive's folder and always loads an older version. Messing with cache/temp copy shows errors. But if I delete the open entry and repick the same file from Drive's picker, K2A loads the latest file. The sync option reports all is in sync but it actually does nothing. I always have to open the database anew to get the updated contents.
PS: the suggestion above to use an intermediary sync app is exactly what K2A should be doing by itself with the Sync option. AND it doesn't work anyway. Syncing this way throws an error DocumentAccessRevokedException. I'm guessing whatever autosync puts locally isn't to K2A's liking.

**Comment by zediiiii** [comment]
Viper is right, the intermediary sync app doesn't actually work, and there are no indications that it didn't work until you realize you are loading an older version -- new database load is required to get the new data. My comment above is hot garbage and has been marked as such.

**Comment by Craigy-** [comment]
Not long ago, the database synchronization from Google Drive also stopped working for me...
I have v1.15-r3. Log:
24.09.2026 14:04:00:503 -- DatabaseSettingsActivity.OnPause 9 (Thread ID: 1) (Main Looper)
24.09.2026 14:04:00:514 -- Timeout start (Thread ID: 1) (Main Looper)
24.09.2026 14:04:00:546 -- GroupActivity.OnStart 8 (Thread ID: 1) (Main Looper)
24.09.2026 14:04:00:550 -- GroupActivity.OnResume 8 (Thread ID: 1) (Main Looper)
24.09.2026 14:04:00:551 --  DatabaseIsUnlocked=True 8 (Thread ID: 1) (Main Looper)
24.09.2026 14:04:00:552 -- Timeout cancel (Thread ID: 1) (Main Looper)
24.09.2026 14:04:01:141 -- DatabaseSettingsActivity.OnStop 9 (Thread ID: 1) (Main Looper)
24.09.2026 14:04:01:163 -- DatabaseSettingsActivity.OnDestroy True 9 (Thread ID: 1) (Main Looper)
24.09.2026 14:04:02:914 -- gdrive://grinder@tsu.com/private.kdbx localVersionHash = 799531C28E22098550CE6C002167CDB44438A0C32EE7EF16A89F1ED9B896D457 (Thread ID: 18)
24.09.2026 14:04:03:159 -- error getting file with for gdrive://.U8-grinder%40tsu.com/.U8-private.kdbx-KP2A-14Xxc9dk7HkOIpFHbwkS_Jis8398qVrBK (Thread ID: 18)
24.09.2026 14:04:03:163 -- System.Exception: error getting file with for gdrive://.U8-grinder%40tsu.com/.U8-private.kdbx-KP2A-14Xxc9dk7HkOIpFHbwkS_Jis8398qVrBK
 ---> Java.IO.FileNotFoundException: error getting file with for gdrive://.U8-grinder%40tsu.com/.U8-private.kdbx-KP2A-14Xxc9dk7HkOIpFHbwkS_Jis8398qVrBK
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Keepass2android.Javafilestorage.GoogleDriveBaseFileStorage.UploadFile(String path, Byte[] data, Boolean writeTransactional)
   at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: error getting file with for gdrive://.U8-grinder%40tsu.com/.U8-private.kdbx-KP2A-14Xxc9dk7HkOIpFHbwkS_Jis8398qVrBK
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage$GDrivePath.verify(GoogleDriveBaseFileStorage.java:187)
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage$GDrivePath.setPath(GoogleDriveBaseFileStorage.java:129)
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage$GDrivePath.<init>(GoogleDriveBaseFileStorage.java:123)
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage.uploadFile(GoogleDriveBaseFileStorage.java:389)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:1572)

  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: error getting file with for gdrive://.U8-grinder%40tsu.com/.U8-private.kdbx-KP2A-14Xxc9dk7HkOIpFHbwkS_Jis8398qVrBK
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage$GDrivePath.verify(GoogleDriveBaseFileStorage.java:187)
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage$GDrivePath.setPath(GoogleDriveBaseFileStorage.java:129)
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage$GDrivePath.<init>(GoogleDriveBaseFileStorage.java:123)
	at keepass2android.javafilestorage.GoogleDriveBaseFileStorage.uploadFile(GoogleDriveBaseFileStorage.java:389)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:1572)

   Exception_EndOfInnerExceptionStack
   at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
   at keepass2android.Io.CachingFileStorage.UpdateRemoteFile(Stream cachedData, IOConnectionInfo ioc, Boolean useFileTransaction, String hash)
   at keepass2android.Io.CachingFileStorage.UpdateRemoteFile(IOConnectionInfo ioc, Boolean useFileTransaction)
   at keepass2android.SynchronizeCachedDatabase.Run() (Thread ID: 18)
