### ISSUE TITLE
App crashes when attempting fingerprint unlock after stored fingerprints changed

### ISSUE THREAD

**Issue by phuler** [PhilippC/keepass2android#250]
Deleting all saved fingerprints on my device and replacing them causes the app to crash immediately after touching the fingerprint reader when the fingerprint unlock option is activated on the unlock database screen. 

Unlocking the database using the password and toggling fingerprint unlocking off/on fixes the issue and fingerprint unlocking works normally again.

**Comment by jonasgustavsson** [comment]
Thank you, you solved my problem!
I also had this problem after I had to do a reset of the phone (thus causing me to reconfigure my fingerprint). I assume the settings for fingerprint unlock was stored in the automatic Google Drive backup.

**Comment by HairyDude** [comment]
This happens on a new device since obviously your fingerprints are new. "Turning it off and on again" per @phuler does work. Here's the exception it raises before that happens:

```
21/08/2018 10:57:37:724 -- Error initializing Fingerprint Unlock: Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <23a0ad77af1846159033a7f689818ea9>:0 
  at keepass2android.QuickUnlock.InitFingerprintUnlock () [0x00155] in <23a0ad77af1846159033a7f689818ea9>:0 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
	at md5f0702f468598c68ce18586502249fb40.QuickUnlock.n_onResume(Native Method)
	at md5f0702f468598c68ce18586502249fb40.QuickUnlock.onResume(QuickUnlock.java:59)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
	at android.app.Activity.performResume(Activity.java:7144)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
	at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:436)
	at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:273)
	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2664)
	at javax.crypto.Cipher.tryCombinations(Cipher.java:2575)
	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2480)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:567)
	at javax.crypto.Cipher.init(Cipher.java:975)
	at javax.crypto.Cipher.init(Cipher.java:910)
	... 13 more
```
