### ISSUE TITLE
Crash when using Find a Password in Chrome

### ISSUE THREAD

**Issue by auanasgheps** [PhilippC/keepass2android#300]
**Device**: Xiaomi Mi5
**Android version** : Android 8.1 (LineageOS 15.1)
**Keepass2Android version**: 1.05-pre1

In Chrome, when using the feature _Share > Find a Password KeePass2Android_ I get a crash after unlocking the database.

I am unlocking with fingerprint, but using the password does not make a difference.
Please let me know if you need more information

Steps to replicate

1. Browse a website in Chrome
2. Menu > Share > Find a Password (KeePass2Android feature)
3. Unlock the database
4. Crash

Version 1.04b works perfectly, I have reverted to that one for now.

Verbose log below:

```
03-14 11:04:40.865 V/FingerprintService(911): startAuthentication(keepass2android.keepass2android)
03-14 11:04:40.865 V/FingerprintService(911): starting client AuthenticationClient(keepass2android.keepass2android), initiatedByClient = true)
03-14 11:04:40.866 I/fpc_fingerprint_hal(681): fpc_worker_set_state_locked worker_state_t = 0
03-14 11:04:40.867 E/fpc_tac (681): fpc_ree_device_wait_irq (fingerprint) pfd[1].revents 1
03-14 11:04:40.874 I/fpc_fingerprint_hal(681): do_navigation end -
03-14 11:04:40.874 I/fpc_fingerprint_hal(681): workerFunction STATE_IDLE
03-14 11:04:40.874 I/fpc_fingerprint_hal(681): fpc_worker_set_state_locked worker_state_t = 2
03-14 11:04:40.874 I/fpc_fingerprint_hal(681): workerFunction STATE_AUTHENTICATE, status:0, nav:1
03-14 11:04:40.874 W/FingerprintService(911): client keepass2android.keepass2android is authenticating...
03-14 11:04:40.885 I/fpc_fingerprint_hal(681): fpc_wait_finger_up FPC_LIB_FINGER_LOST
03-14 11:04:40.885 I/fpc_fingerprint_hal(681): do_identify start -
03-14 11:04:40.886 I/GoogleInputMethod(1587): onStartInputView() : Dummy InputConnection bound
03-14 11:04:40.898 D/KP2A    (23825): GlobalLayout
03-14 11:04:40.899 D/KP2A    (23825): ActualHeight=1855
03-14 11:04:40.899 D/KP2A    (23825): ProposedHeight=1855
03-14 11:04:40.916 W/Environment(1587): com.bitstrips.imoji is not installed
03-14 11:04:40.916 W/VoiceImeTranscriptor(1587): UIME feature enabled: true
03-14 11:04:40.917 I/VoiceImeExtension(1587): Voice Extension onStartInputView() Mic status = [MicIconAvailable]
03-14 11:04:40.917 I/FederatedC2QExtension(1587): Already registered manifest.
03-14 11:04:40.917 I/FederatedC2QExtension(1587): model for it/ranking_20180108 is not yet available
03-14 11:04:40.917 I/FederatedC2QExtension(1587): requesting model 'federated_conv2query_triggering_it_ranking_20180108'
03-14 11:04:40.917 I/FederatedC2QExtension(1587): no valid model for inferencing found, switching to baseline.
03-14 11:04:40.920 I/Superpacks(1587): Syncing federatedc2q
03-14 11:04:40.923 V/View    (23825): dispatchProvideAutofillStructure(): not laid out, ignoring 4 children of 1073741856
03-14 11:04:40.924 V/View    (23825): dispatchProvideAutofillStructure(): not laid out, ignoring 2 children of 1073741857
03-14 11:04:40.924 V/View    (23825): dispatchProvideAutofillStructure(): not laid out, ignoring 2 children of 1073741858
03-14 11:04:40.926 W/Binder  (911): Outgoing transactions from this process must be FLAG_ONEWAY
03-14 11:04:40.926 W/Binder  (911): java.lang.Throwable
03-14 11:04:40.926 W/Binder  (911): 	at android.os.BinderProxy.transact(Binder.java:752)
03-14 11:04:40.926 W/Binder  (911): 	at android.app.assist.AssistStructure$ParcelTransferReader.fetchData(AssistStructure.java:407)
03-14 11:04:40.926 W/Binder  (911): 	at android.app.assist.AssistStructure$ParcelTransferReader.go(AssistStructure.java:343)
03-14 11:04:40.926 W/Binder  (911): 	at android.app.assist.AssistStructure.ensureData(AssistStructure.java:2100)
03-14 11:04:40.926 W/Binder  (911): 	at com.android.server.autofill.Session$1.send(Session.java:227)
03-14 11:04:40.926 W/Binder  (911): 	at com.android.server.am.ActivityManagerService.reportAssistContextExtras(ActivityManagerService.java:13337)
03-14 11:04:40.926 W/Binder  (911): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2472)
03-14 11:04:40.926 W/Binder  (911): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2984)
03-14 11:04:40.926 W/Binder  (911): 	at android.os.Binder.execTransact(Binder.java:697)
03-14 11:04:40.933 I/AssistStructure(23825): Flattened final assist data: 10064 bytes, containing 1 windows, 43 views
03-14 11:04:40.936 I/Superpacks(1587): Requesting packs for federatedc2q with slices: []
03-14 11:04:40.939 I/Superpacks(1587): Sync for 'federatedc2q' succeeded, result: {old=[], new=[], last batch=true}
03-14 11:04:40.943 I/Superpacks(1587): Opening packs for federatedc2q
03-14 11:04:40.945 I/FederatedC2QExtension(1587): Got no packs for locale: it
03-14 11:04:40.958 I/AssistStructure(911): Flattened final assist data: 9768 bytes, containing 1 windows, 43 views
03-14 11:04:40.981 D/KP2A    (23825): FileSelect.OnStop
03-14 11:04:41.007 W/VoiceImeTranscriptor(1587): UIME feature enabled: true
03-14 11:04:41.017 I/EmojiDataExtension(1587): onActivate() : Locale = it
03-14 11:04:41.017 I/EmojiSuperpacksFeature(1587): Emoji superpacks enabled
03-14 11:04:41.017 I/GifEntryExtension(1587): onActivate()
03-14 11:04:41.017 I/DevFeatureConfig(1587): Gif candidate disabled by Phenotype
03-14 11:04:41.017 I/PrimesMetrics(1587): Ignore memory metric of com.google.android.apps.inputmethod.libs.search.gif.GifEntryPointCandidateExtension.
03-14 11:04:41.068 I/zygote  (23825): Explicit concurrent copying GC freed 43088(2MB) AllocSpace objects, 3(552KB) LOS objects, 49% free, 2MB/4MB, paused 222us total 52.796ms
03-14 11:04:41.069 D/KP2A    (23825): FileSelect.OnDestroyTrue
03-14 11:04:41.085 I/GoogleInputMethod(1587): onFinishInputView() : Dummy InputConnection bound
03-14 11:04:41.085 I/PhenotypeExpConfig(1587): refreshConfiguration() : Force = false : UpdateAvailable = false : Age = 62 minutes : MaxAge = 720 minutes
03-14 11:04:41.086 I/GoogleInputMethod(1587): onFinishInput() : Dummy InputConnection bound
03-14 11:04:41.096 W/Environment(1587): com.bitstrips.imoji is not installed
03-14 11:04:41.096 W/VoiceImeTranscriptor(1587): UIME feature enabled: true
03-14 11:04:41.096 I/VoiceImeExtension(1587): Voice Extension onStartInputView() Mic status = [MicIconHidden-PasswordOrNumberOrDateInputType, ]
03-14 11:04:41.096 I/FederatedC2QExtension(1587): Already registered manifest.
03-14 11:04:41.096 I/FederatedC2QExtension(1587): model for it/ranking_20180108 is not yet available
03-14 11:04:41.096 I/FederatedC2QExtension(1587): requesting model 'federated_conv2query_triggering_it_ranking_20180108'
03-14 11:04:41.096 I/FederatedC2QExtension(1587): no valid model for inferencing found, switching to baseline.
03-14 11:04:41.098 I/Superpacks(1587): Syncing federatedc2q
03-14 11:04:41.100 I/EmojiDataExtension(1587): onActivate() : Locale = it
03-14 11:04:41.100 I/EmojiSuperpacksFeature(1587): Emoji superpacks enabled
03-14 11:04:41.100 I/GifEntryExtension(1587): onActivate()
03-14 11:04:41.100 I/DevFeatureConfig(1587): Gif candidate disabled by Phenotype
03-14 11:04:41.100 I/Superpacks(1587): Requesting packs for federatedc2q with slices: []
03-14 11:04:41.102 I/Superpacks(1587): Sync for 'federatedc2q' succeeded, result: {old=[], new=[], last batch=true}
03-14 11:04:41.110 I/Superpacks(1587): Opening packs for federatedc2q
03-14 11:04:41.112 I/FederatedC2QExtension(1587): Got no packs for locale: it
03-14 11:04:41.113 I/PrimesMetrics(1587): Ignore memory metric of com.google.android.apps.inputmethod.libs.search.gif.GifEntryPointCandidateExtension.
03-14 11:04:41.145 I/PhenotypeExpConfig(1587): refreshConfiguration() : Force = false : UpdateAvailable = false : Age = 62 minutes : MaxAge = 720 minutes
03-14 11:04:41.153 I/cr_BindingManager(21187): onTrimMemory: level=20, size=1
03-14 11:04:41.160 D/KP2A    (23825): GlobalLayout
03-14 11:04:41.160 D/KP2A    (23825): ActualHeight=1855
03-14 11:04:41.160 D/KP2A    (23825): ProposedHeight=1093
03-14 11:04:41.163 W/StatusBar(1600): removeNotification for unknown key: -1|android|8|null|1000
03-14 11:04:41.204 D/KP2A    (23825): GlobalLayout
03-14 11:04:41.205 D/KP2A    (23825): ActualHeight=1093
03-14 11:04:41.205 D/KP2A    (23825): ProposedHeight=1855
03-14 11:04:41.228 D/KP2A    (23825): CFS: Files in Sync
03-14 11:04:41.240 D/KP2A    (23825): Pre-loading database file completed
03-14 11:04:43.176 I/fpc_fingerprint_hal(681): wait_wake_up (get_irq)
03-14 11:04:43.194 I/fpc_fingerprint_hal(681): capture_single_image when fpc_wait_finger_down s_domekey_down = 0
03-14 11:04:43.307 D/android.hardware.biometrics.fingerprint@2.1-service(681): onAcquired(0)
03-14 11:04:43.314 E/ANDR-PERF-RESOURCEQS(532): Failed to apply optimization [4, 0]
03-14 11:04:43.316 E/ANDR-PERF-RESOURCEQS(532): Failed to apply optimization [2, 0]
03-14 11:04:43.352 I/fpc_fingerprint_hal(681): do_identify fpc_tac_identify result 2 306 0 179614
03-14 11:04:43.353 I/fpc_fingerprint_hal(681): log_result2 end
03-14 11:04:43.357 I/fpc_fingerprint_hal(681): do_identify before while s_domekey_down = 0 when r=1or2
03-14 11:04:43.357 D/android.hardware.biometrics.fingerprint@2.1-service(681): onAuthenticated(fid=1488702988, gid=0)
03-14 11:04:43.360 I/fpc_tac (681): fpc_tac_store_template_db storing db at /data/system/users/0/fpdata/user.db.bak
03-14 11:04:43.361 D/keystore(608): AddAuthenticationToken: timestamp = 89895742 (4518054928215703552), time_received = 33671
03-14 11:04:43.361 V/FingerprintService(911): onAuthenticated(owner=keepass2android.keepass2android, id=1488702988, gp=0)
03-14 11:04:43.366 V/FingerprintService(911): Done with client: keepass2android.keepass2android
03-14 11:04:43.367 D/KP2A    (23825): FP: OnAuthenticationSucceeded 
03-14 11:04:43.368 D/KP2A    (23825): FP: StopListening 
03-14 11:04:43.380 D/KP2A    (23825): FP: Decrypting 
03-14 11:04:43.417 I/fpc_tac (681): fpc_tac_store_template_db storing db at /data/system/users/0/fpdata/user2.db.bak
03-14 11:04:43.482 I/fpc_fingerprint_hal(681): fpc_wait_finger_up(fpc_tac_check_finger_lost) status: 2
03-14 11:04:43.572 I/chatty  (681): uid=1000(system) android.hardwar identical 3 lines
03-14 11:04:43.606 I/fpc_fingerprint_hal(681): fpc_wait_finger_up(fpc_tac_check_finger_lost) status: 2
03-14 11:04:43.733 I/fpc_fingerprint_hal(681): fpc_wait_finger_up FPC_LIB_FINGER_LOST
03-14 11:04:43.733 I/fpc_fingerprint_hal(681): do_identify end -
03-14 11:04:43.743 I/fpc_fingerprint_hal(681): fpc_wait_finger_up FPC_LIB_FINGER_LOST
03-14 11:04:43.743 I/fpc_fingerprint_hal(681): workerFunction STATE_NONE (Navigation), status:0
03-14 11:04:43.743 I/fpc_fingerprint_hal(681): do_navigation start -
03-14 11:04:43.993 D/KP2A    (23825): PasswordActivity.OnActivityResult 874348/1000
03-14 11:04:43.995 D/KP2A    (23825): No AppTask in OnActivityResult
03-14 11:04:44.010 W/zygote  (23825): JNI RegisterNativeMethods: attempt to register 0 native methods for md5090d07a8de38bd33d150240d8fd8007d.SimpleLoadingDialog
03-14 11:04:44.157 W/zygote  (23825): JNI RegisterNativeMethods: attempt to register 0 native methods for md5090d07a8de38bd33d150240d8fd8007d.SimpleLoadingDialog_BackgroundResult
03-14 11:04:44.779 W/WindowManager(911): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@efaa5e4
03-14 11:04:45.054 I/zygote  (23825): Explicit concurrent copying GC freed 6755(380KB) AllocSpace objects, 79(1900KB) LOS objects, 50% free, 2MB/5MB, paused 174us total 35.973ms
03-14 11:04:45.408 I/zygote  (23825): Explicit concurrent copying GC freed 3272(149KB) AllocSpace objects, 85(1700KB) LOS objects, 50% free, 2MB/5MB, paused 153us total 33.325ms
03-14 11:04:45.770 I/zygote  (23825): Explicit concurrent copying GC freed 1506(56KB) AllocSpace objects, 86(1720KB) LOS objects, 50% free, 2MB/5MB, paused 152us total 33.545ms
03-14 11:04:46.074 W/X       (21187): [TiclService] Ticl being stopped: Client: <ApplicationClientIdP: client_type=1018 client_name=cdf77692-a370-44a4-af49-b6eb93aa205b>, \n\006\n\004\010\003\020\001\022\022\ta\214\301\223,r3\266\021oD\2446pQ\313\212\032\007\010\231\022\020\003\030\001, <RunState: 2>
03-14 11:04:46.279 I/zygote  (14758): Do partial code cache collection, code=19KB, data=29KB
03-14 11:04:46.280 I/zygote  (14758): After code cache collection, code=19KB, data=29KB
03-14 11:04:46.280 I/zygote  (14758): Increasing code cache capacity to 128KB
03-14 11:04:46.296 E/WakeLock(2219): release without a matched acquire!
03-14 11:04:46.349 D/KP2A    (23825): ReadXmlStreamed: 1931ms
03-14 11:04:46.424 I/zygote  (23825): Explicit concurrent copying GC freed 80(31KB) AllocSpace objects, 5(100KB) LOS objects, 50% free, 2MB/5MB, paused 152us total 32.588ms
03-14 11:04:46.472 D/KP2A    (23825): File flags: 455
03-14 11:04:46.500 I/WifiService(911): getConnectionInfo uid=10034
03-14 11:04:46.510 D/KP2A    (23825): Starting/Updating OngoingNotificationsService. Database Unlocked
03-14 11:04:46.541 I/WifiService(911): getConnectionInfo uid=10034
03-14 11:04:46.551 D/KP2A    (23825): LoadDB OK
03-14 11:04:46.616 W/Notification(23825): Use of stream types is deprecated for operations other than volume control
03-14 11:04:46.616 W/Notification(23825): See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-14 11:04:46.625 E/NotificationService(911): Suppressing notification from package by user request.
03-14 11:04:46.747 I/zygote  (23825): Explicit concurrent copying GC freed 1576(244KB) AllocSpace objects, 1(20KB) LOS objects, 50% free, 2MB/5MB, paused 160us total 33.370ms
03-14 11:04:46.761 I/ActivityManager(911): START u0 {cmp=keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.ShareUrlResults (has extras)} from uid 10165
03-14 11:04:46.795 D/KP2A    (23825): PasswordActivity.OnPause
03-14 11:04:46.799 D/KP2A    (23825): Timeout start
03-14 11:04:46.838 D/KP2A    (23825): ShareUrlResults.OnCreate
03-14 11:04:46.839 D/KP2A    (23825): ShareUrlResults:apptask=
03-14 11:04:46.843 D/KP2A    (23825): Creating GBA
03-14 11:04:46.844 D/KP2A    (23825): Loaded task keepass2android.SearchUrlTask
03-14 11:04:46.902 I/MonoDroid(23825): UNHANDLED EXCEPTION:
03-14 11:04:46.930 I/MonoDroid(23825): System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.930 I/MonoDroid(23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.930 I/MonoDroid(23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.935 D/KP2A    (23825): System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.935 D/KP2A    (23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.935 D/KP2A    (23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.944 W/zygote  (23825): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-14 11:04:46.948 D/AndroidRuntime(23825): Shutting down VM
03-14 11:04:46.952 E/AndroidRuntime(23825): FATAL EXCEPTION: main
03-14 11:04:46.952 E/AndroidRuntime(23825): Process: keepass2android.keepass2android, PID: 23825
03-14 11:04:46.952 E/AndroidRuntime(23825): android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
03-14 11:04:46.952 E/AndroidRuntime(23825):   at keepass2android.GroupBaseActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00442] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at keepass2android.ShareUrlResults.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in <aec94da106af4c0ca96559d825ea9da6>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <ccdda1ca96684526b4a1c01b76e98fd0>:0 
03-14 11:04:46.952 E/AndroidRuntime(23825):   at (wrapper dynamic-method) System.Object:f71f5726-2419-4fc1-a86e-6bbc29f8b994 (intptr,intptr,intptr)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.n_onCreate(Native Method)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at md5f0702f468598c68ce18586502249fb40.ShareUrlResults.onCreate(ShareUrlResults.java:31)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Activity.performCreate(Activity.java:6999)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Activity.performCreate(Activity.java:6990)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.os.Looper.loop(Looper.java:164)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at java.lang.reflect.Method.invoke(Native Method)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-14 11:04:46.952 E/AndroidRuntime(23825): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-14 11:04:46.959 W/ActivityManager(911):   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.ShareUrlResults
03-14 11:04:46.963 W/ActivityManager(911):   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.PasswordActivity
03-14 11:04:46.968 I/ActivityManager(911): Showing crash dialog for package keepass2android.keepass2android u0
03-14 11:04:47.008 I/OpenGLRenderer(911): Initialized EGL, version 1.4
03-14 11:04:47.009 D/OpenGLRenderer(911): Swap behavior 2
03-14 11:04:47.462 W/ActivityManager(911): Activity pause timeout for ActivityRecord{116215e u0 keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.ShareUrlResults t1064 f}

```

**Comment by Karreg** [comment]
Duplicate #289

**Comment by auanasgheps** [comment]
@Karreg your case talks about Oreo autofill, which is not being used in this scenario.

**Comment by Karreg** [comment]
Not only autofill. Any search, including URL sharing...

**Comment by Karreg** [comment]
Meanwhile, can you try the other use cases ? Searching from KP2A keyboard, and using Autofill ?

**Comment by Karreg** [comment]
I have the same log for all 3 issues, so definitely the same bug. :)

**Comment by auanasgheps** [comment]
@Karreg good to know you have the same error as I do. I didn't look further in your issue because it seemed unrelated to my case. 
I have reverted to 1.04b so I can't test anymore, but I remember I had a couple of crashes when trying to use the KP2A Keyboard, but can't exactly remember when they happened.

**Comment by Karreg** [comment]
Close #300

**Comment by auanasgheps** [comment]
Closing, duplicate of #289
