### ISSUE TITLE
Crash on fingerprint activation

### ISSUE THREAD

**Issue by federicoiosue** [PhilippC/keepass2android#362]
**Device:** One plus 5T

**Android:** 8.1

**App version:** 1.0.5-pre2

I'm actually not sure if the problem persists even without Xposed. I always used it and everything used to work flawlessly but I've upgraded my firmware to Android 8.1 just some days ago so I'll try to debug further.

```
FATAL EXCEPTION: main
Process: keepass2android.keepass2android, PID: 5213
java.security.ProviderException: Keystore operation failed
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:321)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)
	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
	at android.widget.CompoundButton.toggle(CompoundButton.java:127)
	at android.widget.RadioButton.toggle(RadioButton.java:76)
	at android.widget.CompoundButton.performClick(CompoundButton.java:132)
	at android.view.View$PerformClick.run(View.java:24921)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: android.security.KeyStoreException: User authentication required
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:672)
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:322)
	... 16 more   
```

**Comment by mtraxiot** [comment]
Also crashing for me on android 7.0 tablet

**Comment by federicoiosue** [comment]
It  depends from xposed

**Comment by mtraxiot** [comment]
I don't have xposed on my phone and it works

**Comment by federicoiosue** [comment]
Could you need more informations about this @PhilippC ?

**Comment by icyerasor** [comment]
Had the same issue (with another app though) - try going into the "nexus imprint" / "fingerprint" settings of android OS and changing some stuff there - i.e. display the name of the imprints, change it, etc. For me no re-setup of the imprints was necessary.
Afterwards, back in the app everything worked again..

**Comment by divid3byzero** [comment]
This is (still) an issue on OnePlus 7 Pro running Android 10. I'm running version 1.07b-r0 of the app on the afore mentioned device. 

@PhilippC can you look into this?
