### ISSUE TITLE
QuickUnlock - Fingerprint Reader Issue

### ISSUE THREAD

**Issue by chaotenbacher** [PhilippC/keepass2android#418]
Dear Philipp & all,

after I resetted my HTC U11 (Android 8.0.0), I am not able to use the quick unlock function via fingerprint reader anymore (quick unlock via keyboard is working fine). To the right of the field where I can type my quick unlock passphrase, there's a red exclamation mark, that I leads to below error message. I aleady de- and then re-activated the screen lock and thus the fingerprint function - no effect at all. The fingerprint function works fine with other apps.

The log file is attached to this request. 

Thank you in advance for your support!

Errror message:
"Entsperren mit Fingerabdruck:

Error initializing Fingerprint Unlock: Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <c1cac41f160941d992e0cf5aa198e4c7>:0 
  at keepass2android.QuickUnlock.InitFingerprintUnlock () [0x00155] in <c1cac41f160941d992e0cf5aa198e4c7>:0 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
at md5f0702f468598c68ce18586502249fb40.QuickUnlock.n_onRequestPermissionsResult(Native Method)
at md5f0702f468598c68ce18586502249fb40.QuickUnlock.onRequestPermissionsResult(QuickUnlock.java:51)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7399)
at android.app.Activity.dispatchActivityResult(Activity.java:7250)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4583)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4637)
at android.app.ActivityThread.-wrap19(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:180)
at android.app.ActivityThread.main(ActivityThread.java:6950)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:436)
at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:273)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2659)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2570)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2475)
at javax.crypto.Cipher.chooseProvider(Cipher.java:566)
at javax.crypto.Cipher.init(Cipher.java:973)
at javax.crypto.Cipher.init(Cipher.java:908)
... 14 more"

[kepass2android logfile.txt](https://github.com/PhilippC/keepass2android/files/2110707/kepass2android.logfile.txt)

**Comment by chaotenbacher** [comment]
Thank you Philipp, it works now. Perfect support, will gladly buy you
another beer ;-)


PhilippC <notifications@github.com> schrieb am Mo., 18. Juni 2018, 13:27:

**Comment by jaimehrubiks** [comment]
As I commented on other post, my phone crashes on android 8.1 if I attempt to enable fingerprint. How can I extract a crash log in case it is useful?

**Comment by chaotenbacher** [comment]
I'm using the German version so translation might not be 100% accurate, I
hope you can figure it out anyway:

Menu (3 dots upper RH corner)
Settings
Application
Log File (for debugging)


Jaime Hidalgo García <notifications@github.com> schrieb am Mo., 18. Juni
2018, 16:48:

**Comment by jaimehrubiks** [comment]
I leave here my log report in case it helps somehow.

https://pastebin.com/r6AMBSmF

**Comment by PhilippC** [comment]
@jaimehrubiks what kind of phone is this? Is it a Redmi?

**Comment by jaimehrubiks** [comment]
@PhilippC Yes, it is a Redmi 4 Prime/Pro. Android 8.1. I know these phones are somehow weirdos haha but fingerprint is working for other apps so there must be something in there that is causing the crash.

**Comment by m1st0** [comment]
Also occurring on my Note 9, Android 9.  Similar log when using fingerprint unlock but slightly different stack trace below (I cannot solve this by disabling and enabling fingerprint unlock as the app closes as soon as I activate full fingerprint unlock again):

> Fingerprint unlock
> Error initializing Fingerprint Unlock:
> Java.lang.RuntimeException: Exception of type
> Java.lang.RuntimeException was thrown.
> at keepass2android.Fingerprint encryption.Init
> ( [0x000a3] in
> <42483a0e42cb482da6be36caa63cd922>:0
> 
> at
> keepass2android.Quick Unlock.Init Fingerprint Unlock,
> O [Ox00176] in
> <42483a0e42cb482da6be36caa63cd922>:0
> 
> End of managed Java.lang.RuntimeException
> stack trace-
> java.lang.RuntimeException: Failed to init Cipher
> 
> at
> md5f0702f468598c68ce18586502249fb40.QuickUnlo
> Method)
> 
> at
> 
> md5f0702f468598c68ce18586502249fb40.QuickUnlo
> ck.onResume(QuickUnlock.java:59)
> at
> android.app.Instrumentation.callActivityOnResume(In
> strumentation.java:1412)
> at android.app.Activity.performResume(Activity.java:
> 7557)
> 
> at
> 
> android.app.ActivityThread.performResumeActivity (A
> ctivityThread.java:3979)
> 
> at
> 
> android.app.ActivityThread.handleResume Activity (Act
> ivityThread.java:4019)
> 
> at
> android.app.servertransaction.ResumeActivityltem.execute(ResumeActivityltem.java:51)
> ecute(ResumeActivityltem.java:51)
> 
> at
> android.app.servertransaction.TransactionExecutor.execute
> ecuteLifecycleState(TransactionExecutor.java:145)
> 
> at
> 
> android.app.servertransaction. TransactionExecutor.ex
> ecute(TransactionExecutor.java:70)
> 
> at
> 
> android.app.ActivityThread$H.handleMessage(Activity
> Thread.java:1926)
> at android.os.Handler.dispatchMessage(Handler.java:
> 106)
> at android.os.Looper.loop(Looperiava:214),
