### ISSUE TITLE
Unable to open database with sftp

### ISSUE THREAD

**Issue by hannesrellum** [PhilippC/keepass2android#499]
I try to open my database with sftp on raspberry pi (Raspbian GNU/Linux 9 stretch with pihole), but it always shows an error: "Es ist ein Fehler aufgetreten: No such file"

Log-Output is:

12.08.2018 15:44:28:193 -- PasswordActivity.OnActivityResult 874348/1000
12.08.2018 15:44:28:200 -- No AppTask in OnActivityResult
12.08.2018 15:44:28:208 -- PasswordActivity.OnActivityResult 874348/1004
12.08.2018 15:44:28:209 -- No AppTask in OnActivityResult
12.08.2018 15:44:28:218 -- CFS: OpenWhenNoLocalChanges
12.08.2018 15:44:28:219 -- CFS: hashing cached version
12.08.2018 15:44:28:235 -- CFS: Files in Sync
12.08.2018 15:44:28:327 -- System.IO.FileNotFoundException: No such file ---> Java.IO.FileNotFoundException: No such file
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <92ccbda37a8f409b84c0d709658b6bb1>:0
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <50f136c22854451fb0164819995099ad>:0
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <fb151c603a6b487c8c4acc18b247387d>:0
  at Keepass2android.Javafilestorage.SftpStorage.OpenFileForRead (System.String p0) [0x00062] in <864263ecf9c74d2cbcc01d384e32b4fd>:0
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <8b8564fc621f46ffaff800ca19bc9b90>:0
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: No such file
at keepass2android.javafilestorage.SftpStorage.convertException(SftpStorage.java:207)
at keepass2android.javafilestorage.SftpStorage.openFileForRead(SftpStorage.java:86)

  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <8b8564fc621f46ffaff800ca19bc9b90>:0
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <8b8564fc621f46ffaff800ca19bc9b90>:0
  at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <8b8564fc621f46ffaff800ca19bc9b90>:0
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <8b8564fc621f46ffaff800ca19bc9b90>:0
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <8b8564fc621f46ffaff800ca19bc9b90>:0
  at keepass2android.PasswordActivity.PreloadDbFile () [0x00037] in <23a0ad77af1846159033a7f689818ea9>:0
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <92ccbda37a8f409b84c0d709658b6bb1>:0
  at System.Threading.Tasks.Task.Execute () [0x00010] in <92ccbda37a8f409b84c0d709658b6bb1>:0
12.08.2018 15:44:28:547 -- OnFinish message: Ein Fehler ist aufgetreten: No such file
12.08.2018 15:44:32:795 -- PasswordActivity.OnPause
12.08.2018 15:44:32:818 -- AppSettingsActivity.OnCreate
12.08.2018 15:44:32:818 -- AppSettingsActivity:apptask=
12.08.2018 15:44:32:893 -- AppSettingsActivity.OnStart
12.08.2018 15:44:32:895 -- AppSettingsActivity.OnResume
12.08.2018 15:44:32:896 --  DatabaseIsUnlocked=False
12.08.2018 15:44:33:338 -- PasswordActivity.OnStop

What am I doing wrong? I Cleared cache and data on my Phone, deinstalled, re-installed, rebootet, but nothing helped...

**Comment by PhilippC** [comment]
Can you post a screenshot of the dialog where you enter the SFTP data like server etc.?

**Comment by hannesrellum** [comment]
I hope that is whar you were looking for:

![screenshot_20180815-071908](https://user-images.githubusercontent.com/3299379/44132839-588dd116-a05c-11e8-9c0f-2d78f928f4de.png)

**Comment by PhilippC** [comment]
please try without the filename, only the directory ("/"). You should then see a file browser where you can select the file.

**Comment by hannesrellum** [comment]
that solved my problem - many many thanks.
I now have access via sftp to my server, just perfect!

(the "optional" for "Startverzeichnis" is a bit misleading, since without "/" I get another error)

**Comment by 0tt3** [comment]
I have the very same problem. Instead, leaving out the file name causes another error: "Cannot connect to file service. No such file" (translated from German: "Kann nicht zum Datei-Dienst verbinden. No such file"
It doesn't matter if I left out the whole path or just the file name.
When using the whole path + file name I get to enter my master password, but then I get the message "An error occurred: No such file" ("Ein ist Fehler aufgetreten: No such file"). Even when leaving the master password blank.

I'm using Paranoid Android 7.3.1-RELEASE (Android 7.1.2); K2A 1.07-r1. I use the same host, port and credentials on Windows/Keepass 2. They work just fine. I suspect it's either my NAS or K2A.
I switched to SFTP because ftps stopped working with my Fritzbox 7490 (probably because of #825).

Any suggestions?
