### ISSUE TITLE
Endless loop with file access error

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#550]
9/8/2018 7:39:28 AM:291 -- PasswordActivity.OnPause
9/8/2018 7:39:28 AM:325 -- FileSelect.OnCreate
9/8/2018 7:39:28 AM:326 -- FileSelect:apptask=NullTask
9/8/2018 7:39:28 AM:327 -- Loaded task keepass2android.NullTask
9/8/2018 7:39:28 AM:352 -- FileSelect.OnStart
9/8/2018 7:39:28 AM:353 -- FileSelect.OnResume
9/8/2018 7:39:28 AM:402 -- Java.Lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AownCloud_Sync%2FRWPasswords-OC_YubikeyCR.kdbx from pid=17937, uid=10330 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e517f258e41f48d1b26c62fb5ffd1b94>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <ef8a592d5fc54c2fbeba6639a28e5da7>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <ef8a592d5fc54c2fbeba6639a28e5da7>:0 
at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <23e87dd929b5410bb246b44faae222fa>:0
  at keepass2android.Io.AndroidContentStorage.TryGetDisplayName (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& displayName) [0x00017] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AownCloud_Sync%2FRWPasswords-OC_YubikeyCR.kdbx from pid=17937, uid=10330 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
 at android.os.Parcel.readException(Parcel.java:1959)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
 at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
 at android.content.ContentResolver.query(ContentResolver.java:760)
 at android.content.ContentResolver.query(ContentResolver.java:710)
 at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.n_bindView(Native Method)
 at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.bindView(FileSelectActivity_MyCursorAdapter.java:46)
 at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
 at android.widget.AbsListView.obtainView(AbsListView.java:3189)
 at android.widget.ListView.makeAndAddView(ListView.java:2197)
 at android.widget.ListView.fillDown(ListView.java:824)
 at android.widget.ListView.fillFromTop(ListView.java:885)
 at android.widget.ListView.layoutChildren(ListView.java:1924)
 at android.widget.AbsListView.onLayout(AbsListView.java:2961)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:944)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2948)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2635)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7810)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
 at android.view.Choreographer.doCallbacks(Choreographer.java:723)
 at android.view.Choreographer.doFrame(Choreographer.java:658)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6938)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

9/8/2018 7:39:28 AM:503 -- Java.Lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AownCloud_Sync%2FRWPasswords-OC_YubikeyCR.kdbx from pid=17937, uid=10330 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e517f258e41f48d1b26c62fb5ffd1b94>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <ef8a592d5fc54c2fbeba6639a28e5da7>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <ef8a592d5fc54c2fbeba6639a28e5da7>:0 
at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <23e87dd929b5410bb246b44faae222fa>:0
  at keepass2android.Io.AndroidContentStorage.TryGetDisplayName (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& displayName) [0x00017] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AownCloud_Sync%2FRWPasswords-OC_YubikeyCR.kdbx from pid=17937, uid=10330 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
 at android.os.Parcel.readException(Parcel.java:1959)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
 at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
 at android.content.ContentResolver.query(ContentResolver.java:760)
 at android.content.ContentResolver.query(ContentResolver.java:710)
 at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.n_bindView(Native Method)
 at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.bindView(FileSelectActivity_MyCursorAdapter.java:46)
 at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
 at android.widget.AbsListView.obtainView(AbsListView.java:3189)
 at android.widget.ListView.makeAndAddView(ListView.java:2197)
 at android.widget.ListView.fillDown(ListView.java:824)
 at android.widget.ListView.fillSpecific(ListView.java:1534)
 at android.widget.ListView.layoutChildren(ListView.java:1914)
 at android.widget.AbsListView.onLayout(AbsListView.java:2961)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:944)
 at android.view.View.layout(View.java:20822)
 at android.view.ViewGroup.layout(ViewGroup.java:6401)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2948)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2635)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7810)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
 at android.view.Choreographer.doCallbacks(Choreographer.java:723)
 at android.view.Choreographer.doFrame(Choreographer.java:658)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6938)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

9/8/2018 7:39:28 AM:840 -- PasswordActivity.OnStop
9/8/2018 7:39:28 AM:841 -- PasswordActivity.OnDestroyTrue
9/8/2018 7:39:29 AM:634 -- FileSelect.OnPause
9/8/2018 7:39:29 AM:646 -- SelectStorageLocationActivity.OnCreate
9/8/2018 7:39:30 AM:160 -- FileSelect.OnStop
9/8/2018 7:39:31 AM:232 -- onAR
9/8/2018 7:39:31 AM:233 -- base.onAR
9/8/2018 7:39:31 AM:235 -- com.android.documentsui
9/8/2018 7:39:34 AM:818 -- onAR
9/8/2018 7:39:34 AM:819 -- base.onAR
9/8/2018 7:39:34 AM:819 -- FileSelection returned content://com.android.externalstorage.documents/document/primary%3AownCloud_2nd%2FRWPasswords-OC_YubikeyCR.kdbx
9/8/2018 7:39:34 AM:826 -- FileSelection returned filename 
9/8/2018 7:39:34 AM:827 -- TakePersistableUriPermission
9/8/2018 7:39:34 AM:832 -- File flags: 326
9/8/2018 7:39:34 AM:844 -- No AppTask in OnActivityResult
9/8/2018 7:39:34 AM:887 -- PasswordActivity.OnCreate
9/8/2018 7:39:34 AM:888 -- PasswordActivity:apptask=
9/8/2018 7:39:34 AM:890 -- Loaded task keepass2android.NullTask
9/8/2018 7:39:34 AM:951 -- PasswordActivity.OnStart
9/8/2018 7:39:34 AM:953 -- PasswordActivity.OnResume
9/8/2018 7:39:34 AM:953 --  DatabaseIsUnlocked=False
9/8/2018 7:39:34 AM:954 -- starting: True, Finishing: False, _performingLoad: False
9/8/2018 7:39:34 AM:957 -- Pre-loading database file starting
9/8/2018 7:39:34 AM:958 -- CFS: OpenWhenNoLocalChanges
9/8/2018 7:39:34 AM:958 -- CFS: hashing cached version
9/8/2018 7:39:34 AM:964 -- PasswordActivity.OnPause
9/8/2018 7:39:35 AM:89 -- PasswordActivity.OnResume
9/8/2018 7:39:35 AM:90 --  DatabaseIsUnlocked=False
9/8/2018 7:39:35 AM:91 -- starting: False, Finishing: False, _performingLoad: False
9/8/2018 7:39:35 AM:95 -- FP: Create FingerprintDecryption
9/8/2018 7:39:35 AM:97 -- FP: Init for Dec
9/8/2018 7:39:35 AM:106 -- CFS: Files in Sync
9/8/2018 7:39:35 AM:106 -- failed to init fingerprint unlock:Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <248fedeff5864311afa259496aeb0dcd>:0 
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00088] in <248fedeff5864311afa259496aeb0dcd>:0 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
 at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
 at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
 at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
 at android.app.Activity.performResume(Activity.java:7353)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6938)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
 at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:436)
 at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:273)
 at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2659)
 at javax.crypto.Cipher.tryCombinations(Cipher.java:2570)
 at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2475)
 at javax.crypto.Cipher.chooseProvider(Cipher.java:566)
 at javax.crypto.Cipher.init(Cipher.java:973)
 at javax.crypto.Cipher.init(Cipher.java:908)
 ... 13 more

9/8/2018 7:39:35 AM:110 -- Pre-loading database file completed
9/8/2018 7:39:35 AM:525 -- FileSelect.OnDestroyTrue
9/8/2018 7:40:02 AM:544 -- PasswordActivity.OnActivityResult 874348/1001
9/8/2018 7:40:02 AM:545 -- No AppTask in OnActivityResult
9/8/2018 7:40:02 AM:553 -- System.NotImplementedException: The method or operation is not implemented.
  at keepass2android.Io.AndroidContentStorage.GetParentPath (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00000] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.GetParentPath (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00000] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at keepass2android.Io.CachingFileStorage.GetParentPath (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00000] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at keepass2android.PasswordActivity+ChallengeAuxFileLoader.GetDefaultAuxLocation () [0x00016] in <248fedeff5864311afa259496aeb0dcd>:0 
  at keepass2android.PasswordActivity+AuxFileLoader+<>c__DisplayClass2_0.<LoadAuxFile>b__0 (Java.Lang.Object[] <p0>) [0x00000] in <248fedeff5864311afa259496aeb0dcd>:0 
9/8/2018 7:40:02 AM:555 -- CFS: OpenWhenNoLocalChanges
9/8/2018 7:40:02 AM:567 -- keepass2android.Io.DocumentAccessRevokedException: Exception of type 'keepass2android.Io.DocumentAccessRevokedException' was thrown.
  at keepass2android.Io.AndroidContentStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00034] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <de18cbdbc6bc4c8aa724e464db651ce4>:0 
  at KeeChallenge.ChallengeInfo.Load (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00013] in <248fedeff5864311afa259496aeb0dcd>:0 
9/8/2018 7:40:02 AM:592 -- PasswordActivity.OnPause
9/8/2018 7:40:30 AM:82 -- PasswordActivity.OnActivityResult Canceled/793
9/8/2018 7:40:30 AM:83 -- TryGetFromActivityResult: no data
9/8/2018 7:40:30 AM:84 -- PasswordActivity.OnResume
9/8/2018 7:40:30 AM:84 --  DatabaseIsUnlocked=False
9/8/2018 7:40:30 AM:86 -- starting: False, Finishing: False, _performingLoad: False
9/8/2018 7:40:30 AM:90 -- FP: Create FingerprintDecryption
9/8/2018 7:40:30 AM:92 -- FP: Init for Dec
9/8/2018 7:40:30 AM:102 -- failed to init fingerprint unlock:Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <248fedeff5864311afa259496aeb0dcd>:0 
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00088] in <248fedeff5864311afa259496aeb0dcd>:0 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
 at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
 at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
 at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
 at android.app.Activity.performResume(Activity.java:7353)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6938)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
 at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:436)
 at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:273)
 at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2659)
 at javax.crypto.Cipher.tryCombinations(Cipher.java:2570)
 at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2475)
 at javax.crypto.Cipher.chooseProvider(Cipher.java:566)
 at javax.crypto.Cipher.init(Cipher.java:973)
 at javax.crypto.Cipher.init(Cipher.java:908)
 ... 13 more

9/8/2018 7:40:56 AM:895 -- PasswordActivity.OnPause
9/8/2018 7:40:56 AM:908 -- AppSettingsActivity.OnCreate
9/8/2018 7:40:56 AM:909 -- AppSettingsActivity:apptask=
9/8/2018 7:40:56 AM:950 -- AppSettingsActivity.OnStart
9/8/2018 7:40:56 AM:953 -- AppSettingsActivity.OnResume
9/8/2018 7:40:56 AM:953 --  DatabaseIsUnlocked=False
9/8/2018 7:40:57 AM:416 -- PasswordActivity.OnStop

**Comment by PhilippC** [comment]
even though there are a few exceptions here, this is not related to the "endlessly appearing yubichallenge window" described by mail. This would need another log. The exceptions in the log are either correctly handled by the app or related to other issues in this milestone (e.g. for fingerprint)
