### ISSUE TITLE
Error opening in Sharepoint

### ISSUE THREAD

**Issue by tomprofan** [PhilippC/keepass2android#580]
I try to open a file in a SharePoint behind a Citrix netscaler. I use https Webdav. Authenticate on netscaler works and it promps for the data base password and then it fails to load. If I paste the link in Chrome the file is dowmloaded and can be opened with the App.

05.10.2018 13:39:08:470 -- Creating application keepass2android.keepass2android. Version=127
05.10.2018 13:39:08:817 -- PasswordActivity.OnCreate
05.10.2018 13:39:08:826 -- PasswordActivity:apptask=
05.10.2018 13:39:08:854 -- Loaded task keepass2android.NullTask
05.10.2018 13:39:10:73 -- PasswordActivity.OnStart
05.10.2018 13:39:10:148 -- PasswordActivity.OnResume
05.10.2018 13:39:10:150 --  DatabaseIsUnlocked=False
05.10.2018 13:39:10:156 -- starting: True, Finishing: False, _performingLoad: False
05.10.2018 13:39:10:275 -- Pre-loading database file starting
05.10.2018 13:39:10:280 -- PasswordActivity.OnPause
05.10.2018 13:39:10:309 -- CFS: OpenWhenNoLocalChanges
05.10.2018 13:39:10:312 -- CFS: hashing cached version
05.10.2018 13:39:10:692 -- PasswordActivity.OnResume
05.10.2018 13:39:10:692 --  DatabaseIsUnlocked=False
05.10.2018 13:39:10:695 -- starting: False, Finishing: False, _performingLoad: False
05.10.2018 13:39:11:543 -- CFS: Files in Sync
05.10.2018 13:39:11:560 -- Pre-loading database file completed
05.10.2018 13:39:13:70 -- PasswordActivity.OnPause
05.10.2018 13:39:13:106 -- FileSelect.OnCreate
05.10.2018 13:39:13:107 -- FileSelect:apptask=NullTask
05.10.2018 13:39:13:111 -- Loaded task keepass2android.NullTask
05.10.2018 13:39:13:346 -- FileSelect.OnStart
05.10.2018 13:39:13:351 -- FileSelect.OnResume
05.10.2018 13:39:13:533 -- Java.Lang.SecurityException: Permission Denial: opening provider org.chromium.chrome.browser.util.ChromeFileProvider from ProcessRecord{77f7a53 2074:keepass2android.keepass2android/u0a213} (pid=2074, uid=10213) that is not exported from UID 10132
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at keepass2android.Io.AndroidContentStorage.TryGetDisplayName (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& displayName) [0x00017] in <a845e75707b54877bb366548a90ed2a7>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: opening provider org.chromium.chrome.browser.util.ChromeFileProvider from ProcessRecord{77f7a53 2074:keepass2android.keepass2android/u0a213} (pid=2074, uid=10213) that is not exported from UID 10132
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.os.Parcel.readException(Parcel.java:1905)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5282)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6164)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2559)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1786)
	at android.content.ContentResolver.query(ContentResolver.java:744)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.n_bindView(Native Method)
	at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.bindView(FileSelectActivity_MyCursorAdapter.java:46)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
	at android.widget.AbsListView.obtainView(AbsListView.java:3189)
	at android.widget.ListView.makeAndAddView(ListView.java:2197)
	at android.widget.ListView.fillDown(ListView.java:824)
	at android.widget.ListView.fillFromTop(ListView.java:885)
	at android.widget.ListView.layoutChildren(ListView.java:1924)
	at android.widget.AbsListView.onLayout(AbsListView.java:2961)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2961)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2648)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

05.10.2018 13:39:14:25 -- PasswordActivity.OnStop
05.10.2018 13:39:14:34 -- PasswordActivity.OnDestroyTrue
05.10.2018 13:39:19:334 -- No AppTask in OnActivityResult
05.10.2018 13:39:19:411 -- Java.Lang.SecurityException: Permission Denial: opening provider org.chromium.chrome.browser.util.ChromeFileProvider from ProcessRecord{77f7a53 2074:keepass2android.keepass2android/u0a213} (pid=2074, uid=10213) that is not exported from UID 10132
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Android.Content.ContentResolver.Query (Android.Net.Uri uri, System.String[] projection, System.String selection, System.String[] selectionArgs, System.String sortOrder, Android.OS.CancellationSignal cancellationSignal) [0x000d2] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at keepass2android.Io.AndroidContentStorage.TryGetDisplayName (KeePassLib.Serialization.IOConnectionInfo ioc, System.String& displayName) [0x00017] in <a845e75707b54877bb366548a90ed2a7>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: Permission Denial: opening provider org.chromium.chrome.browser.util.ChromeFileProvider from ProcessRecord{77f7a53 2074:keepass2android.keepass2android/u0a213} (pid=2074, uid=10213) that is not exported from UID 10132
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.os.Parcel.readException(Parcel.java:1905)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5282)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6164)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2559)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1786)
	at android.content.ContentResolver.query(ContentResolver.java:744)
	at android.content.ContentResolver.query(ContentResolver.java:710)
	at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.n_bindView(Native Method)
	at md5f0702f468598c68ce18586502249fb40.FileSelectActivity_MyCursorAdapter.bindView(FileSelectActivity_MyCursorAdapter.java:46)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
	at android.widget.AbsListView.obtainView(AbsListView.java:3189)
	at android.widget.ListView.makeAndAddView(ListView.java:2197)
	at android.widget.ListView.fillDown(ListView.java:824)
	at android.widget.ListView.fillFromTop(ListView.java:885)
	at android.widget.ListView.layoutChildren(ListView.java:1952)
	at android.widget.AbsListView.onLayout(AbsListView.java:2961)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
	at android.view.View.layout(View.java:20854)
	at android.view.ViewGroup.layout(ViewGroup.java:6401)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2961)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2648)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7832)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

05.10.2018 13:39:19:428 -- FileSelect.OnPause
05.10.2018 13:39:19:454 -- PasswordActivity.OnCreate
05.10.2018 13:39:19:455 -- PasswordActivity:apptask=
05.10.2018 13:39:19:459 -- Loaded task keepass2android.NullTask
05.10.2018 13:39:19:598 -- PasswordActivity.OnStart
05.10.2018 13:39:19:603 -- PasswordActivity.OnResume
05.10.2018 13:39:19:604 --  DatabaseIsUnlocked=False
05.10.2018 13:39:19:606 -- starting: True, Finishing: False, _performingLoad: False
05.10.2018 13:39:19:611 -- Pre-loading database file starting
05.10.2018 13:39:19:614 -- CFS: OpenWhenNoLocalChanges
05.10.2018 13:39:19:615 -- CFS: hashing cached version
05.10.2018 13:39:19:623 -- PasswordActivity.OnPause
05.10.2018 13:39:19:843 -- PasswordActivity.OnResume
05.10.2018 13:39:19:844 --  DatabaseIsUnlocked=False
05.10.2018 13:39:19:846 -- starting: False, Finishing: False, _performingLoad: False
05.10.2018 13:39:20:245 -- FileSelect.OnStop
05.10.2018 13:39:20:336 -- FileSelect.OnDestroyTrue
05.10.2018 13:39:20:688 -- CFS: Files in Sync
05.10.2018 13:39:20:689 -- Pre-loading database file completed
05.10.2018 13:39:25:684 -- PasswordActivity.OnActivityResult 874348/1000
05.10.2018 13:39:25:685 -- No AppTask in OnActivityResult
05.10.2018 13:39:26:313 -- System.FormatException: The file signature is invalid. Either the file isn't a KeePass database file at all or it is corrupted.
  at KeePassLib.Serialization.KdbxFile.LoadHeader (KeePassLib.Serialization.BinaryReaderEx br) [0x00093] in <1ba2655a174d4c5395f8168cf1f6a0cd>:0 
  at KeePassLib.Serialization.KdbxFile.Load (System.IO.Stream sSource, KeePassLib.Serialization.KdbxFormat fmt, KeePassLib.Interfaces.IStatusLogger slLogger) [0x00083] in <1ba2655a174d4c5395f8168cf1f6a0cd>:0 
  at keepass2android.KdbxDatabaseFormat.PopulateDatabaseFromStream (KeePassLib.PwDatabase db, System.IO.Stream s, KeePassLib.Interfaces.IStatusLogger slLogger) [0x00013] in <a845e75707b54877bb366548a90ed2a7>:0 
  at KeePassLib.PwDatabase.Open (System.IO.Stream s, System.String fileNameWithoutPathAndExt, KeePassLib.Serialization.IOConnectionInfo ioSource, KeePassLib.Keys.CompositeKey pwKey, KeePassLib.Interfaces.IStatusLogger slLogger, KeePassLib.IDatabaseFormat format) [0x000a6] in <1ba2655a174d4c5395f8168cf1f6a0cd>:0 
  at keepass2android.Database.PopulateDatabaseFromStream (KeePassLib.PwDatabase pwDatabase, System.IO.Stream s, KeePassLib.Serialization.IOConnectionInfo iocInfo, KeePassLib.Keys.CompositeKey compositeKey, keepass2android.ProgressDialogStatusLogger status, KeePassLib.IDatabaseFormat databaseFormat) [0x00013] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.Database.LoadData (keepass2android.IKp2aApp app, KeePassLib.Serialization.IOConnectionInfo iocInfo, System.IO.MemoryStream databaseData, KeePassLib.Keys.CompositeKey compositeKey, keepass2android.ProgressDialogStatusLogger status, KeePassLib.IDatabaseFormat databaseFormat) [0x00033] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.Kp2aApp.LoadDatabase (KeePassLib.Serialization.IOConnectionInfo ioConnectionInfo, System.IO.MemoryStream memoryStream, KeePassLib.Keys.CompositeKey compositeKey, keepass2android.ProgressDialogStatusLogger statusLogger, KeePassLib.IDatabaseFormat databaseFormat) [0x00058] in <7afcc631c65a49968e148310b528842e>:0 
  at keepass2android.LoadDb.TryLoad (System.IO.MemoryStream databaseStream) [0x00021] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.LoadDb.Run () [0x000a4] in <a845e75707b54877bb366548a90ed2a7>:0 
05.10.2018 13:39:26:328 -- OnFinish message: Ein Fehler ist aufgetreten: The file signature is invalid. Either the file isn't a KeePass database file at all or it is corrupted.
05.10.2018 13:39:29:726 -- PasswordActivity.OnPause
05.10.2018 13:39:29:760 -- AppSettingsActivity.OnCreate
05.10.2018 13:39:29:761 -- AppSettingsActivity:apptask=
05.10.2018 13:39:30:3 -- AppSettingsActivity.OnStart
05.10.2018 13:39:30:14 -- AppSettingsActivity.OnResume
05.10.2018 13:39:30:16 --  DatabaseIsUnlocked=False
05.10.2018 13:39:30:621 -- PasswordActivity.OnStop
05.10.2018 13:39:38:924 -- AppSettingsActivity.OnPause
05.10.2018 13:39:44:763 -- AppSettingsActivity.OnStop
05.10.2018 13:40:38:364 -- AppSettingsActivity.OnStart
05.10.2018 13:40:38:366 -- AppSettingsActivity.OnResume
05.10.2018 13:40:38:366 --  DatabaseIsUnlocked=False

**Comment by PhilippC** [comment]
sorry that I never had time to look into this. The OneDrive implementation is completely changed since the report, so I'm closing this. Reopen with an up-to-date log from 1.12-r3 or later if this still is relevant and exists.
