### ISSUE TITLE
getProtectedFieldsList always returns null

### ISSUE THREAD

**Issue by Skycoder42** [PhilippC/keepass2android#627]
The current `keepass2android.pluginsdk.PluginActionBroadcastReceiver.ActionSelectedAction.getProtectedFieldsList` method always returns a null array. The reason for that is pretty straight forward:

In the implementation of `PluginEntryActionBase.getProtectedFieldsListFromIntent` the `Intent.getStringArrayExtra` method is used to retrieve the list of protected fields from the intent. This results in an exception:

```
12-03 18:27:31.676 32418 32418 W Bundle  : Key keepass2android.EXTRA_PROTECTED_FIELDS_LIST expected String[] but value was a java.lang.String.  The default value <null> was returned.
12-03 18:27:31.681 32418 32418 W Bundle  : Attempt to cast generated internal exception:
12-03 18:27:31.681 32418 32418 W Bundle  : java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.String[]
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.os.BaseBundle.getStringArray(BaseBundle.java:1440)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.content.Intent.getStringArrayExtra(Intent.java:7285)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at keepass2android.pluginsdk.PluginActionBroadcastReceiver$PluginEntryActionBase.getProtectedFieldsListFromIntent(PluginActionBroadcastReceiver.java:68)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at keepass2android.pluginsdk.PluginActionBroadcastReceiver$ActionSelectedAction.getProtectedFieldsList(PluginActionBroadcastReceiver.java:149)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at de.skycoder42.kpt.TransferActionReceiver.actionSelected(TransferActionReceiver.java:37)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at keepass2android.pluginsdk.PluginActionBroadcastReceiver.onReceive(PluginActionBroadcastReceiver.java:271)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3257)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.os.Looper.loop(Looper.java:251)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at java.lang.reflect.Method.invoke(Native Method)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-03 18:27:31.681 32418 32418 W Bundle  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

As one can see, this happens because the intent actually contains a string, not a string array. Upon further inspection, I found out that the actual extra is a JSON-Array encoded as string.

The way to fix this would be to simply read the extra as a string and deserialize it using the standard json classes.

**Comment by Skycoder42** [comment]
A PR was proposed that uses `org.json.JSONArray` to perform the deserialization and convert the extra to an actuals `String[]`.
