### ISSUE TITLE
Crash on adding fingerprint

### ISSUE THREAD

**Issue by aksh1618** [PhilippC/keepass2android#677]
The app crashes for me as soon as I add a fingerprint using either the quick unlock or the full mode. Tested on both latest stable and beta, I have been facing this for 3-4 versions now.

## Steps to Reproduce

1. Enter db password and unlock.
2. Select 'Yes' in bottom prompt/suggestion to use fingerprint.
3. Select either the quick unlock or the full mode.
4. Touch the fingerprint sensor.

## Device Info

- Device: Redmi Note 4 SD (mido)
- Android Version: 9.0 (AOSP Extended)
- Keepaas2Android Version: Latest Stable and Beta

## Logs

```
time: 1547346685920
msg: android.security.KeyStoreException: Key user not authenticated
stacktrace: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:505)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	... 1 more
Caused by: javax.crypto.IllegalBlockSizeException
	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6739)
	... 3 more
Caused by: android.security.KeyStoreException: Key user not authenticated
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
	... 10 more
```

**Comment by mc-ff** [comment]
Same issue here. Galaxy A5 2016 with Android 8.1 rooted. Even tried different custom roms. Fingerprint working on all other apps.

**Comment by mc-ff** [comment]
Seems to be fixed for me as I had set fingerprint with PIN but than changed to unlock by slide. When setting back to another unlock Mode the crash issue did not come up again. Hope this will fix it for you, too...

**Comment by Defman21** [comment]
I changed my Pattern+Fingerprint to Slide (so it removed my fingerprint), then changed it back to Pattern+Fingerprint, created a new fingerprint and tried to enable the unlock in KeePass. That didn't work, I'm getting the same IllegalBlockSizeException error.

Pixel Experience 9.0 Pie (Magisk rooted, SafetyNet check OK), Project Treble.

Telegram works fine, though.

```
2/16/2019 6:18:18 PM:405 -- PasswordActivity.OnPause
2/16/2019 6:18:19 PM:170 -- PasswordActivity.OnResume
2/16/2019 6:18:19 PM:171 --  DatabaseIsUnlocked=False
2/16/2019 6:18:19 PM:173 -- starting: False, Finishing: False, _performingLoad: False
2/16/2019 6:18:20 PM:68 -- PasswordActivity.OnPause
2/16/2019 6:18:20 PM:89 -- AppSettingsActivity.OnCreate
2/16/2019 6:18:20 PM:90 -- AppSettingsActivity:apptask=
2/16/2019 6:18:20 PM:168 -- AppSettingsActivity.OnStart
2/16/2019 6:18:20 PM:170 -- AppSettingsActivity.OnResume
2/16/2019 6:18:20 PM:171 --  DatabaseIsUnlocked=False
2/16/2019 6:18:20 PM:720 -- PasswordActivity.OnStop
2/16/2019 6:18:23 PM:734 -- AppSettingsActivity.OnPause
2/16/2019 6:18:24 PM:840 -- AppSettingsActivity.OnResume
2/16/2019 6:18:24 PM:841 --  DatabaseIsUnlocked=False
2/16/2019 6:18:28 PM:861 -- AppSettingsActivity.OnPause
2/16/2019 6:18:28 PM:875 -- PasswordActivity.OnStart
2/16/2019 6:18:28 PM:878 -- PasswordActivity.OnResume
2/16/2019 6:18:28 PM:879 --  DatabaseIsUnlocked=False
2/16/2019 6:18:28 PM:880 -- starting: True, Finishing: False, _performingLoad: False
2/16/2019 6:18:29 PM:390 -- AppSettingsActivity.OnStop
2/16/2019 6:18:29 PM:392 -- AppSettingsActivity.OnDestroyTrue
2/16/2019 6:18:38 PM:880 -- PasswordActivity.OnActivityResult 874348/1000
2/16/2019 6:18:38 PM:882 -- No AppTask in OnActivityResult
2/16/2019 6:18:40 PM:56 -- ReadXmlStreamed: 533ms
2/16/2019 6:18:40 PM:158 -- LoadDB OK
2/16/2019 6:18:40 PM:178 -- Starting/Updating OngoingNotificationsService. Database Unlocked
2/16/2019 6:18:40 PM:518 -- PasswordActivity.OnPause
2/16/2019 6:18:40 PM:523 -- Timeout start
2/16/2019 6:18:40 PM:574 -- GroupActivity.OnCreate
2/16/2019 6:18:40 PM:576 -- GroupActivity:apptask=
2/16/2019 6:18:40 PM:582 -- Loaded task keepass2android.NullTask
2/16/2019 6:18:40 PM:748 -- GroupActivity.OnStart
2/16/2019 6:18:40 PM:753 -- GroupActivity.OnResume
2/16/2019 6:18:40 PM:754 --  DatabaseIsUnlocked=True
2/16/2019 6:18:40 PM:755 -- Timeout cancel
2/16/2019 6:18:41 PM:578 -- PasswordActivity.OnStop
2/16/2019 6:18:43 PM:874 -- GroupActivity.OnPause
2/16/2019 6:18:43 PM:875 -- Timeout start
2/16/2019 6:18:43 PM:895 -- DatabaseSettingsActivity.OnCreate
2/16/2019 6:18:43 PM:896 -- DatabaseSettingsActivity:apptask=
2/16/2019 6:18:44 PM:46 -- DatabaseSettingsActivity.OnStart
2/16/2019 6:18:44 PM:48 -- DatabaseSettingsActivity.OnResume
2/16/2019 6:18:44 PM:48 --  DatabaseIsUnlocked=True
2/16/2019 6:18:44 PM:49 -- Timeout cancel
2/16/2019 6:18:44 PM:658 -- GroupActivity.OnStop
2/16/2019 6:18:45 PM:473 -- DatabaseSettingsActivity.OnPause
2/16/2019 6:18:45 PM:475 -- Timeout start
2/16/2019 6:18:46 PM:97 -- DatabaseSettingsActivity.OnStop
2/16/2019 6:18:46 PM:250 -- DatabaseSettingsActivity.OnStart
2/16/2019 6:18:46 PM:252 -- DatabaseSettingsActivity.OnResume
2/16/2019 6:18:46 PM:252 --  DatabaseIsUnlocked=True
2/16/2019 6:18:46 PM:253 -- Timeout cancel
2/16/2019 6:18:53 PM:17 -- DatabaseSettingsActivity.OnPause
2/16/2019 6:18:53 PM:19 -- Timeout start
2/16/2019 6:18:53 PM:44 -- FingerprintSetupActivity.OnCreate
2/16/2019 6:18:53 PM:45 -- FingerprintSetupActivity:apptask=
2/16/2019 6:18:53 PM:130 -- FingerprintSetupActivity.OnStart
2/16/2019 6:18:53 PM:132 -- FingerprintSetupActivity.OnResume
2/16/2019 6:18:53 PM:133 --  DatabaseIsUnlocked=True
2/16/2019 6:18:53 PM:134 -- Timeout cancel
2/16/2019 6:18:53 PM:201 -- FingerprintSetupActivity.OnPause
2/16/2019 6:18:53 PM:202 -- Timeout start
2/16/2019 6:18:53 PM:305 -- FingerprintSetupActivity.OnResume
2/16/2019 6:18:53 PM:306 --  DatabaseIsUnlocked=True
2/16/2019 6:18:53 PM:307 -- Timeout cancel
2/16/2019 6:18:53 PM:765 -- DatabaseSettingsActivity.OnStop
2/16/2019 6:18:55 PM:687 -- FP: Create FingerprintEncryption
2/16/2019 6:18:55 PM:703 -- FP: CreateKey 
2/16/2019 6:18:55 PM:807 -- FP: Init for Enc 
2/16/2019 6:18:55 PM:851 -- FP: StartListening 
2/16/2019 6:18:56 PM:682 -- FP: OnAuthenticationSucceeded 
2/16/2019 6:18:56 PM:683 -- FP: StopListening 
2/16/2019 6:18:58 PM:2 -- FP: Encrypting
2/16/2019 6:18:58 PM:68 -- Java.Security.GeneralSecurityException: Exception of type 'Java.Security.GeneralSecurityException' was thrown. ---> Java.Lang.Exception: Key user not authenticated
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Javax.Crypto.Cipher.DoFinal (System.Byte[] input) [0x00029] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at keepass2android.FingerprintCrypt.Encrypt (System.String textToEncrypt) [0x0001b] in <7afcc631c65a49968e148310b528842e>:0 
  at keepass2android.FingerprintCrypt.StoreEncrypted (System.String textToEncrypt, System.String prefKey, Android.Content.ISharedPreferencesEditor edit) [0x00000] in <7afcc631c65a49968e148310b528842e>:0 
  at keepass2android.FingerprintSetupActivity.StoreUnlockMode () [0x0006c] in <7afcc631c65a49968e148310b528842e>:0 
  at keepass2android.FingerprintSetupActivity.<OnFingerprintAuthSucceeded>b__25_0 () [0x00022] in <7afcc631c65a49968e148310b528842e>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at (wrapper dynamic-method) System.Object.48aeabb1-7c12-45b1-b887-cf559e9341bc(intptr,intptr)
  --- End of managed Java.Security.GeneralSecurityException stack trace ---
javax.crypto.IllegalBlockSizeException
 at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
 at javax.crypto.Cipher.doFinal(Cipher.java:2055)
 at mono.java.lang.RunnableImplementor.n_run(Native Method)
 at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6718)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.security.KeyStoreException: Key user not authenticated
 at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
 at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
 at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
 at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
 ... 10 more

2/16/2019 6:18:59 PM:898 -- Creating application keepass2android.keepass2android. Version=127
2/16/2019 6:19:00 PM:122 -- DatabaseSettingsActivity.OnCreate
2/16/2019 6:19:00 PM:128 -- DatabaseSettingsActivity:apptask=
2/16/2019 6:19:00 PM:432 -- DatabaseSettingsActivity.OnStart
2/16/2019 6:19:00 PM:444 -- DatabaseSettingsActivity.OnResume
2/16/2019 6:19:00 PM:446 --  DatabaseIsUnlocked=False
2/16/2019 6:19:00 PM:451 -- Database not loaded, couldn't lock
2/16/2019 6:19:00 PM:578 -- Finishing md5f0702f468598c68ce18586502249fb40.DatabaseSettingsActivity due to database lock
2/16/2019 6:19:00 PM:717 -- DatabaseSettingsActivity.OnPause
2/16/2019 6:19:00 PM:827 -- GroupActivity.OnCreate
2/16/2019 6:19:00 PM:828 -- GroupActivity:apptask=
2/16/2019 6:19:00 PM:838 -- Loaded task keepass2android.NullTask
2/16/2019 6:19:00 PM:895 -- PasswordActivity.OnCreate
2/16/2019 6:19:00 PM:897 -- PasswordActivity:apptask=
2/16/2019 6:19:00 PM:905 -- Loaded task keepass2android.NullTask
2/16/2019 6:19:01 PM:684 -- PasswordActivity.OnStart
2/16/2019 6:19:01 PM:718 -- PasswordActivity.OnActivityResult Canceled/0
2/16/2019 6:19:01 PM:719 -- TryGetFromActivityResult: no data
2/16/2019 6:19:01 PM:725 -- PasswordActivity.OnResume
2/16/2019 6:19:01 PM:726 --  DatabaseIsUnlocked=False
2/16/2019 6:19:01 PM:728 -- starting: True, Finishing: False, _performingLoad: False
2/16/2019 6:19:01 PM:770 -- Pre-loading database file starting
2/16/2019 6:19:01 PM:790 -- CFS: OpenWhenNoLocalChanges
2/16/2019 6:19:01 PM:790 -- PasswordActivity.OnPause
2/16/2019 6:19:01 PM:791 -- CFS: hashing cached version
2/16/2019 6:19:01 PM:966 -- PasswordActivity.OnResume
2/16/2019 6:19:01 PM:966 --  DatabaseIsUnlocked=False
2/16/2019 6:19:01 PM:967 -- starting: False, Finishing: False, _performingLoad: False
2/16/2019 6:19:02 PM:415 -- GroupActivity.OnDestroyTrue
2/16/2019 6:19:02 PM:514 -- DatabaseSettingsActivity.OnStop
2/16/2019 6:19:02 PM:518 -- DatabaseSettingsActivity.OnDestroyTrue
2/16/2019 6:19:03 PM:26 -- CFS: Files in Sync
2/16/2019 6:19:03 PM:45 -- Pre-loading database file completed
2/16/2019 6:19:05 PM:405 -- PasswordActivity.OnPause
2/16/2019 6:19:05 PM:423 -- AppSettingsActivity.OnCreate
2/16/2019 6:19:05 PM:424 -- AppSettingsActivity:apptask=
2/16/2019 6:19:05 PM:504 -- AppSettingsActivity.OnStart
2/16/2019 6:19:05 PM:506 -- AppSettingsActivity.OnResume
2/16/2019 6:19:05 PM:507 --  DatabaseIsUnlocked=False
2/16/2019 6:19:06 PM:62 -- PasswordActivity.OnStop
2/16/2019 6:19:07 PM:105 -- AppSettingsActivity.OnPause
2/16/2019 6:19:07 PM:782 -- AppSettingsActivity.OnStop
2/16/2019 6:19:10 PM:707 -- AppSettingsActivity.OnStart
2/16/2019 6:19:10 PM:708 -- AppSettingsActivity.OnResume
2/16/2019 6:19:10 PM:709 --  DatabaseIsUnlocked=False
```

**Comment by PhilippC** [comment]
seems the same as https://github.com/PhilippC/keepass2android/issues/155
