### ISSUE TITLE
Cant open kdbx file per webdav

### ISSUE THREAD

**Issue by Maranja** [PhilippC/keepass2android#716]
The connection is right, the App found the kdbx file at the Server & asks about the password. After entering the password, I got only this error: "Fehler:" ("Error:") witho7t any additional Informations.
This error comea at webdav http & https & sftp & ftp.
The file on the Server is not corrupt, IT works at some Windows Computer.

What this error mean?

**Comment by PhilippC** [comment]
So you entered the folder URI and used the app's internal file browser to get to the file? Then the connection should in fact be ok.
Can you please try to enable debug logging in the app settings and send me the log after trying to open the database?

**Comment by john159753** [comment]
@PhilippC - I am seeing this issue too with v1.06f.
The error occurs when using HTTPS WebDav, I cannot replicate with HTTP WebDav.

There is a file not found error in the logs:

> 2/21/2019 11:18:44 AM:412 -- PasswordActivity.OnActivityResult 874348/1000
2/21/2019 11:18:44 AM:440 -- No AppTask in OnActivityResult
2/21/2019 11:18:44 AM:521 -- System.IO.FileNotFoundException:  ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String p0) [0x00062] in <860acb9066e34d8fb1fc7684abe0383f>:0 
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <a845e75707b54877bb366548a90ed2a7>:0 
  --- End of managed Java.IO.FileNotFoundException stack trace ---
  java.io.FileNotFoundException
  at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:341)
  at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:111)
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.PasswordActivity.PreloadDbFile () [0x00037] in <7afcc631c65a49968e148310b528842e>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
2/21/2019 11:18:44 AM:538 -- OnFinish message: An error occured: 
2/21/2019 11:18:48 AM:799 -- PasswordActivity.OnPause
2/21/2019 11:18:48 AM:818 -- AppSettingsActivity.OnCreate
2/21/2019 11:18:48 AM:818 -- AppSettingsActivity:apptask=
2/21/2019 11:18:48 AM:859 -- AppSettingsActivity.OnStart
2/21/2019 11:18:48 AM:860 -- AppSettingsActivity.OnResume
2/21/2019 11:18:48 AM:860 --  DatabaseIsUnlocked=False
2/21/2019 11:18:49 AM:245 -- PasswordActivity.OnStop

**Comment by pums974** [comment]
I have exactly the same problem here.

My phone is about a Samsung Galaxy S7 edge with Android 6

**Comment by pums974** [comment]
Resolved by updating my phone to Android 7
