### ISSUE TITLE
Error saving database: java.io.FileNotFoundException: Not a whole file

### ISSUE THREAD

**Issue by haimiko** [PhilippC/keepass2android#763]
I get this error when trying to save my database:

````
3/27/2019 1:40:50 PM:991 -- GroupActivity.OnPause
3/27/2019 1:40:50 PM:996 -- Timeout start
3/27/2019 1:40:51 PM:23 -- EntryEditActivity.OnCreate
3/27/2019 1:40:51 PM:24 -- EntryEditActivity:apptask=
3/27/2019 1:40:51 PM:26 -- Loaded task keepass2android.NullTask
3/27/2019 1:40:51 PM:79 -- EntryEditActivity.OnStart
3/27/2019 1:40:51 PM:80 -- EntryEditActivity.OnResume
3/27/2019 1:40:51 PM:80 --  DatabaseIsUnlocked=True
3/27/2019 1:40:51 PM:80 -- Timeout cancel
3/27/2019 1:40:51 PM:472 -- GroupActivity.OnStop
3/27/2019 1:40:57 PM:10 -- Xml WriteDocument: 400ms
3/27/2019 1:40:57 PM:36 -- Java.IO.FileNotFoundException: Not a whole file
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d8e5a69113614d34b2b88e3d068e1fbe>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <733f038b1ff344b4b5828c2a833a3728>:0 
  at Android.Content.ContentResolver.OpenFileDescriptor (Android.Net.Uri uri, System.String mode) [0x0004b] in <2e94d8bb0dbb44c596f8b00792c4fddd>:0 
  at keepass2android.Io.AndroidContentWriteTransaction.CommitWrite () [0x00016] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.Database.SaveData () [0x00056] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.SaveDb.PerformSaveWithoutCheck (keepass2android.Io.IFileStorage fileStorage, KeePassLib.Serialization.IOConnectionInfo ioc) [0x0001b] in <a845e75707b54877bb366548a90ed2a7>:0 
  at keepass2android.SaveDb.Run () [0x0014e] in <a845e75707b54877bb366548a90ed2a7>:0 
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: Not a whole file
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1172)
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1109)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
at java.lang.Thread.run(Thread.java:764)

3/27/2019 1:40:57 PM:39 -- OnFinish message: Not a whole file
3/27/2019 1:40:59 PM:300 -- EntryEditActivity.OnPause
3/27/2019 1:40:59 PM:301 -- Timeout start
3/27/2019 1:40:59 PM:328 -- TryGetFromActivityResult: no data
3/27/2019 1:40:59 PM:329 -- GroupActivity.OnStart
3/27/2019 1:40:59 PM:330 -- GroupActivity.OnResume
3/27/2019 1:40:59 PM:330 --  DatabaseIsUnlocked=True
3/27/2019 1:40:59 PM:330 -- Timeout cancel
3/27/2019 1:40:59 PM:723 -- EntryEditActivity.OnStop
3/27/2019 1:40:59 PM:725 -- EntryEditActivity.OnDestroyTrue
3/27/2019 1:41:02 PM:370 -- GroupActivity.OnPause
3/27/2019 1:41:02 PM:370 -- Timeout start
3/27/2019 1:41:02 PM:394 -- DatabaseSettingsActivity.OnCreate
3/27/2019 1:41:02 PM:394 -- DatabaseSettingsActivity:apptask=
3/27/2019 1:41:02 PM:434 -- DatabaseSettingsActivity.OnStart
3/27/2019 1:41:02 PM:435 -- DatabaseSettingsActivity.OnResume
3/27/2019 1:41:02 PM:435 --  DatabaseIsUnlocked=True
3/27/2019 1:41:02 PM:436 -- Timeout cancel
3/27/2019 1:41:02 PM:806 -- GroupActivity.OnStop
````

**Comment by PhilippC** [comment]
can you choose lock&close database, then Change database > Open database and select the file again and try again? Where exactly is the file located?

**Comment by haimiko** [comment]
I've tried that a few times.  I open the file directly from OneDrive.  I
don't use the internal plugin because there is too much delay when
opening.

**Comment by PhilippC** [comment]
It looks like the OneDrive app does not supporting writing back changes. If you don't want to use the built-in OneDrive implementation, you might use FolderSync or a a similar tool to sync to local files and open from there. Or you open with the built-in OneDrive, but then switch to "Use internal cache only" and only sync every now and then with the cloud.
