### ISSUE TITLE
Cannot unlock cloud database

### ISSUE THREAD

**Issue by carlolf** [PhilippC/keepass2android#781]
On my Huawei tablet with Android 7.0 I cannot unlock the cloud based database anymore. After password input, keepass2Android says: "Please unlock with password and reenable fingerprint access" (in fact, German text, translated here somehow). I do not know what to do. I tried with reboot, I tried with reinstallation. Nothing helped.

On my Huawei smartphone with Android 8.0 I do not have this problem.

**Comment by PhilippC** [comment]
can you please 
1.) try with the latest version from the beta channel (1.07-r1) https://play.google.com/apps/testing/keepass2android.keepass2android
2.) enable debug logging if the problem still exists and send me a log, e.g. here or to crocoapps@gmail.com

**Comment by carlolf** [comment]
Ok, PhilippC, I did as you suggested. There was no difference in the behavior of the app with the new 1.07 version. Here is the log:
`
10.04.2019 17:13:32:46 -- AppSettingsActivity.OnPause
10.04.2019 17:13:42:433 -- AppSettingsActivity.OnStop
10.04.2019 17:13:54:872 -- AppSettingsActivity.OnStart
10.04.2019 17:13:54:875 -- AppSettingsActivity.OnResume
10.04.2019 17:13:54:875 --  DB null
10.04.2019 17:15:18:208 -- AppSettingsActivity.OnPause
10.04.2019 17:15:18:850 -- AppSettingsActivity.OnStop
10.04.2019 17:15:33:38 -- AppSettingsActivity.OnStart
10.04.2019 17:15:33:40 -- AppSettingsActivity.OnResume
10.04.2019 17:15:33:40 --  DB null
10.04.2019 17:15:42:859 -- AppSettingsActivity.OnPause
10.04.2019 17:15:42:917 -- PasswordActivity.OnStart
10.04.2019 17:15:42:942 -- PasswordActivity.OnResume
10.04.2019 17:15:42:942 --  DB null
10.04.2019 17:15:42:943 -- starting: True, Finishing: False, _performingLoad: False
10.04.2019 17:15:42:999 -- Pre-loading database file starting
10.04.2019 17:15:42:999 -- FP: Create FingerprintDecryption
10.04.2019 17:15:43:1 -- CFS: OpenWhenNoLocalChanges
10.04.2019 17:15:43:2 -- FP: Init for Dec
10.04.2019 17:15:43:10 -- failed to init fingerprint unlock:Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <42483a0e42cb482da6be36caa63cd922>:0
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00088] in <42483a0e42cb482da6be36caa63cd922>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
at android.app.Activity.performResume(Activity.java:7017)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3622)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3687)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:6623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435)
at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:272)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2973)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2884)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
at javax.crypto.Cipher.init(Cipher.java:1329)
at javax.crypto.Cipher.init(Cipher.java:1267)
... 13 more

10.04.2019 17:15:43:130 -- Received intent to provide access to entry
10.04.2019 17:15:43:224 -- PasswordActivity.OnPause
10.04.2019 17:15:43:859 -- PasswordActivity.OnStop
10.04.2019 17:15:43:861 -- AppSettingsActivity.OnStop
10.04.2019 17:15:43:863 -- AppSettingsActivity.OnDestroyTrue
10.04.2019 17:16:03:156 -- PasswordActivity.OnStart
10.04.2019 17:16:03:164 -- PasswordActivity.OnResume
10.04.2019 17:16:03:165 --  DB null
10.04.2019 17:16:03:167 -- starting: True, Finishing: False, _performingLoad: False
10.04.2019 17:16:03:193 -- FP: Create FingerprintDecryption
10.04.2019 17:16:03:195 -- FP: Init for Dec
10.04.2019 17:16:03:205 -- failed to init fingerprint unlock:Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <42483a0e42cb482da6be36caa63cd922>:0
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00088] in <42483a0e42cb482da6be36caa63cd922>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
at android.app.Activity.performResume(Activity.java:7017)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3622)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3687)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:6623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435)
at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:272)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2973)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2884)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
at javax.crypto.Cipher.init(Cipher.java:1329)
at javax.crypto.Cipher.init(Cipher.java:1267)
... 13 more

10.04.2019 17:16:03:231 -- Received intent to provide access to entry
10.04.2019 17:16:12:749 -- PasswordActivity.OnPause
10.04.2019 17:16:13:28 -- PasswordActivity.OnStop
10.04.2019 17:16:15:439 -- KeePass.OnCreate
10.04.2019 17:16:15:440 -- KeePass:apptask=
10.04.2019 17:16:15:441 -- Loaded task keepass2android.NullTask
10.04.2019 17:16:15:442 -- KeePass.OnCreate
10.04.2019 17:16:15:448 -- KeePass.OnStart
10.04.2019 17:16:15:448 -- KeePass.OnStart
10.04.2019 17:16:15:508 -- Loaded task keepass2android.NullTask
10.04.2019 17:16:15:557 -- FileSelect.OnCreate
10.04.2019 17:16:15:635 -- FileSelect.OnStart
10.04.2019 17:16:15:657 -- FileSelect.OnResume
10.04.2019 17:16:15:662 -- FileSelect.OnPause
10.04.2019 17:16:15:703 -- FSSA.OnCreate
10.04.2019 17:16:15:813 -- PasswordActivity.OnCreate
10.04.2019 17:16:15:814 -- PasswordActivity:apptask=
10.04.2019 17:16:15:960 -- PasswordActivity.OnStart
10.04.2019 17:16:15:968 -- PasswordActivity.OnResume
10.04.2019 17:16:15:969 --  DB null
10.04.2019 17:16:15:970 -- starting: True, Finishing: False, _performingLoad: False
10.04.2019 17:16:15:978 -- Pre-loading database file starting
10.04.2019 17:16:15:980 -- CFS: OpenWhenNoLocalChanges
10.04.2019 17:16:16:47 -- PasswordActivity.OnPause
10.04.2019 17:16:16:91 -- Received intent to provide access to entry
10.04.2019 17:16:16:299 -- PasswordActivity.OnResume
10.04.2019 17:16:16:300 --  DB null
10.04.2019 17:16:16:301 -- starting: False, Finishing: False, _performingLoad: False
10.04.2019 17:16:16:308 -- FP: Create FingerprintDecryption
10.04.2019 17:16:16:310 -- FP: Init for Dec
10.04.2019 17:16:16:317 -- failed to init fingerprint unlock:Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <42483a0e42cb482da6be36caa63cd922>:0
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00088] in <42483a0e42cb482da6be36caa63cd922>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
at android.app.Activity.performResume(Activity.java:7017)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3622)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3687)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:6623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435)
at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:272)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2973)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2884)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
at javax.crypto.Cipher.init(Cipher.java:1329)
at javax.crypto.Cipher.init(Cipher.java:1267)
... 13 more

10.04.2019 17:16:16:419 -- FileSelect.OnStop
10.04.2019 17:16:16:515 -- FileSelect.OnDestroyTrue
10.04.2019 17:16:16:524 -- KeePass.OnStop
10.04.2019 17:16:16:524 -- KeePass.OnDestroyTrue
10.04.2019 17:16:16:525 -- KeePass.OnDestroyTrue
10.04.2019 17:16:55:854 -- PasswordActivity.OnPause
10.04.2019 17:16:55:884 -- FSSA.OnCreate
10.04.2019 17:16:55:975 -- LockingActivity: OnActivityResult
10.04.2019 17:16:55:976 -- PasswordActivity.OnActivityResult 874348/1000
10.04.2019 17:16:55:989 -- PasswordActivity.OnResume
10.04.2019 17:16:55:990 --  DB null
10.04.2019 17:16:55:991 -- starting: False, Finishing: False, _performingLoad: True
10.04.2019 17:16:55:997 -- FP: Create FingerprintDecryption
10.04.2019 17:16:55:999 -- FP: Init for Dec
10.04.2019 17:16:56:7 -- failed to init fingerprint unlock:Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <42483a0e42cb482da6be36caa63cd922>:0
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00088] in <42483a0e42cb482da6be36caa63cd922>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.n_onResume(Native Method)
at md5f0702f468598c68ce18586502249fb40.PasswordActivity.onResume(PasswordActivity.java:103)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
at android.app.Activity.performResume(Activity.java:7017)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3622)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3687)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:6623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435)
at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:272)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2973)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2884)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
at javax.crypto.Cipher.init(Cipher.java:1329)
at javax.crypto.Cipher.init(Cipher.java:1267)
... 13 more

10.04.2019 17:16:56:48 -- status message: Initializing...
10.04.2019 17:16:56:49 -- status submessage:
10.04.2019 17:16:56:145 -- status message: Lade Datenbank…
10.04.2019 17:16:56:153 -- System.IO.FileNotFoundException: gdrive://carlo.lf@gmail.com/ClfDatabase.kdbx is trashed! ---> Java.IO.FileNotFoundException: gdrive://carlo.lf@gmail.com/ClfDatabase.kdbx is trashed!
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <daf82fa226e64866b6883f2960c1a0f1>:0
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <f53e43de1d6c43078eb67fc63a0181e1>:0
  at Keepass2android.Javafilestorage.GoogleDriveFileStorage.OpenFileForRead (System.String p0) [0x00062] in <bbfdbb1fb19a4f0a8a8c95bc1465a6cb>:0
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <d9555282dea14061ab4400355adad9e4>:0
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: gdrive://carlo.lf@gmail.com/ClfDatabase.kdbx is trashed!
at keepass2android.javafilestorage.GoogleDriveFileStorage.getFileForPath(GoogleDriveFileStorage.java:318)
at keepass2android.javafilestorage.GoogleDriveFileStorage.openFileForRead(GoogleDriveFileStorage.java:296)

  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <d9555282dea14061ab4400355adad9e4>:0
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <d9555282dea14061ab4400355adad9e4>:0
  at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <d9555282dea14061ab4400355adad9e4>:0
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <d9555282dea14061ab4400355adad9e4>:0
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <d9555282dea14061ab4400355adad9e4>:0
  at keepass2android.PasswordActivity.PreloadDbFile () [0x00037] in <42483a0e42cb482da6be36caa63cd922>:0
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0
  at System.Threading.Tasks.Task.Execute () [0x00010] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0
10.04.2019 17:16:56:181 -- OnFinish message: Ein Fehler ist aufgetreten: gdrive://carlo.lf@gmail.com/ClfDatabase.kdbx is trashed!
10.04.2019 17:16:56:190 -- FP: Create FingerprintDecryption
10.04.2019 17:16:56:192 -- FP: Init for Dec
10.04.2019 17:16:56:199 -- failed to init fingerprint unlock:Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
  at keepass2android.FingerprintDecryption.Init () [0x000d0] in <42483a0e42cb482da6be36caa63cd922>:0
  at keepass2android.PasswordActivity.InitFingerprintUnlock () [0x00088] in <42483a0e42cb482da6be36caa63cd922>:0
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Failed to init Cipher
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
at android.os.Handler.handleCallback(Handler.java:761)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:6623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.security.InvalidKeyException: Only SecretKey is supported
at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:435)
at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:272)
at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2973)
at javax.crypto.Cipher.tryCombinations(Cipher.java:2884)
at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2789)
at javax.crypto.Cipher.chooseProvider(Cipher.java:956)
at javax.crypto.Cipher.init(Cipher.java:1329)
at javax.crypto.Cipher.init(Cipher.java:1267)
... 9 more

10.04.2019 17:17:09:807 -- PasswordActivity.OnPause
10.04.2019 17:17:09:834 -- AppSettingsActivity.OnCreate
10.04.2019 17:17:09:835 -- AppSettingsActivity:apptask=
10.04.2019 17:17:09:928 -- AppSettingsActivity.OnStart
10.04.2019 17:17:09:934 -- AppSettingsActivity.OnResume
10.04.2019 17:17:09:935 --  DB null
10.04.2019 17:17:10:221 -- PasswordActivity.OnStop
`

**Comment by PhilippC** [comment]
One thing that stands out from the log is that KP2A refuses to load the database because it is "trashed". Please try to select "Change database" - "Open database" and browse to the file again. (Note that in GDrive, a file is identified by its ID which does not change if you move a file to trash. KP2A does not access by file path.)

**Comment by carlolf** [comment]
Thanks for this tip - it did work!
