### ISSUE TITLE
KeyboardSwap not working on all devices

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#85]
even though the permission was granted through adb shell, the plugin reports "No permision to change input method." on some devices. Maybe related to OS version? Two reports are from Android 5.

**Comment by raczkow** [comment]
Here's an output from logcat while I press "TEST CONFIGURATION" button
```
D/audio_hw_primary(  353): out_set_parameters: enter: usecase(0: deep-buffer-playback) kvpairs: routing=2
D/audio_hw_extn(  353): audio_extn_set_anc_parameters: anc_enabled:0
D/KP2A    (29080): com.sonymobile.android.handwriting/.HandwritingInputMethodService:com.sonyericsson.textinput.uxp/.glue.InputMethodServiceGlue:com.google.android.googlequicksearchbox/com.google.android.voicesearch.ime.VoiceInputMethodService:keepass2android.keepass2android/keepass2android.softkeyboard.KP2AKeyboard
E/DatabaseUtils(  874): Writing exception to parcel
E/DatabaseUtils(  874): java.lang.SecurityException: Permission denial: writing to settings requires android.permission.WRITE_SETTINGS
E/DatabaseUtils(  874): 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:757)
E/DatabaseUtils(  874): 	at android.content.ContentProvider$Transport.call(ContentProvider.java:379)
E/DatabaseUtils(  874): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
E/DatabaseUtils(  874): 	at android.os.Binder.execTransact(Binder.java:446)
D/audio_hw_primary(  353): start_output_stream: enter: stream(0xb54809c0)usecase(0: deep-buffer-playback) devices(0x2)
D/audio_hw_primary(  353): select_devices: out_snd_device(37: speaker) in_snd_device(0: )
D/hardware_info(  353): hw_info_append_hw_type : device_name = speaker
D/ACDB-LOADER(  353): ACDB -> send_audio_cal, acdb_id = 15, path =  0
D/ACDB-LOADER(  353): ACDB -> send_adm_topology
D/ACDB-LOADER(  353): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER(  353): ACDB -> send_asm_topology
D/ACDB-LOADER(  353): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
D/ACDB-LOADER(  353): ACDB -> send_audtable
D/ACDB-LOADER(  353): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER(  353): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER(  353): ACDB -> send_audvoltable
D/ACDB-LOADER(  353): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
D/ACDB-LOADER(  353): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/ACDB-LOADER(  353): ACDB -> send_afe_cal
D/ACDB-LOADER(  353): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
D/ACDB-LOADER(  353): ACDB -> AUDIO_SET_AFE_CAL
D/audio_hw_primary(  353): select_devices: done
D/KP2AAF  (32706): OnAccEvent
D/KP2AAF  (32706): event: 2048, package = keepass2android.plugin.keyboardswap2
D/KP2AAF  (32706): no com.android.systemui
D/KP2AAF  (32706): don't autofill kp2a.
D/KP2AAF  (32706): OnAccEvent
```

Looks like there is a lack of WRITE_SETTINGS permission.
But I can't grant it:
`Operation not allowed: java.lang.SecurityException: Package keepass2android.plugin.keyboardswap2 has not requested permission android.permission.WRITE_SETTINGS`

**Comment by PhilippC** [comment]
I have added the permission WRITE_SETTINGS (in addition to WRITE_SECURE_SETTINGS) in the manifest hoping that this will fix this. Can you please test in the beta channel of the plugin?
https://play.google.com/apps/testing/keepass2android.plugin.keyboardswap2

**Comment by raczkow** [comment]
Works for me now.
Thanks for preparing the fix.

**Comment by jhwsys** [comment]
Works for me now on ancient Nexus 4 running 5.1.1
Many thanks.

**Comment by DJCrashdummy** [comment]
also had this problem (https://github.com/PhilippC/kp2a_keyboardswap/issues/1) with devices running stock Android 4.4.2 & 5.1.1 and even rooted CyanogenMod 12.1 (based on Android 5.1.1)... but with Keepass2Android 1.04b and KeyboardSwap 1.03 everything works fine now on these devices (also without re-executing the adb-command). :+1: 

i guess this issue can also be closed like the mentioned one.
