### ISSUE TITLE
can not use fingerprint

### ISSUE THREAD

**Issue by TIIEHenry** [PhilippC/keepass2android#866]
can not use fingerprint
java.security.ProviderException:
Keystore operation failed

**Comment by mulsambe** [comment]
I too have problème with fingerprint.
It used to work.
I changed my phone and switched to android 9.
Cannot tell whether it is the new phone or the new android causing the error.

**Comment by JohnLGalt** [comment]
Works on my Pixel 2 XL running Android Q ẞeta 5, and has worked on Pie before I started in on the Q ẞetas.

K2A ver?  Pie exact ver?  K2A app restore on new phone method?

**Comment by mulsambe** [comment]
Thank you for your message.I just checked, and got a message telling to enter password and reset the fingerprint settings.I did that and fingerprint unlock works fine now.I am sorry for the disturbance.And I thank you for your attention and your help.RegardsPatrick BlumLe 13 juil. 2019 20:48, "John L. Galt" <notifications@github.com> a écrit :Works on my Pixel 2 XL running Android Q ẞeta 5, and has worked on Pie before I started in on the Q ẞetas.

K2A ver?  Pie exact ver?  K2A app restore on new phone method?

**Comment by JohnLGalt** [comment]
> 
> 
> can not use fingerprint
> java.security.ProviderException:
> Keystore operation failed

Which device?  Android ver?  K2A version?

**Comment by Andreas-ddl** [comment]
Aosp extended 9 too:
time: 1563636021395
msg: android.security.KeyStoreException: User authentication required
stacktrace: java.security.ProviderException: Keystore operation failed
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:324)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
	at android.widget.CompoundButton.toggle(CompoundButton.java:127)
	at android.widget.RadioButton.toggle(RadioButton.java:76)
	at android.widget.CompoundButton.performClick(CompoundButton.java:132)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25889)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6745)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.security.KeyStoreException: User authentication required
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:813)
	... 18 more

**Comment by TIIEHenry** [comment]
my device is lg v30, android 8.0

**Comment by t-o-o-m** [comment]
Have the same issue now. Tried re-initializing fingerprints, re-installing the app, de-and reactivating fingerprint unlock un the app -  both to no avail. Previously forced basic SafetyNet evaluation.
Samsung S10e, 1.09a-r3

`05.08.2021 07:23:08:633 -- DatabaseSettingsActivity.OnPause 5
05.08.2021 07:23:08:634 -- Timeout start
05.08.2021 07:23:08:646 -- BiometricSetupActivity.OnCreate 6
05.08.2021 07:23:08:646 -- BiometricSetupActivity:apptask= 6
05.08.2021 07:23:08:658 -- BiometricSetupActivity.OnStart 6
05.08.2021 07:23:08:659 -- BiometricSetupActivity.OnResume 6
05.08.2021 07:23:08:659 --  DatabaseIsUnlocked=True 6
05.08.2021 07:23:08:659 -- Timeout cancel
05.08.2021 07:23:08:665 -- BiometricHardware available = 0
05.08.2021 07:23:09:6 -- DatabaseSettingsActivity.OnStop 5
05.08.2021 07:23:09:973 -- FP: Create BiometricEncryption
05.08.2021 07:23:09:975 -- FP: CreateKey 
05.08.2021 07:23:09:988 -- Java.Lang.RuntimeException: Keystore operation failed ---> Java.Lang.Exception: User authentication required
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <779d05ba5af24e759d3f9b3c6a932802>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <779d05ba5af24e759d3f9b3c6a932802>:0 
  at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in <5bf15d4eb5b643d887d450c892d69beb>:0 
  at keepass2android.BiometricEncryption.CreateKey () [0x0006c] in <a80b664dd37144a2b06baa8dfaf3799f>:0 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.security.ProviderException: Keystore operation failed
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:378)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
	at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:192)
	at android.widget.CompoundButton.toggle(CompoundButton.java:145)
	at android.widget.RadioButton.toggle(RadioButton.java:79)
	at android.widget.CompoundButton.performClick(CompoundButton.java:150)
	at android.view.View.performClickInternal(View.java:7838)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29362)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: android.security.KeyStoreException: User authentication required
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1522)
	... 18 more

05.08.2021 07:23:09:988 -- FP: Init for Enc 
05.08.2021 07:23:11:636 -- BiometricSetupActivity.OnPause 6
05.08.2021 07:23:11:636 -- Timeout start
05.08.2021 07:23:11:638 -- Fingerprint: StopListening  without prompt
05.08.2021 07:23:11:650 -- DatabaseSettingsActivity.OnStart 5
05.08.2021 07:23:11:651 -- DatabaseSettingsActivity.OnResume 5
05.08.2021 07:23:11:651 --  DatabaseIsUnlocked=True 5
05.08.2021 07:23:11:652 -- Timeout cancel
05.08.2021 07:23:12:16 -- BiometricSetupActivity.OnStop 6
05.08.2021 07:23:12:17 -- BiometricSetupActivity.OnDestroyTrue 6
`

**Comment by PhilippC** [comment]
does it work with Keepassdroid or KeepassDX?
