### ISSUE TITLE
Cannot access kbdx through WebDav on qnap

### ISSUE THREAD

**Issue by incendor** [PhilippC/keepass2android#956]
When trying to unlock a database file stored on my personal QNAP NAS, accessible through WebDav, I get a generic error message (see attached image) toast, stating "An error occured".
![keepass2android](https://user-images.githubusercontent.com/31634819/64854048-08b53600-d61d-11e9-9f88-ef4c2c52fa83.jpg)

I'd like to get more information about the error  but I cannot figure out where the log file is saved to after enabling it through the settings.

**Comment by ItsCoding** [comment]
Same for me :(

**Comment by Bug-Ninja** [comment]
Same thing is happening to me. I git to see the log through the settings -> app settings -> send log file.

> 
6-10-2019 02:46:42:759 -- KeePass.OnCreate
6-10-2019 02:46:42:764 -- KeePass.OnStart
6-10-2019 02:46:42:764 -- KeePass.OnStart
6-10-2019 02:46:42:834 -- Loaded task keepass2android.NullTask
6-10-2019 02:46:42:880 -- FileSelect.OnCreate
6-10-2019 02:46:42:942 -- FileSelect.OnStart
6-10-2019 02:46:42:995 -- PasswordActivity.OnCreate
6-10-2019 02:46:42:996 -- PasswordActivity:apptask=
6-10-2019 02:46:43:133 -- PasswordActivity.OnStart
6-10-2019 02:46:43:136 -- PasswordActivity.OnResume
6-10-2019 02:46:43:137 --  DB null
6-10-2019 02:46:43:138 -- starting: True, Finishing: False, _performingLoad: False
6-10-2019 02:46:43:142 -- Pre-loading database file starting
6-10-2019 02:46:43:144 -- CFS: OpenWhenNoLocalChanges
6-10-2019 02:46:43:146 -- PasswordActivity.OnPause
6-10-2019 02:46:43:312 -- FileSelect.OnStop
6-10-2019 02:46:43:380 -- FileSelect.OnDestroyTrue
6-10-2019 02:46:43:386 -- KeePass.OnStop
6-10-2019 02:46:43:387 -- KeePass.OnDestroyTrue
6-10-2019 02:46:43:387 -- KeePass.OnDestroyTrue
6-10-2019 02:46:43:413 -- PasswordActivity.OnResume
6-10-2019 02:46:43:413 --  DB null
6-10-2019 02:46:43:414 -- starting: False, Finishing: False, _performingLoad: False
6-10-2019 02:46:58:185 -- LockingActivity: OnActivityResult 
6-10-2019 02:46:58:186 -- PasswordActivity.OnActivityResult 874348/1000
6-10-2019 02:46:58:227 -- status message: Initializing...
6-10-2019 02:46:58:228 -- status submessage: 
6-10-2019 02:46:58:276 -- status message: Database wordt geladen…
6-10-2019 02:46:58:289 -- System.IO.FileNotFoundException:  ---> Java.IO.FileNotFoundException: Exception of type 'Java.IO.FileNotFoundException' was thrown.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <daf82fa226e64866b6883f2960c1a0f1>:0 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
  at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead (System.String p0) [0x00062] in <bbfdbb1fb19a4f0a8a8c95bc1465a6cb>:0 
  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0000d] in <d9555282dea14061ab4400355adad9e4>:0 
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:357)
at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:121)

  at keepass2android.Io.JavaFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00022] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x00006] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00000] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges (KeePassLib.Serialization.IOConnectionInfo ioc, System.String cachedFilePath) [0x00023] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.Io.CachingFileStorage.OpenFileForRead (KeePassLib.Serialization.IOConnectionInfo ioc) [0x0005a] in <d9555282dea14061ab4400355adad9e4>:0 
  at keepass2android.PasswordActivity.PreloadDbFile () [0x00037] in <42483a0e42cb482da6be36caa63cd922>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
6-10-2019 02:46:58:317 -- OnFinish message: Een fout is opgetreden: 
> 

Don't understand too much of what's happening, but apparently the file is not being found. I am starting to wonder if there are any specific things to know when you enter the location an credentials for secure/https webdav?! 

The format I use:
mysubdomain.domain.com:port/keepassfolder/database.kdbx

user name and pass are the same as for ftp and ssh on my server, but should you add the domain with the user name? I start to doubt it all and have tried so many options. File is definely there as I us it for my windows pc as well.

runing android lineageos15.1 /android 8.1 and kp2a 1.07-r1

**Comment by Bug-Ninja** [comment]
In the meanwhile I have tried some other Android apps that make use of webdav, and they popup with the same kind of errors: my android device is somehow not able to see the contents of the webdav, so I guess it is not related de KP2A in my case.

**Comment by Superkikim** [comment]
Hi. Long time with no update on this thread. I guess you didn't solve it. Did you try using the browser ? I have the same problem and I'm using kDrive from Infomaniak. So I don't thing the problem is from keepass. What is your source for the file ? What cloud provider ?
